### PR TITLE
fix(cli): prevent pipeline status errors

### LINKED ISSUE #2004: `pipeline status` ignores specified/selected app
The `pipeline status` command disregards the app name specified by the `-app` flag or selected from the app list, and returns information on the pipeline found in the pipeline manifest.

### PR DESCRIPTION
**Pull request by huanjani**
This fixes two bugs in `pipeline status`-- previously, the command was throwing a nil pointer error when the prompter was being used, and `describe` threw an error when there was no pipeline name. It was also returning the pipeline status of the pipeline found in the manifest if there were no pipelines associated with the app name passed in with the flag. Now the command behaves as expected.

Fixes https://github.com/aws/copilot-cli/issues/2004.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

File: internal/pkg/cli/pipeline_status.go [hunk 1]
```diff
@@ -109,6 +110,9 @@ func (o *pipelineStatusOpts) Ask() error {
 
 // Execute displays the status of the pipeline.
 func (o *pipelineStatusOpts) Execute() error {
+	if o.pipelineName == "" {
```
Comment (efekarakus) [inline internal/pkg/cli/pipeline_status.go]: Is it possible for this to occur? I thought we would be prompting for the pipeline name if not present

Comment (huanjani) [reply internal/pkg/cli/pipeline_status.go]: If it's not present 1. as a flag, 2. in the manifest, or 3. deployed, `askPipelineName` just moves on to `Execute()` and (without this addition) returns 
```
✘ describe status of pipeline: get pipeline status: get pipeline state : InvalidParameter: 1 validation error(s) found.
- minimum field size of 1, GetPipelineStateInput.Name.
```
We never prompt for the user to type in the pipeline name, we only provide a `SelectOne` menu with the deployed pipelines as options.

**Review by efekarakus — APPROVED** [review]

File: internal/pkg/cli/pipeline_status.go (hunk 1 above)
Comment (Lou1415926) [reply internal/pkg/cli/pipeline_status.go]: Should we instead error out at line 174 when we can't find any deployed pipeline, if there is no other concern?

I think the case where there is no pipeline to be shown may be better handled in `pipeline_show.go` instead of describer. Because that'd be more of a UX thing as opposed to a describe thing.

**Review by Lou1415926 — COMMENTED** [review]
LGTM! A small suggestion below ⬇️

File: internal/pkg/cli/pipeline_status.go (hunk 1 above)
Comment (huanjani) [reply internal/pkg/cli/pipeline_status.go]: Ah, sorry if my comment above was misleading. As is, there is no error message if someone tries to show the status of a nonexistent pipeline; they just get some logged info and copilot exits:
```
% copilot pipeline status --app chuckles
No pipeline manifest in workspace for application chuckles, looking for deployed pipelines.
No pipelines found for application chuckles.
```
As is, line 113 is serving as a safety net before the `Describe()` call to prevent that error message.

Comment (huanjani) [reply internal/pkg/cli/pipeline_status.go]: Update: after commit a97a188, no pipelines yields: 
```
% copilot pipeline status --app chuckles
No pipeline manifest in workspace for application chuckles, looking for deployed pipelines.
✘ no pipelines found for application chuckles
```

**Review by iamhopaul123 — APPROVED** [review]
