### PR TITLE
fix(addons): support empty addon dirs

### LINKED ISSUE #2502: Empty addons directory fails the deployment
It looks like having an empty `addons` directory fails the deployment with following error: 

```
deploy service: get addons outputs for namegen: "Resources" field in cloudformation template is not a map
```

### PR DESCRIPTION
**Pull request by buddhike**
This is achieved by turning `ErrAddonsDirNotExist` into
a more general purpose one called `ErrAddonsNotFound`.

It's hard to think of a use-case that different failure
reasons for gathering addons have to be treated differently.

Fixes #2502

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

File: internal/pkg/addon/errors.go [hunk 1]
```diff
@@ -10,13 +10,13 @@ import (
...
-type ErrAddonsDirNotExist struct {
+// ErrAddonsNotFound occurs when an addons directory for a workload is either not found or empty.
+type ErrAddonsNotFound struct {
 	WlName    string
 	ParentErr error
 }
 
-func (e *ErrAddonsDirNotExist) Error() string {
+func (e *ErrAddonsNotFound) Error() string {
 	return fmt.Sprintf("read addons directory for %s: %v", e.WlName, e.ParentErr)
```
Comment (Lou1415926) [inline internal/pkg/addon/errors.go]: nit: could we include a conditional so that this returns a different error message if `e.ParrentErr == nil`? For example,
```suggestion
        if e.ParrentErr != nil {
            return fmt.Sprintf("read addons directory for %s: %v", e.WlName, e.ParentErr)
        }
        return fmt.Sprintf("read addons directory for %s: no addons found", e.WlName)

```

**Review by Lou1415926 — APPROVED** [review]
This looks great! Thank you so much for your contribution 🙏🏼 !! I just have one tiny nit below ⬇️

File: internal/pkg/addon/addons_test.go [hunk 2]
```diff
@@ -51,12 +51,72 @@ func TestAddons_Template(t *testing.T) {
...
+					wlName: testSvcName,
+					ws:     ws,
+				}
+			},
+			wantedErr: &ErrAddonsNotFound{
+				WlName:    testSvcName,
+				ParentErr: nil,
+			},
+		},
+		"return ErrAddonsNotFound if addons directory is empty in a job": {
```
Comment (efekarakus) [inline internal/pkg/addon/addons_test.go]: nit: looks like we can remove this test, it's the same one as above where just the name is changed

File: internal/pkg/addon/addons_test.go [hunk 3]
```diff
@@ -51,12 +51,72 @@ func TestAddons_Template(t *testing.T) {
...
+					wlName: testJobName,
+					ws:     ws,
+				}
+			},
+			wantedErr: &ErrAddonsNotFound{
+				WlName:    testJobName,
+				ParentErr: nil,
+			},
+		},
+		"return ErrAddonsNotFound if addons directory does not contain yaml files in a service": {
```
Comment (efekarakus) [inline internal/pkg/addon/addons_test.go:74]: awesome testcase!

File: internal/pkg/addon/addons_test.go [hunk 4]
```diff
@@ -51,12 +51,72 @@ func TestAddons_Template(t *testing.T) {
...
+					wlName: testSvcName,
+					ws:     ws,
+				}
+			},
+			wantedErr: &ErrAddonsNotFound{
+				WlName:    testSvcName,
+				ParentErr: nil,
+			},
+		},
+		"return ErrAddonsNotFound if addons directory does not contain yaml files in a job": {
```
Comment (efekarakus) [inline internal/pkg/addon/addons_test.go]: nit: same here we can remove this one

**Review by efekarakus — APPROVED** [review]
Looks great! If it's possible to address @Lou1415926's recommendation then we'll remove the "do-not-merge" label from the PR and our bot will automatically merge your pull request.

Thank you so much for the contribution 🥳

File: internal/pkg/addon/errors.go (hunk 1 above)
Comment (buddhike) [reply internal/pkg/addon/errors.go]: Great idea, will update this shortly. Thanks @Lou1415926 🙏🏾

File: internal/pkg/addon/addons_test.go (hunk 2 above)
Comment (buddhike) [reply internal/pkg/addon/addons_test.go]: Thanks @efekarakus 🙏🏾. I was a bit confused about this too. I followed the pattern in `return ErrAddonsNotFound if addons doesn't exist in a service` and `return ErrAddonsNotFound if addons doesn't exist in a job` tests nevertheless. I thought the original author may have included this to detect that workload name is correctly reflected in error (i.e. not a fixed string 😄). I will remove them now.

File: internal/pkg/addon/errors.go (hunk 1 above)
Comment (buddhike) [reply internal/pkg/addon/errors.go]: @Lou1415926 , This is the first error I see with some formatting logic. Should we include a test case for this?

Comment (Lou1415926) [reply internal/pkg/addon/errors.go]: @buddyspike Yay thanks for asking!! Currently we don't include unit tests for custom errors' formatting logic anywhere, but I think it'd be great to have them in the future. That'd be a refactoring that we can do on our end though. I think it's fine for this PR to go without it 🚢.

Comment (buddhike) [reply internal/pkg/addon/errors.go]: Awesome! I asked the question after I wrote the test lolz. I didn't include it in my patch but I'll post it here anyway 😊. 

```
package addon

import (
	"errors"
	"fmt"
	"github.com/stretchr/testify/require"
	"testing"
)

func TestErrors(t *testing.T) {
	var (
		wl        = "mysvc"
		parentErr = errors.New("some err")
	)

	testCases := map[string]struct {
		error     func() error
		wantedMsg string
	}{
		"returns a message including parent error": {
			error: func() error {
				return &ErrAddonsNotFound{
					WlName:    wl,
					ParentErr: parentErr,
				}
			},
			wantedMsg: fmt.Sprintf("read addons directory for %s: %v", wl, parentErr),
		},
		"returns no addons found message": {
			error: func() error {
				return &ErrAddonsNotFound{
					WlName: wl,
				}
			},
			wantedMsg: fmt.Sprintf("read addons directory for %s: no addons found", wl),
		},
	}

	for name, tc := range testCases {
		t.Run(name, func(t *testing.T) {
			// GIVEN
			err := tc.error()

			// WHEN
			msg := err.Error()

			// THEN
			require.Equal(t, tc.wantedMsg, msg)
		})
	}
}

```

Comment (Lou1415926) [reply internal/pkg/addon/errors.go]: this is awesome!! thanks ❤️
