### PR TITLE
fix: allow importing public subnets with no MapPublicIPOnLaunch

### LINKED ISSUE #1724: copilot env init does not see existing subnets.
VPC has 2 public and 2 private subnets.
All are visible with profile used, yet "copilot env init" with arguments and with prompts, fails to acknowledge subnets.

See detail below:

$  copilot env init
What is your environment's name? dev
Which credentials would you like to use to create dev? [profile ec_copilot]
Would you like to use the default configuration for a new production environment?
    - A new VPC with 2 AZs, 2 public subnets and 2 private subnets
    - A new ECS Cluster
    - New IAM Roles to manage services in your environment
 No, I'd like to import existing resources (VPC, subnets).
Which VPC would you like to use? vpc-084303080a6fd9ea2
✘ No existing public subnets were found in VPC vpc-084303080a6fd9ea2. You can either:
- Create new public subnets and then import them.
- Use the default Copilot environment configuration.✘ select public subnets: no existing subnets found
$
$ aws --profile ec_copilot ec2 describe-subnets --filters Name=vpc-id,Values=vpc-084303080a6fd9ea2 --query 'Subnets[].{Name:Tags[?Key==`Name`]|[0].Value,Subnetid:SubnetId,VpcID:VpcId}' --output text
Private Subnet  subnet-062b4e7f3cfb95007        vpc-084303080a6fd9ea2
Private subnet  subnet-03c13da51c8844ae0        vpc-084303080a6fd9ea2
Public Subnnet  subnet-031805325a522ba69        vpc-084303080a6fd9ea2
Public subnet   subnet-0d452e2620153c98f        vpc-084303080a6fd9ea2

### LINKED ISSUE #2287: Import VPC with Public Subnets
I'm trying to use the import feature. When selecting my existing VPC which it finds, it does not select the public subnets that are available. I saw [1724](https://github.com/aws/copilot-cli/issues/1724) was closed and the final comment was that this support is now available for launching tasks in private subnets with imported vpcs. Is this done outside of the import feature? 

Like the user in 1724, we do not auto-enable ipv4 on resources created in public subnets due to security concerns. 

```
What is your environment's name? 
Would you like to use the default configuration for a new environment?
    - A new VPC with 2 AZs, 2 public subnets and 2 private subnets
    - A new ECS Cluster
    - New IAM Roles to manage services and jobs in your environment
 No, I'd like to import existing resources
Which VPC would you like to use? vpc-xxx
✘ No existing public subnets were found in VPC vpc-xxx. You can either:
- Create new public subnets and then import them.
- Use the default Copilot environment configuration.✘ select public subnets: no existing subnets found
```

### PR DESCRIPTION
**Pull request by iamhopaul123**
fixes #1724, fixes #2287

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

File: internal/pkg/aws/ec2/ec2.go [hunk 1]
```diff
@@ -20,35 +20,6 @@ const (
 	TagFilterName = "tag:%s"
 )
 
-// ListVPCSubnetsOpts sets up optional parameters for ListVPCSubnets function.
-type ListVPCSubnetsOpts func([]*ec2.Subnet) []*ec2.Subnet
-
-// FilterForPublicSubnets is used to filter to get public subnets.
-func FilterForPublicSubnets() ListVPCSubnetsOpts {
```
Comment (efekarakus) [inline internal/pkg/aws/ec2/ec2.go:27]: Should we not be figuring out if a subnet has an internet gateway? so that we filter out the ones that are not relevant

Comment (iamhopaul123) [reply internal/pkg/aws/ec2/ec2.go:27]: It would be very difficult to tell since we need to check
1. if the VPC has an internet gateway attached to it
2. describe the route table check if it has route to the internet gateway and check if the route table is associated with the subnet (we would need to do it for every subnet within the VPC)

File: internal/pkg/cli/env_init.go [hunk 2]
```diff
@@ -483,11 +483,11 @@ If you proceed without public subnets, you will not be able to deploy Load Balan
...
 	}
 	if o.importVPC.PrivateSubnetIDs == nil {
-		privateSubnets, err := o.selVPC.PrivateSubnets(envInitPrivateSubnetsSelectPrompt, "", o.importVPC.ID)
+		privateSubnets, err := o.selVPC.Subnets(envInitPrivateSubnetsSelectPrompt, "", o.importVPC.ID)
 		if err != nil {
 			if err == selector.ErrSubnetsNotFound {
-				log.Errorf(`No existing private subnets were found in VPC %s. You can either:
-- Create new private subnets and then import them.
+				log.Errorf(`No existing subnets were found in VPC %s. You can either:
+- Create new subnets and then import them as private subnets.
```
Comment (Lou1415926) [inline internal/pkg/cli/env_init.go]: I see it a bit confusing to say 'import them as private subnets', since whether they're private subnets doesn't depend on how they import them 🤔

File: internal/pkg/aws/ec2/ec2.go (hunk 1 above)
Comment (bvtujo) [reply internal/pkg/aws/ec2/ec2.go:27]: Is the drawback that this is too fragile? If we can provide a good experience by making these API calls and if there are no valid subnets, prompt customers what changes they'd need to make to their subnet in order for it to be useful to Copilot?

**Review by bvtujo — APPROVED** [review]

File: internal/pkg/aws/ec2/ec2.go (hunk 1 above)
Comment (efekarakus) [reply internal/pkg/aws/ec2/ec2.go:27]: It's not too bad I think. We can describe the route tables for a given VPC from the user:
```
$ aws ec2 describe-route-tables --filters Name=vpc-id,Values=vpc-03e4614a3d0217256
```
In the response we'll look for `SubnetId` under `Associations` and for `Routes` to have a `GatewayId` that starts with `igw-`:
<details>
  <summary> View JSON response </summary>
  
  ```json
"Associations": [
    {
        "Main": false,
        "RouteTableAssociationId": "rtbassoc-096f8559b5e31d9d3",
        "RouteTableId": "rtb-073d682766628c37f",
        "SubnetId": "subnet-018ccb78d353cec9b",
        "AssociationState": {
            "State": "associated"
        }
    },
    {
        "Main": false,
        "RouteTableAssociationId": "rtbassoc-0ebf8e431225c1b20",
        "RouteTableId": "rtb-073d682766628c37f",
        "SubnetId": "subnet-005dc83a6473feee7",
        "AssociationState": {
            "State": "associated"
        }
    }
],
"PropagatingVgws": [],
"RouteTableId": "rtb-073d682766628c37f",
"Routes": [
    {
        "DestinationCidrBlock": "10.0.0.0/16",
        "GatewayId": "local",
        "Origin": "CreateRouteTable",
        "State": "active"
    },
    {
        "DestinationCidrBlock": "0.0.0.0/0",
        "GatewayId": "igw-058421418aeacb2f0",
        "Origin": "CreateRoute",
        "State": "active"
    }
]
```
</details>

The only downside is we won't have tags associated with the subnets, but we can make two network calls to get that info.

Comment (iamhopaul123) [reply internal/pkg/aws/ec2/ec2.go:27]: ok addressed!

File: internal/pkg/aws/ec2/ec2.go [hunk 3]
```diff
@@ -186,23 +161,65 @@ func (c *EC2) HasDNSSupport(vpcID string) (bool, error) {
...
-// ListVPCSubnets lists all subnets given a VPC ID.
-func (c *EC2) ListVPCSubnets(vpcID string, opts ...ListVPCSubnetsOpts) ([]string, error) {
-	respSubnets, err := c.subnets(Filter{
+// VPCSubnets are all subnets within a VPC.
+type VPCSubnets struct {
+	Public  []VPCResource
+	Private []VPCResource
+}
+
+// ListVPCSubnets lists all subnets given a VPC ID. Note that public subnets
```
Comment (huanjani) [inline internal/pkg/aws/ec2/ec2.go]:
```suggestion
// ListVPCSubnets lists all subnets with a given VPC ID. Note that public subnets
```

File: internal/pkg/aws/ec2/ec2.go [hunk 4]
```diff
@@ -186,23 +161,65 @@ func (c *EC2) HasDNSSupport(vpcID string) (bool, error) {
...
+// are subnets associated with a route table that routed by an internet gateway.
```
Comment (huanjani) [inline internal/pkg/aws/ec2/ec2.go]: the wording of my fix is kinda weird but maybe a little clearer? 
```suggestion
// are subnets associated with an internet gateway through a route table.
```

File: internal/pkg/aws/ec2/ec2.go [hunk 5]
```diff
@@ -186,23 +161,65 @@ func (c *EC2) HasDNSSupport(vpcID string) (bool, error) {
...
+// And the rest subnets are private subnets.
```
Comment (huanjani) [inline internal/pkg/aws/ec2/ec2.go]:
```suggestion
// And the rest of the subnets are private.
```

File: internal/pkg/cli/env_init.go [hunk 6]
```diff
@@ -470,8 +470,8 @@ https://aws.amazon.com/premiumsupport/knowledge-center/ecs-pull-container-api-er
 		publicSubnets, err := o.selVPC.PublicSubnets(envInitPublicSubnetsSelectPrompt, "", o.importVPC.ID)
 		if err != nil {
 			if err == selector.ErrSubnetsNotFound {
-				log.Warningf(`No existing public subnets were found in VPC %s.
-If you proceed without public subnets, you will not be able to deploy Load Balanced Web Services in this environment.
+				log.Warningf(`No existing subnets were found in VPC %s.
+If you proceed without specifying public subnets, you will not be able to deploy Load Balanced Web Services in this environment.
```
Comment (huanjani) [inline internal/pkg/cli/env_init.go]: Should we say "specifying two public subnets"?

**Review by huanjani — APPROVED** [review]
Looks great! Just some tiny wording nits. Feel free to remove DNM label when those are addressed (or ignored) 😄 .

File: internal/pkg/aws/ec2/ec2.go [hunk 7]
```diff
@@ -86,37 +59,39 @@ func New(s *session.Session) *EC2 {
 	}
 }
 
-// VPC contains the ID and name of a VPC.
-type VPC struct {
+// VPCResource contains the ID and name of a VPCResource.
+type VPCResource struct {
```
Comment (efekarakus) [inline internal/pkg/aws/ec2/ec2.go]: Why this rename? I liked reading `ec2.VPC` and `ec2.Subnets` better

File: internal/pkg/aws/ec2/ec2.go [hunk 8]
```diff
@@ -186,23 +161,65 @@ func (c *EC2) HasDNSSupport(vpcID string) (bool, error) {
...
 }
 
-// ListVPCSubnets lists all subnets given a VPC ID.
-func (c *EC2) ListVPCSubnets(vpcID string, opts ...ListVPCSubnetsOpts) ([]string, error) {
-	respSubnets, err := c.subnets(Filter{
+// VPCSubnets are all subnets within a VPC.
+type VPCSubnets struct {
+	Public  []VPCResource
+	Private []VPCResource
+}
```
Comment (efekarakus) [inline internal/pkg/aws/ec2/ec2.go]: 🤔 this is confusing, why is a subnet composed of VPC resources? 

What do you think of refactoring to:
```go
type Subnet struct {
   resource
   Public  bool
   VPCID   string
}

func (c *EC2) ListVPCSubnets(vpcID string) ([]Subnet, error) {
```

File: internal/pkg/aws/ec2/ec2.go (hunk 7 above)
Comment (efekarakus) [reply internal/pkg/aws/ec2/ec2.go]: Oh I see you wanted to use ID and Name across resources, what do you thikn of this alternative:
```go
type resource struct {
   ID     string
   Name   string
}

type VPC resource
```

File: internal/pkg/aws/ec2/ec2.go [hunk 9]
```diff
@@ -279,6 +280,26 @@ func (c *EC2) subnets(filters ...Filter) ([]*ec2.Subnet, error) {
 	return subnets, nil
 }
 
+func (c *EC2) routeTables(filters ...Filter) ([]*ec2.RouteTable, error) {
+	inputFilters := toEC2Filter(filters)
+	var routeTables []*ec2.RouteTable
+	input := &ec2.DescribeRouteTablesInput{
+		Filters: inputFilters,
+	}
```
Comment (efekarakus) [inline internal/pkg/aws/ec2/ec2.go]: nit:
```suggestion
	var routeTables []*ec2.RouteTable
	input := &ec2.DescribeRouteTablesInput{
		Filters: toEC2Filter(filters),
	}
```

File: internal/pkg/cli/env_init.go (hunk 6 above)
Comment (efekarakus) [reply internal/pkg/cli/env_init.go]: yeah maybe "without at least two public subnets"

File: internal/pkg/term/selector/ec2.go [hunk 10]
```diff
@@ -67,27 +67,44 @@ func (s *EC2Select) VPC(prompt, help string) (string, error) {
 
 // PublicSubnets has the user multiselect public subnets given the VPC ID.
 func (s *EC2Select) PublicSubnets(prompt, help, vpcID string) ([]string, error) {
-	return s.subnet(prompt, help, vpcID, ec2.FilterForPublicSubnets())
+	return s.subnet(prompt, help, vpcID, true)
```
Comment (efekarakus) [inline internal/pkg/term/selector/ec2.go]: boolean params are usually a codesmell because it's not clear what the boolean stands for: https://martinfowler.com/bliki/FlagArgument.html

```go
return s.selectPublicSubnets(prompt, help, vpcID)
return s.selectPrivateSubnets(prompt, help, vpcID)

func (s *EC2Select) selectPublicSubnets(prompt, help, vpcID string) ([]string, error) {
   subnets, err := s.ec2.ListVPCSubnets(vpcID)
   if err != nil { ... }
   publicSubnets := .... // for-loop and filter on .Public
   
   return s.selectSubnets(prompt, help, publicSubnets) // This method is common for s.selectPrivateSubnets
}
```

File: internal/pkg/aws/ec2/ec2.go (hunk 8 above)
Comment (iamhopaul123) [reply internal/pkg/aws/ec2/ec2.go]: hmm following the logic here https://github.com/aws/copilot-cli/pull/2457#discussion_r654026948 i think it might be clearer to just have
```go
// VPCSubnets are all subnets within a VPC.
type VPCSubnets struct {
	Public  []Subnet
	Private []Subnet
}
```

File: internal/pkg/aws/ec2/ec2.go [hunk 11]
```diff
@@ -86,37 +59,70 @@ func New(s *session.Session) *EC2 {
 	}
 }
 
-// VPC contains the ID and name of a VPC.
-type VPC struct {
+// Resource contains the ID and name of a EC2 resource.
+type Resource struct {
```
Comment (efekarakus) [inline internal/pkg/aws/ec2/ec2.go:63]: does this need to be public?   
You can still access the public fields even if the embedded struct is private so you should be able to do `vpc.ID`

**Review by efekarakus — APPROVED** [review]
Feel free to merge after the nit!

File: internal/pkg/aws/ec2/ec2.go (hunk 11 above)
Comment (iamhopaul123) [reply internal/pkg/aws/ec2/ec2.go:63]: It's for unit test in the other pkg https://github.com/aws/copilot-cli/pull/2457/files#diff-c870c9dd1b1575fbdd8a11486b23829bc2d95e6121202ea397c5f14c528fa53dR48-R50
