### PR TITLE
fix: stop truncating logs to 10 at a time when running `svc logs --follow`

### LINKED ISSUE #3220: `svc logs --follow` doesn't print all logs
Expected behavior
`copilot svc logs --follow` should print all lines printed by the application since the `copilot svc logs --follow` command was executed.

Actual behavior
`copilot svc logs --follow` only prints 10-line "chunks" of output. It doesn't print all lines. In practice, it seems to print the last 10 lines resulting from a test request. I'm assuming the fact that the "chunk" is 10 lines of output is related to the default value for `--limit` (10).

I seem to be able to get around this with `copilot svc logs --follow --limit 10000`, but this feels clumsy and I'm not confident that all logged lines are being printed.

Am I misunderstanding how `copilot svc logs --follow` is intended to be used?

### PR DESCRIPTION
**Pull request by efekarakus**
Fixes #3220 

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the Apache 2.0 License.

### CODE REVIEW

File: internal/pkg/logging/service.go [hunk 1]
```diff
@@ -65,14 +67,29 @@ func (o WriteLogEventsOpts) limit() *int64 {
...
 	return aws.Int64(defaultServiceLogsLimit)
 }
 
+func (o WriteLogEventsOpts) startTime(now func() time.Time) *int64 {
+	if o.StartTime != nil {
+		return o.StartTime
+	}
+	if o.Follow {
+		// Start following log events from current timestamp.
+		return aws.Int64(now().Unix() * 1000) // Multiplied by 1000 to convert the Unix() timestamp in seconds to milliseconds
```
Comment (Lou1415926) [inline internal/pkg/logging/service.go]: nit: [or alternatively](https://pkg.go.dev/time#Time.UnixMilli)...
```suggestion
		return aws.Int64(now().UnixMilli())
```

**Review by Lou1415926 — APPROVED** [review]

File: internal/pkg/logging/service_test.go [hunk 2]
```diff
@@ -54,9 +55,9 @@ firelens_log_router/fcfe4 10.0.0.00 - - [01/Jan/1970 01:01:01] "WARN some warnin
 		},
 	}
 	mockLimit := aws.Int64(100)
-	mockDefaultLimit := aws.Int64(10)
 	var mockNilLimit *int64
 	mockStartTime := aws.Int64(123456789)
+	mockCurrentTimestamp := time.Date(2020, 11, 23, 0, 0, 0, 0, time.UTC) // Copilot GA date :).
```
Comment (huanjani) [inline internal/pkg/logging/service_test.go:60]: 😻

File: internal/pkg/logging/service.go (hunk 1 above)
Comment (efekarakus) [reply internal/pkg/logging/service.go]: wow I had no idea this method existed 😂 fixed!

I also changed it in other places in the codebase where we multiplied by 1000

**Review by iamhopaul123 — APPROVED** [review]
