### PR TITLE
fix(manifest): allow depending on firelens container

### LINKED ISSUE #3053: Main container can not `depends_on` logging container(firelens_log_router)
I would like to depend on `firelens_log_router` on the main container. But current copilot does not support this.
```
$ copilot deploy
✘ execute svc deploy: validate manifest against environment sbx: validate container dependencies: container firelens_log_router does not exist
```

manifest
--------
```yml
image:
  depends_on:
    firelens_log_router: HEALTHY # I think `logging stanza` does not support `healthcehck` so please ignore `HEALTHY`.

logging:
  ...
```

### PR DESCRIPTION
**Pull request by iamhopaul123**
fixes #3053 

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the Apache 2.0 License.

### CODE REVIEW

File: internal/pkg/manifest/validate.go [hunk 1]
```diff
@@ -1180,6 +1185,9 @@ func validateContainerDeps(opts validateDependenciesOpts) error {
 		dependsOn:   opts.imageConfig.DependsOn,
 		isEssential: true,
 	}
+	if !opts.logging.IsEmpty() {
+		containerDependencies[firelensContainerName] = containerDependency{}
```
Comment (efekarakus) [inline internal/pkg/manifest/validate.go:1189]: so it's not possible for the firelens container to depend on another one?

**Review by efekarakus — APPROVED** [review]

File: internal/pkg/manifest/validate.go (hunk 1 above)
Comment (iamhopaul123) [reply internal/pkg/manifest/validate.go:1189]: Right now it's not configurable and it is always an essential one.

**Review by huanjani — APPROVED** [review]
lgtm!
