### PR TITLE
fix: custom resource upload should be namespaced by env

### LINKED ISSUE #3984: Pipeline for service fails if service is not already deployed to environment.
We have a pipeline running in a build account, it deploys to an environment in another account. If the service hasn't already been deployed to an account the cloudformation stage will fail with some variation of a S3 permissions error.

`Resource handler returned message: "Your access has been denied by S3, please make sure your request credentials have permission to GetObject for stackset-app-infrastruc-pipelinebuiltartifactbuc-xyz/manual/scripts/custom-resources/envcontrollerfunction/3ffcf03598029891816b7ce2d1ff14fdd8079af4406a0cfeff1d4aa0109dcd7d.zip. S3 Error Code: AccessDenied. S3 Error Message: Access Denied (Service: Lambda, Status Code: 403, Request ID: aae1a382-3a20-4345-80ca-ac160bc75175)" (RequestToken: ccbd59fc-caa1-dd84-e5a9-9b5e871070bb, HandlerErrorCode: AccessDenied)`

We are potentially going to have many apps, and many environments so at best this will be very inconvenient. Worse we restrict access to our prod account so manual deploys are not be possible.

### PR DESCRIPTION
**Pull request by iamhopaul123**
Fixes #3984

Screen Shot 2022-09-15 at 9 06 01 AM

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the Apache 2.0 License.

### CODE REVIEW

File: internal/pkg/aws/s3/s3.go [hunk 1]
```diff
@@ -56,28 +54,6 @@ func New(s *session.Session) *S3 {
 	}
 }
 
-// ZipAndUpload zips all files and uploads the zipped file to an S3 bucket under the specified key.
-// Per s3's recommendation https://docs.aws.amazon.com/AmazonS3/latest/userguide/about-object-ownership.html:
-// The bucket owner, in addition to the object owner, is granted full control.
-func (s *S3) ZipAndUpload(bucket, key string, files ...NamedBinary) (string, error) {
```
Comment (efekarakus) [inline internal/pkg/aws/s3/s3.go:62]: yay! thank you for deleting dead code

File: internal/pkg/cli/deploy/env.go [hunk 2]
```diff
@@ -89,7 +89,7 @@ func NewEnvDeployer(in *NewEnvDeployerInput) (*envDeployer, error) {
 		env: in.Env,
 
 		templateFS:       template.New(),
-		s3:               s3.New(envRegionSession),
+		s3:               s3.New(envManagerSession),
```
Comment (efekarakus) [inline internal/pkg/cli/deploy/env.go:92]: I actually don't get why this issue is happening  if the object is uploaded with bucket ownership: 
https://github.com/aws/copilot-cli/blob/4b45d6682865598b368819023f15185b6d572b93/internal/pkg/aws/s3/s3.go#L217

and the bucket allows all actions from the env accounts:
https://github.com/aws/copilot-cli/blob/4b45d6682865598b368819023f15185b6d572b93/internal/pkg/template/templates/app/cf.yml#L74-L82

Then why is there an access denied error? What am I missing? I'd have guessed that as long as the objects are uploaded with BucketOwnership then it wouldn't matter if they're overriden.

**Comment by efekarakus** [comment]
OK I finally get what is going on 

The buckets are created by default with [`BucketOwnership` set to `ObjectWriter`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-s3-bucket-ownershipcontrolsrule.html).

Everything gets fixed if we change the `BucketOwnership` to `BucketOwnerEnforced` or `BucketOwnerPreferred` in the app template (we don't have to touch any of our `s3.go` code). 
In these scenarios, the access control to the data becomes based on the BucketPolicy instead of these confusing ACLs:
https://github.com/aws/copilot-cli/blob/35772b453f37f4b82a2a27c932a8d661f7d6ee15/internal/pkg/template/templates/app/cf.yml#L71-L82

My recommendation is instead of namespacing the custom resources, we should change the control ownership to be `BucketOwnerEnforced` and force the users that need the fix to run `copilot app upgrade`.

File: internal/pkg/deploy/upload/customresource/customresource.go [hunk 3]
```diff
@@ -84,15 +83,15 @@ func (cr *CustomResource) init() error {
 	for _, file := range cr.files {
 		f, err := w.Create(file.name)
 		if err != nil {
-			return fmt.Errorf("create zip file %q for custom resource %q: %v", file.name, cr.FunctionName(), err)
+			return fmt.Errorf("create zip file %q for custom resource %q: %v", file.name, cr.name, err)
```
Comment (efekarakus) [inline internal/pkg/deploy/upload/customresource/customresource.go]: nit: can we use `.Name()` instead to rely on the public interface of the type rather than the internal data structure

**Review by efekarakus — COMMENTED** [review]
Should we update the `TemplateVersion: 'v1.1.0'` field in the app template and `deploy.LatestAppTemplateVersion` to `v1.2.0` ?

File: internal/pkg/deploy/upload/customresource/customresource.go (hunk 3 above)
Comment (iamhopaul123) [reply internal/pkg/deploy/upload/customresource/customresource.go]: > Should we update the TemplateVersion: 'v1.1.0' field in the app template and deploy.LatestAppTemplateVersion to v1.2.0 ?

No we don't because it is not released yet.

File: internal/pkg/aws/s3/s3.go [hunk 4]
```diff
@@ -56,28 +54,6 @@ func New(s *session.Session) *S3 {
 	}
 }
 
-// ZipAndUpload zips all files and uploads the zipped file to an S3 bucket under the specified key.
```
Comment (Lou1415926) [inline internal/pkg/aws/s3/s3.go:59]: :rip

File: internal/pkg/cli/deploy/env.go (hunk 2 above)
Comment (Lou1415926) [reply internal/pkg/cli/deploy/env.go:92]: thanks for fixing the session here!

File: internal/pkg/cli/deploy/svc.go [hunk 5]
```diff
@@ -208,9 +207,6 @@ func newWorkloadDeployer(in *WorkloadDeployerInput) (*workloadDeployer, error) {
 	if err != nil {
 		return nil, fmt.Errorf("create default: %w", err)
 	}
-	if err != nil {
```
Comment (Lou1415926) [inline internal/pkg/cli/deploy/svc.go:211]: :doge

**Review by Lou1415926 — APPROVED** [review]

**Review by efekarakus — APPROVED** [review]
