### PR TITLE
fix(cicd): upload pipeline template to S3 bucket to prevent hitting size limit

### LINKED ISSUE #2068: upload pipeline template to S3 bucket to handle larger capacities
Hello,
I added another environment to my pipeline and got the following error "'templateBody' failed to satisfy constraint: Member must have length less than or equal to 51200".
For my understanding this is a CFN limitation, how can i avoid that?

### PR DESCRIPTION
**Pull request by huanjani**
The maximum size of a Cloudformation template body is 51,200 bytes. (https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cloudformation-limits.html)

When users have multiple services deployed to multiple environments and they want to build a pipeline, they risk hitting this limit. 

By uploading the template to an S3 bucket, then passing the template URL to the ChangeSet, we take advantage of S3's multipart upload functionality (https://docs.aws.amazon.com/AmazonS3/latest/userguide/mpuoverview.html) and circumvent the size limit.

The size limit for a template passed in via URL is 460,800 bytes. (https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cloudformation-stackset.html)

Fixes #2068.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

File: internal/pkg/cli/pipeline_update.go [hunk 1]
```diff
@@ -103,6 +103,75 @@ func (o *updatePipelineOpts) Validate() error {
 	return nil
 }
 
+// Execute creates a new pipeline or updates the current pipeline if it already exists.
+func (o *updatePipelineOpts) Execute() error {
```
Comment (huanjani) [inline internal/pkg/cli/pipeline_update.go:107]: Note: there are no changes to `Execute()`-- in the first commit I just moved this method higher up in the file.

File: internal/pkg/aws/cloudformation/changeset.go [hunk 2]
```diff
@@ -123,6 +124,41 @@ func (cs *changeSet) create(conf *stackConfig) error {
 	return nil
 }
 
+// createWithTemplateURL creates a ChangeSet with the TemplateURL (as opposed to TemplateBody) field, waits until it's created, and returns the ChangeSet ID on success.
```
Comment (SoManyHs) [inline internal/pkg/aws/cloudformation/changeset.go]: nit: do we have a line length limit recommendation?

File: internal/pkg/deploy/cloudformation/pipeline.go [hunk 3]
```diff
@@ -36,8 +38,12 @@ func (cf CloudFormation) PipelineExists(in *deploy.CreatePipelineInput) (bool, e
 }
 
 // CreatePipeline sets up a new CodePipeline for deploying services.
-func (cf CloudFormation) CreatePipeline(in *deploy.CreatePipelineInput) error {
-	s, err := toStack(stack.NewPipelineStackConfig(in))
+func (cf CloudFormation) CreatePipeline(in *deploy.CreatePipelineInput, bucketName string) error {
+	templateURL, err := cf.pushTemplateToS3Bucket(bucketName, stack.NewPipelineStackConfig(in))
```
Comment (SoManyHs) [inline internal/pkg/deploy/cloudformation/pipeline.go:42]: For my own edification, are we always pushing the template to S3 regardless of size? Just wondering if we'd considered only doing that for templates that exceeded a certain size, just to save a roundtrip to S3 downstream.

File: internal/pkg/deploy/cloudformation/pipeline_test.go [hunk 4]
```diff
@@ -87,10 +87,14 @@ func TestCloudFormation_CreatePipeline(t *testing.T) {
 		Stages:          nil,
 		ArtifactBuckets: nil,
 	}
+	mockS3BucketName := "BitterBucket"
```
Comment (SoManyHs) [inline internal/pkg/deploy/cloudformation/pipeline_test.go:90]: !

File: internal/pkg/deploy/cloudformation/pipeline.go (hunk 3 above)
Comment (SoManyHs) [reply internal/pkg/deploy/cloudformation/pipeline.go:42]: Do we tend to have conventions on adding function arguments to existing exported functions? I know that `CreatePipeline` and `UpdatePipeline` are only called internally from other packages, but was wondering if we might consider adding the `bucketName` to `deploy.CreatePipelineInput` within `Execute`, which would save on having to add the argument downstream.

**Review by SoManyHs — APPROVED** [review]
Looks fabulous! ✨ had a few code style questions, but nothing blocking :shipit:

File: internal/pkg/deploy/cloudformation/pipeline.go (hunk 3 above)
Comment (huanjani) [reply internal/pkg/deploy/cloudformation/pipeline.go:42]: > Do we tend to have conventions on adding function arguments to existing exported functions? I know that `CreatePipeline` and `UpdatePipeline` are only called internally from other packages, but was wondering if we might consider adding the `bucketName` to `deploy.CreatePipelineInput` within `Execute`, which would save on having to add the argument downstream.

This did cross my mind (and reminded me of how to pass `shouldOutputJSON` with `env_show` a million years ago)! It does seem cleaner to add it to the input struct; the thing that stopped me was the consideration that `bucketName` isn't strictly "pipeline input." I can make this change, especially if we decide to push only too-big templates!

File: internal/pkg/deploy/cloudformation/pipeline_test.go (hunk 4 above)
Comment (huanjani) [reply internal/pkg/deploy/cloudformation/pipeline_test.go:90]: a la Bitbucket, not a bucket full of bitterness!

File: internal/pkg/deploy/cloudformation/pipeline.go (hunk 3 above)
Comment (SoManyHs) [reply internal/pkg/deploy/cloudformation/pipeline.go:42]: > the thing that stopped me was the consideration that bucketName isn't strictly "pipeline input." 

totes, I was looking at that too, but also thought that since we control that data structure within the `deploy` package it might be okay since we're wrapping the SDK data structure with what we need. I don't think it's a big enough deal to warrant having to change this right now, but wanted to check to see if we tend to follow any particular design patterns for this kind of thing!

Comment (huanjani) [reply internal/pkg/deploy/cloudformation/pipeline.go:42]: > For my own edification, are we always pushing the template to S3 regardless of size? Just wondering if we'd considered only doing that for templates that exceeded a certain size, just to save a roundtrip to S3 downstream.

Yup, all templates will get pushed. To keep things simple and bc S3 is cheap! :)

File: internal/pkg/aws/cloudformation/changeset.go [hunk 5]
```diff
@@ -123,6 +124,41 @@ func (cs *changeSet) create(conf *stackConfig) error {
 	return nil
 }
 
+// createWithTemplateURL creates a ChangeSet with the TemplateURL (as opposed to TemplateBody) field, waits until it's created, and returns the ChangeSet ID on success. There is a 1,024 max length for the TemplateURL value.
+func (cs *changeSet) createWithTemplateURL(conf *stackConfig) error {
```
Comment (efekarakus) [inline internal/pkg/aws/cloudformation/changeset.go]: What do you think about modifying the `create` method instead of creating a new method? right now there is a lot of common code between the two methods:
```go
...
TemplateBody: conf.TemplateBody,
TemplateURL: conf.TemplateURL,
...
```
I liked your initial proposal of having two constructors for `Stack`: `NewStack(name, tplBody string)` or `NewStackWithURL(name, tplURL string)`

File: internal/pkg/aws/cloudformation/changeset.go [hunk 6]
```diff
@@ -188,6 +224,22 @@ func (cs *changeSet) execute() error {
 // createAndExecute calls create and then execute.
 // If the change set is empty, returns a ErrChangeSetEmpty.
 func (cs *changeSet) createAndExecute(conf *stackConfig) error {
+	if strings.Contains(conf.Template, "pipeline.stack.yml") {
```
Comment (efekarakus) [inline internal/pkg/aws/cloudformation/changeset.go]: We talked about this offline :) but sharing here to spread information:

We should try to make the `aws/*` pkgs libraries that higher-level packages can consume. For example,  it would awesome if this package is agnostic to the underlying template and can be used to upload service or job cfn templates.

File: internal/pkg/aws/s3/s3.go [hunk 7]
```diff
@@ -31,6 +31,7 @@ type s3ManagerAPI interface {
 type s3API interface {
 	ListObjectVersions(input *s3.ListObjectVersionsInput) (*s3.ListObjectVersionsOutput, error)
 	DeleteObjects(input *s3.DeleteObjectsInput) (*s3.DeleteObjectsOutput, error)
+	CreateBucket(input *s3.CreateBucketInput) (*s3.CreateBucketOutput, error)
```
Comment (efekarakus) [inline internal/pkg/aws/s3/s3.go]: no longer needed :D

File: internal/pkg/deploy/cloudformation/pipeline.go [hunk 8]
```diff
@@ -86,3 +96,16 @@ func (cf CloudFormation) UpdatePipeline(in *deploy.CreatePipelineInput) error {
 func (cf CloudFormation) DeletePipeline(stackName string) error {
 	return cf.cfnClient.DeleteAndWait(stackName)
 }
+
+func (cf CloudFormation) pushTemplateToS3Bucket(bucket string, config StackConfiguration) (string, error) {
+	template, err := config.Template()
+	if err != nil {
+		return "", err
```
Comment (efekarakus) [inline internal/pkg/deploy/cloudformation/pipeline.go]: nit: do we need to wrap this error?

**Review by efekarakus — COMMENTED** [review]
Looks great! Just a tiny request to remove the conditional from the the `cloudformation` pkg

**Review by efekarakus — APPROVED** [review]
