### PR TITLE
fix(cicd): truncate pipeline name to prevent failures

### LINKED ISSUE #1939: CodeBuild fails in pipeline when the GitHub repository path has a long name
**Issue:** Having a long organisation and github repository name makes the docker build fail in CodeBuild

**Description:**

I have a relatively long GitHub organisation name, and an average sized repository name, but when combined they make up 59 characters. When combined with the uuid and the `pipeline-app-name` the total character count exceeds the [128 character limit docker imposes](https://docs.docker.com/engine/reference/commandline/tag/) for a tag. 

When I looked in the logs for CodeBuild I noticed it was failing on the error `invalid reference format` 

**Workaround:**

I shortened the name of my GitHub repository and verified the build succeeded

It would be great to truncate the tag to a certain length to avoid this problem happening in the future

### PR DESCRIPTION
**Pull request by huanjani**
When building pipelines, we are limited by character maximums for multiple strings:
128 for PipelineRolePolicy, BuildProjectPolicy, etc., and the CODEBUILD_BUILD_ID tag for Docker.
100 for CodePipeline pipeline names.

So that pipelines built from repos with very long names and/or repo provider accounts with very long names do not fail, this change reduces the characters when we generate pipeline names, and throws an error when pipeline names exceed 100 characters in `pipeline update` (in case pipeline names were edited in the pipeline manifest). We limit to 100 to satisfy CodePipeline's pipeline name limit (100), but also to enable the automated tacking on of `-CodepipelinePolicy` and `-BuildprojectPolicy` (and any future policy name suffixes) to the end of the stack names (128). 

The extra characters are omitted _from the front_; at the moment, pipeline names go from general ("pipeline") to specific (repoName or even branchName, if users are [changing pipeline names to enable multiple pipelines from a single repo](https://github.com/aws/copilot-cli/discussions/1925)) so truncating from the front of the string preserves the more valuable information.

In the buildspec, we truncate the string yet again, this time to 128 characters. Again, we cut off excess characters from the front. Here, it is because `-BuildProject-[UUID]` is appended to form the CODEBUILD_BUILD_ID, and we don't want to lose the identifying UUID. We must truncate in two steps because it is possible for a pipeline name (of, say, 100 characters), to successfully generate a CFN stack, but fail in CodeBuild because with the added characters it becomes 150 characters long. 

Fixes #1939.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

File: internal/pkg/cli/pipeline_init.go [hunk 1]
```diff
@@ -554,14 +551,8 @@ func (o *initPipelineOpts) secretName() string {
...
-func (o *initPipelineOpts) pipelineName() (string, error) {
-	if o.provider == ghProviderName {
-		return fmt.Sprintf(fmtGHPipelineName, o.appName, o.githubOwner, o.repoName), nil
-	}
-	if o.provider == ccProviderName {
-		return fmt.Sprintf(fmtCCPipelineName, o.appName, o.repoName), nil
-	}
-	return "", fmt.Errorf("unable to create pipeline name for repo %s from provider %s", o.repoName, o.provider)
+func (o *initPipelineOpts) pipelineName() string {
+	return fmt.Sprintf(fmtPipelineName, o.appName, o.repoName)
```
Comment (efekarakus) [inline internal/pkg/cli/pipeline_init.go]: Should we generate a name by default that is always <= 100 chars? I think right now it's still possible that our generated names are super long.

We should not do this but I was having fun: https://play.golang.org/p/oJvOr5z5e7M . I think let's do the simple thing and truncate at 100 chars

File: internal/pkg/cli/pipeline_update.go [hunk 2]
```diff
@@ -211,6 +211,9 @@ func (o *updatePipelineOpts) Execute() error {
 	if err != nil {
 		return fmt.Errorf("unmarshal pipeline manifest: %w", err)
 	}
+	if len(pipeline.Name) > 100 {
+		return fmt.Errorf("pipeline name must be shorter than 100 characters")
```
Comment (efekarakus) [inline internal/pkg/cli/pipeline_update.go]:
```suggestion
		return fmt.Errorf(`pipeline name '%s' must be shorter than 100 characters`, pipeline.Name)
```

File: templates/cicd/buildspec.yml [hunk 3]
```diff
@@ -35,7 +35,7 @@ phases:
       - envs=$(./copilot-linux env ls --json | jq '.environments[].name' | sed 's/"//g')
       # Generate the cloudformation templates.
       # The tag is the build ID but we replaced the colon ':' with a dash '-'.
-      - tag=$(sed 's/:/-/g' <<<"$CODEBUILD_BUILD_ID")
+      - tag=$(sed 's/:/-/g' <<<"$CODEBUILD_BUILD_ID" | rev | cut -c 1-128 | rev)
```
Comment (efekarakus) [inline templates/cicd/buildspec.yml:40]: lol can you update the comment above to also say that Docker tags need to be limited to 128 chars.

**Review by efekarakus — COMMENTED** [review]
Looks good!

File: templates/cicd/buildspec.yml (hunk 3 above)
Comment (huanjani) [reply templates/cicd/buildspec.yml:40]: Done. Seems silly that there doesn't seem to be a better way to truncate from the front, right?

File: internal/pkg/cli/pipeline_init.go (hunk 1 above)
Comment (huanjani) [reply internal/pkg/cli/pipeline_init.go]: Ha, that's great! 
Added truncation.

File: internal/pkg/cli/pipeline_init.go [hunk 4]
```diff
@@ -552,7 +553,19 @@ func (o *initPipelineOpts) secretName() string {
 }
 
 func (o *initPipelineOpts) pipelineName() string {
```
Comment (efekarakus) [inline internal/pkg/cli/pipeline_init.go:596]: Let's just keep things dumb and less prone to bugs, realistically folks won't have huge app names, if anything it will be the repo name so i think we can just do:
```
if len name <= 100:
   return name
return name[:100]
```

Comment (huanjani) [reply internal/pkg/cli/pipeline_init.go:596]: done

**Review by efekarakus — APPROVED** [review]

File: templates/cicd/buildspec.yml (hunk 3 above)
Comment (Lou1415926) [reply templates/cicd/buildspec.yml:40]: Just for fun: I think `sed 's/^.*\(.\{128\}\)$/\1/p'` would also do the truncation (`rev| cut| rev` definitely looks nicer)

**Review by bvtujo — APPROVED** [review]
