### PR TITLE
fix: asg should work with --force for svc deploy

### LINKED ISSUE #3092: Deploy --force is not working when auto scaling set.
Hi,

We had set the location in manifest to pull from the static image url (with the latest tag), eg. repo.example/staging/helloworld:latest
While we use the manifest without auto scaling, copilot svc deploy --force it work perfectly.
After that we try to add auto scaling eg.
 
environments:
  staging:
    http:
      api : api.example.com
    count:
      range:
        min: 2
        max: 3
        spot_from: 2
      cpu_percentage: 50

copilot svc deploy --force will be deploy successfully at the first time, but the second time it wont recreate the tasks.

This is the old manifest.yml
environments:
  staging:
    http:
      api : api.example.com

Thanks for you assistance.

### PR DESCRIPTION
**Pull request by iamhopaul123**
fixes #3092

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the Apache 2.0 License.

### CODE REVIEW

File: internal/pkg/apprunner/apprunner.go [hunk 1]
```diff
@@ -55,6 +57,19 @@ func (c Client) ForceUpdateService(app, env, svc string) error {
 	return c.appRunnerClient.WaitForOperation(id, svcARN)
 }
 
+// LastUpdatedAt returns the last updated time of the app runner service.
+func (c Client) LastUpdatedAt(app, env, svc string) (*time.Time, error) {
```
Comment (efekarakus) [inline internal/pkg/apprunner/apprunner.go]: Can we return just `time.Time` (not a pointer)?

I tested this even if the service is not yet created, the `UpdatedAt` has a value that's equal to `CreatedAt`so it should be safe

File: internal/pkg/cli/svc_deploy.go [hunk 2]
```diff
@@ -74,41 +75,44 @@ type uploadCustomResourcesOpts struct {
...
+	targetApp           *config.Application
+	targetEnvironment   *config.Environment
+	targetSvc           *config.Workload
+	appliedManifest     interface{}
+	imageDigest         string
+	buildRequired       bool
+	appEnvResources     *stack.AppRegionalResources
+	rdSvcAlias          string
+	svcUpdater          serviceUpdater
+	svcLastUpdateGetter serviceLastUpdateGetter
```
Comment (efekarakus) [inline internal/pkg/cli/svc_deploy.go]: instead of creating a new field `svcLastUpdateGetter` what do you think of renaming the `serviceUpdater` interface to:
```go
type svcForceUpdater interface {
  ForceUpdateService(app, env, svc string) error
  LastUpdatedAt(app, env, svc string) (time.Time, error)
}
```

File: internal/pkg/cli/svc_deploy.go [hunk 3]
```diff
@@ -696,21 +709,33 @@ func (o *deploySvcOpts) deploySvc(addonsURL string) error {
 		return err
 	}
 
+	if o.cmdRunAt == nil {
+		o.cmdRunAt = aws.Time(time.Now())
+	}
```
Comment (efekarakus) [inline internal/pkg/cli/svc_deploy.go]: nit: another way I think of achieving this would be

```go
type deploySvcOpts struct {
   ...
   now   func() time.Time
}

func newSvcDeployOpts(vars deployWkldVars) (*deploySvcOpts, error) {
   opts.now = time.Now
}
```
and in the tests we can put a `fakeNow` function

File: internal/pkg/cli/svc_deploy.go [hunk 4]
```diff
@@ -696,21 +709,33 @@ func (o *deploySvcOpts) deploySvc(addonsURL string) error {
...
+		if !o.forceNewUpdate {
 			log.Warningf("Set --%s to force an update for the service.\n", forceFlag)
+			return fmt.Errorf("deploy service: %w", err)
+		}
+	}
+	// Force update the service if --force is set and the service is not updated by the CFN.
+	if o.forceNewUpdate {
+		lastUpdatedAt, err := o.svcLastUpdateGetter.LastUpdatedAt(o.appName, o.envName, o.name)
+		if err != nil {
+			return fmt.Errorf("get the last updated time for %s: %w", o.name, err)
```
Comment (efekarakus) [inline internal/pkg/cli/svc_deploy.go]:
```suggestion
			return fmt.Errorf("get the last updated deployment time for service %s: %w", o.name, err)
```

**Review by efekarakus — COMMENTED** [review]
Looks great, just one small suggestion

File: internal/pkg/apprunner/apprunner.go (hunk 1 above)
Comment (iamhopaul123) [reply internal/pkg/apprunner/apprunner.go]: I use the pointer because `time.Time{}` is a valid time so that we can't use `time.Time{}` to denote the field is empty (the same logic as `count`). In terms of safety as long as we use `aws.TimeValue()` I think we should be good? What do you think 🤔

Comment (efekarakus) [reply internal/pkg/apprunner/apprunner.go]: Yeah, it makes sense, I think my point was that at least for App Runner this value is always set so it can't ever be `nil`. If that's the case also with ECS we can get rid of an unnecessary condition. Otherwise, we can keep it as is

Comment (iamhopaul123) [reply internal/pkg/apprunner/apprunner.go]: nvm i think they are about the same since `time.Time{}` doesn't really happen

File: internal/pkg/cli/svc_deploy.go [hunk 5]
```diff
@@ -108,7 +109,8 @@ type deploySvcOpts struct {
 	buildRequired     bool
 	appEnvResources   *stack.AppRegionalResources
 	rdSvcAlias        string
-	svcUpdater        serviceUpdater
+	svcUpdater        svcForceUpdater
+	now               func() time.Time
```
Comment (efekarakus) [inline internal/pkg/cli/svc_deploy.go:113]: I think we need to update `init.go` and `deploy.go` as well with `now: time.Now`

File: internal/pkg/cli/svc_deploy.go [hunk 6]
```diff
@@ -148,8 +150,11 @@ func newSvcDeployOpts(vars deployWkldVars) (*deploySvcOpts, error) {
 		},
 		newInterpolator: newManifestInterpolator,
 		cmd:             exec.NewCmd(),
-		sessProvider:    sessions.NewProvider(),
-		snsTopicGetter:  deployStore,
+		now: func() time.Time {
+			return time.Now()
+		},
```
Comment (efekarakus) [inline internal/pkg/cli/svc_deploy.go]:
```suggestion
		now: time.Now,
```

**Review by efekarakus — APPROVED** [review]

File: internal/pkg/cli/svc_deploy.go (hunk 5 above)
Comment (iamhopaul123) [reply internal/pkg/cli/svc_deploy.go:113]: Oooh good call!

**Review by Lou1415926 — APPROVED** [review]
LGTM!
