### PR TITLE
fix(cli): --app flag can now be overridden by users

### LINKED ISSUE #1329: `--app` doesn't work for env commands
Global flag `--app` doesn't work for env commands (init, ls, show...). https://github.com/spf13/viper/issues/233#issuecomment-314890908 could be the reason, we need to have a better way to bind our global flags so that it won't get override.

### PR DESCRIPTION
**Pull request by efekarakus**
Resolves #1329

Removes GlobalOpts struct and the viper lib dependency from the CLI.

Previously, if we ran "env init --app other" the overridden value
"other" was ignored and only the workspace's app was used.
This is an issue with viper as was found in #1329. Instead, with this
change we get rid of Global Flags and force commands themselves to write
whether they need an --app flag or not.

_By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice._

### CODE REVIEW

File: internal/pkg/cli/cli.go [hunk 1]
```diff
@@ -12,62 +12,23 @@ import (
...
 	"github.com/aws/copilot-cli/internal/pkg/workspace"
 	"github.com/spf13/cobra"
-	"github.com/spf13/viper"
 )
 
-// GlobalOpts holds fields that are used across multiple commands.
-type GlobalOpts struct {
-	appName string
-	prompt  prompter
-}
```
Comment (SoManyHs) [inline internal/pkg/cli/cli.go:25]: Curious if it's possible to keep GlobalOpts and therefore maintain DRYness across all the command Opts but just get rid of the `bindAppName` logic?

Comment (efekarakus) [reply internal/pkg/cli/cli.go:25]: `GlobalOpts` itself is not great because it resulted in commands getting a `prompt` whether they needed it or not, and we had a bunch of commands that never used it :(

An alternative that doesn't force the re-declaration of the `--app` flag in these sub-commands that I can think of is this: https://gist.github.com/efekarakus/37144a1a4b8792508c39e9927a020243 

The benefit is that we don't have to remember to add the flag for all these sub-commands.
But, the downside is that I find this harder to understand as a reader than:
```
cmd.Flags().StringVarP(&vars.appName, appFlag, appFlagShort, tryReadingAppName(), appFlagDescription)
```
This makes it obvious if the `--app` flag is part of the command or not.

File: go.mod [hunk 2]
```diff
@@ -20,19 +20,15 @@ require (
...
-	github.com/pelletier/go-toml v1.8.0 // indirect
 	github.com/robfig/cron/v3 v3.0.1
 	github.com/sirupsen/logrus v1.6.0 // indirect
+	github.com/smartystreets/goconvey v1.6.4 // indirect
 	github.com/spf13/afero v1.3.5
-	github.com/spf13/cast v1.3.1 // indirect
 	github.com/spf13/cobra v1.0.0
-	github.com/spf13/jwalterweatherman v1.1.0 // indirect
 	github.com/spf13/pflag v1.0.5
-	github.com/spf13/viper v1.7.1
```
Comment (iamhopaul123) [inline go.mod:35]: 👋

**Review by iamhopaul123 — COMMENTED** [review]
Thank for the efforts for making this happen! It's such an annoying problem. A general question: have you run e2e test to make sure if they all work as expected?

**Comment by efekarakus** [comment]
> Thank for the efforts for making this happen! It's such an annoying problem. A general question: have you run e2e test to make sure if they all work as expected?

Yea after 2h44mins success :)

File: internal/pkg/cli/init.go [hunk 3]
```diff
@@ -209,12 +211,15 @@ func (o *initOpts) loadApp() error {
 	if err := o.initAppCmd.Validate(); err != nil {
 		return err
 	}
-	// Write the application name to viper so that sub-commands can retrieve its value.
-	viper.Set(appFlag, o.appName)
 	return nil
 }
 
 func (o *initOpts) loadSvc() error {
+	if initSvcOpts, ok := o.initSvcCmd.(*initSvcOpts); ok {
```
Comment (bvtujo) [inline internal/pkg/cli/init.go:218]: Is there a way to test this case?

**Review by bvtujo — APPROVED** [review]
Looks good, just a question about testing something in init.

**Review by iamhopaul123 — APPROVED** [review]
