### PR TITLE
fix: do not remove svc from app when running `svc delete --env`

### LINKED ISSUE #1126: Still have another AWS account environment, but copilot cli deletes ECR repository
### copilot cli version
`v0.1.0`

### Steps to Reproduce
```bash
$ copilot app init example-app
$ copilot svc init --name front-end --svc-type "Load Balanced Web Service" --dockerfile Dockerfile
$ copilot env init -n test --profile accountA-apn1-profile
$ copilot env init -n prod --profile accountB-apn1-profile
$ copilot svc deploy --name front-end --env test
$ copilot svc deploy --name front-end --env prod
$ copilot svc delete --name front-end --env test
```
`prod` environment ECS service still running, but `front-end` ECR repository deleted and `copilot svc show front-end` command failed.

### PR DESCRIPTION
**Pull request by kohidave**
Right now, when a customer runs `copilot svc delete --env e` copilot will delete the svc from the entire application, including the ECR repo and the SSM parameter.

The expected behavior is for copilot to only remove the service from the environment `e` - but for the service to still exist within the app. 

This change updates the service_delete code to skip removing the service from the application when the service is only being removed from one environment. 

This change might result in the service's app resources (ECR Repo, S3 Bucket, and KMS key) lingering around even if the service isn't deployed to any environment. Customers can always run `copilot svc delete` to clean up those resources. I'm hesitant to add any smarts into deleting those resources (like reference counting them) - just because I think it'll over complicate things.

fixes #1126, https://github.com/aws/copilot-cli/issues/1006

By submitting this pull request, I confirm that you can use, modify, 
copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

File: internal/pkg/cli/svc_delete.go [hunk 1]
```diff
@@ -137,17 +157,23 @@ func (o *deleteSvcOpts) Execute() error {
...
-	}
-	if err := o.removeSvcFromApp(); err != nil {
-		return err
-	}
-	if err := o.deleteSSMParam(); err != nil {
-		return err
+
+	// Only remove the app-level infrastructure if
+	// the service is being completely deleted.
+	if o.needsAppCleanup() {
```
Comment (efekarakus) [inline internal/pkg/cli/svc_delete.go:163]: can we flip the if-statement to reduce nesting?
```go
if !o.needsAppClean() {
     return nil
}
```

File: internal/pkg/cli/svc_delete_test.go [hunk 2]
```diff
@@ -329,6 +345,9 @@ func TestDeleteSvcOpts_Execute(t *testing.T) {
 			},
 			wantedError: nil,
 		},
+		// A servie can be deployed to multiple
```
Comment (efekarakus) [inline internal/pkg/cli/svc_delete_test.go:348]:
```suggestion
		// A service can be deployed to multiple
```

File: internal/pkg/cli/svc_delete_test.go [hunk 3]
```diff
@@ -341,17 +360,15 @@ func TestDeleteSvcOpts_Execute(t *testing.T) {
...
-					// emptyECRRepos
-					mocks.ecr.EXPECT().ClearRepository(mockRepo).Return(nil),
 
-					// removeSvcFromApp
-					mocks.store.EXPECT().GetApplication(mockAppName).Return(mockApp, nil),
-					mocks.spinner.EXPECT().Start(fmt.Sprintf(fmtSvcDeleteResourcesStart, mockSvcName, mockAppName)),
-					mocks.appCFN.EXPECT().RemoveServiceFromApp(mockApp, mockSvcName).Return(nil),
-					mocks.spinner.EXPECT().Stop(log.Ssuccessf(fmtSvcDeleteResourcesComplete, mockSvcName, mockAppName)),
+					// It should **not** emptyECRRepos
+					mocks.ecr.EXPECT().ClearRepository(mockRepo).Return(nil).Times(0),
```
Comment (efekarakus) [inline internal/pkg/cli/svc_delete_test.go:365]: nit: can we make the arguments `gomock.Any()` since we want to check that it's not called at all regardless of the inputs

File: internal/pkg/cli/svc_delete_test.go (hunk 2 above)
Comment (kohidave) [reply internal/pkg/cli/svc_delete_test.go:348]: You liked your own suggestion 👀

File: internal/pkg/cli/svc_delete_test.go (hunk 3 above)
Comment (kohidave) [reply internal/pkg/cli/svc_delete_test.go:365]: sure sure
