### PR TITLE
fix: respect network replacement configured through manifest

### LINKED ISSUE #3346: Environment overrides for `network` are overwriting base definitions.
I'm am seeing this with `network:`. I am not sure if this is happening with other maps.

In comparison, this isn't merging in the way that I would expect helm would merge: Maps/keys are merged at all levels. Values/arrays are overwritten.

Is everything getting overridden at the map of `network:`?

This doesn't place the task in the private subnet:
```yaml
network:
  vpc:
    placement: private

environments:
  dev:
    network:
      vpc:
        security_groups:
          - sg-1234567890
```

This does place the task in the private subnet:
```yaml
environments:
  dev:
    network:
      vpc:
        placement: private
        security_groups:
          - sg-1234567890
```

edit: Thanks!

### PR DESCRIPTION
**Pull request by Lou1415926**
This PR fixes #3346 by:
1. Remove the custom unmarshal logic of `network` field. The logic preset the network's placement value, which causes the bug that's seen in #3346.
2. Use `const` instead of `var` for placement types.
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the Apache 2.0 License.

### CODE REVIEW

File: internal/pkg/manifest/workload.go [hunk 1]
```diff
@@ -565,3 +544,11 @@ func uint16P(n uint16) *uint16 {
 	}
 	return &n
 }
+
```
Comment (iamhopaul123) [inline internal/pkg/manifest/workload.go:546]: comment pls

File: internal/pkg/manifest/workload.go [hunk 2]
```diff
@@ -23,14 +23,14 @@ const (
 )
 
 // AWS VPC subnet placement options.
```
Comment (iamhopaul123) [inline internal/pkg/manifest/workload.go]: maybe move this one below the const?

**Review by iamhopaul123 — APPROVED** [review]

File: internal/pkg/manifest/workload.go [hunk 3]
```diff
@@ -552,6 +531,15 @@ func DockerfileBuildRequired(svc interface{}) (bool, error) {
 	return required, nil
 }
 
+// PlacementP converts a string to a `Placement` type and returns its pointer.
+func PlacementP(p string) *Placement {
```
Comment (efekarakus) [inline internal/pkg/manifest/workload.go]: What do you think of instead the following approach:
```go
package manifest

// Placement represents VPC subnet placement.
type Placement string

const (
   PublicSubnetPlacement Placement    = "public"
   PrivateSubnetPlacement Placement = "private"
)
```

**Review by efekarakus — APPROVED** [review]
