### PR TITLE
fix(cli): use image digest instead of commit id when deploying 

### LINKED ISSUE #2139: Support deploying without creating a git commit
## Ask
Running `copilot deploy` should update my service using my local changes even if they're not yet committed.  

Related #1400 

## Current Behavior
When a user has changes that have not yet been committed and run `copilot deploy`, Copilot will:
1. Push to ECR a new image using the latest commit sha as the image tag. 
   > This can be misleading because the image tagged with a particular sha can now refer to code that's not actually part of that commit.
2. Trigger a service or job stack update
   > However, the stack update does not update the service because the image URL did not change. 

So although we pushed an image to ECR, the service update does not happen and leads to a confusing experience to users.
Our recommendation to mitigate this issue at the moment is to run `copilot deploy --tag <unique value>`. 

deploy

## Expected Behavior
1. The image tagged with the git commit sha should refer to the real commit and not to uncommitted code.
2. If an image gets pushed to ECR, the ECS service should be updated using the image.

## Proposed solution
We should refer to the image digest in our cloudformation templates instead of the tag. For example:
```
# Instead of:
111111111.dkr.ecr.us-west-2.amazonaws.com/demo/frontend:54fda35
# Use:
111111111.dkr.ecr.us-west-2.amazonaws.com/demo/frontend@sha256:1594f4a9be2c12c4aac3545d048ff772fe0f5ee03c0fb4f5525ba363b3e8b3a5
```

To do this, when running `copilot deploy`:
1. We shouldn't require an image tag anymore while pushing by default (so no git repo needed) :
https://github.com/aws/copilot-cli/blob/f8b02ab585c3c6fb2beb5c7558767c0979b8d7b2/internal/pkg/cli/git.go#L31-L37
2. Instead, if there is a commit and `git status --porcelain` returns no ouput then use the commit as a tag for the user's convenience. If not then leave it empty.
3. We can retrieve the digest after pushing by running:
```
$ docker inspect --format='{{json (index .RepoDigests 0)}}'  111111111.dkr.ecr.us-west-2.amazonaws.com/demo/frontend
"111111111.dkr.ecr.us-west-2.amazonaws.com/demo/frontend@sha256:1594f4a9be2c12c4aac3545d048ff772fe0f5ee03c0fb4f5525ba363b3e8b3a5"
```

### PR DESCRIPTION
**Pull request by efekarakus**
Fixes #2139

_By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice._

### CODE REVIEW

File: internal/pkg/deploy/cloudformation/stack/workload.go [hunk 1]
```diff
@@ -59,11 +59,21 @@ type RuntimeConfig struct {
 type ECRImage struct {
 	RepoURL  string // RepoURL is the ECR repository URL the container image should be pushed to.
 	ImageTag string // Tag is the container image's unique tag.
+	Digest   string // The image digest.
 }
 
-// GetLocation returns the location of the ECR image.
+// GetLocation returns the ECR image URI.
+// If a tag is provided for the image than prioritize refering to the image via the tag.
```
Comment (Lou1415926) [inline internal/pkg/deploy/cloudformation/stack/workload.go]: nit: 
```suggestion
// If a tag is provided for the image then prioritize refering to the image via the tag.
```

File: internal/pkg/cli/job_deploy.go [hunk 2]
```diff
@@ -113,11 +114,7 @@ func (o *deployJobOpts) Ask() error {
 	if err := o.askEnvName(); err != nil {
 		return err
 	}
-	tag, err := askImageTag(o.imageTag, o.prompt, o.cmd)
-	if err != nil {
-		return err
-	}
-	o.imageTag = tag
+	o.imageTag = imageTagFromGit(o.cmd, o.imageTag)
```
Comment (Lou1415926) [inline internal/pkg/cli/job_deploy.go]: Should this be moved to, for example, `Execute()` since we are no longer asking for it?

File: internal/pkg/cli/svc_package_test.go [hunk 3]
```diff
@@ -127,21 +130,73 @@ func TestPackageSvcOpts_Ask(t *testing.T) {
 		wantedTag     string
 		wantedErrorS  string
 	}{
-		"prompt for all options": {
+		"sets the image tag if not in a git repository": {
```
Comment (Lou1415926) [inline internal/pkg/cli/svc_package_test.go]:
```suggestion
		"leaves the image tag empty if not in a git repository": {
```

**Review by Lou1415926 — COMMENTED** [review]
The code LGTM!!

File: internal/pkg/deploy/cloudformation/stack/workload.go [hunk 4]
```diff
@@ -59,11 +59,21 @@ type RuntimeConfig struct {
...
+// If a digest is present then refer to the image via the digest.
+// Otherwise, use the "latest" tag.
```
Comment (iamhopaul123) [inline internal/pkg/deploy/cloudformation/stack/workload.go]: Maybe be more specific about it: currently the only use case is when doing `package` command with the default tag.

**Review by iamhopaul123 — APPROVED** [review]
+1 to wanxian's feedback otherwise looks good to me!

File: internal/pkg/deploy/cloudformation/stack/workload.go (hunk 1 above)
Comment (efekarakus) [reply internal/pkg/deploy/cloudformation/stack/workload.go]: Done!

File: internal/pkg/cli/job_deploy.go (hunk 2 above)
Comment (efekarakus) [reply internal/pkg/cli/job_deploy.go]: That makes sense! I've done this, I'll send a follow-up PR to move `git.go` inside the `exec` pkg. So that we have one package for running any commands, and increase our unit test coverage by moving it outside of the `cli` pkg.

**Review by Lou1415926 — APPROVED** [review]
Looks good!
