### PR TITLE
fix(manifest): preserve default values on environment overrides for jobs

### LINKED ISSUE #1736: copilot job environment
It looks like schedule is required when we have environments on the manifest.

We have to add
on:
    schedule
on the environments too.
example:
environments:
   test:
       on:
           schedule: "expersion"

if not added, it will generate an error schedule required.

### LINKED ISSUE #2043: Scheduled jobs - `manifest.yaml` - when specifying `environments` map, top-level `on.schedule` setting is nulled out
## Summary

**Scheduled jobs** `manifest.yaml` - when specifying `environments` map, top-level `on.schedule` setting is nulled out.

This isn't expected behaviour. [Documentation states](https://aws.github.io/copilot-cli/docs/manifest/scheduled-job/#environments) `environments` mapping is supported for jobs
as with any other service manifest.

## Problem

the following Scheduled Job fails when i add a matching environment in the environments map. manifest below.

```yaml
name: scheduled-job
type: Scheduled Job

on:
  schedule: "@hourly"

image:
  build: ./Dockerfile

environments:
  staging:
    variables:
      arbitrary-variable: arbitrary-value
```

```shell
copilot deploy \
  --app application \
  --env staging \
  --name scheduled-job

... builds container
... pushes layers

✘ Failed to deploy job.

✘ execute job deploy: deploy job: convert schedule for job scheduled-job: missing required field "schedule"
    in manifest for job scheduled-job
```

if i remove the environments map, it works fine.

## Workaround

If you specify `on.schedule` within the `environments` mapping, the job deploys without incident.

Example:

```yaml
name: scheduled-job
type: Scheduled Job
image:
  build: ./Dockerfile
environments:
  staging:
    on:
      schedule: "@hourly"
    variables:
      arbitrary-variable: arbitrary-value
```

the above deploys 👍

### PR DESCRIPTION
**Pull request by efekarakus**
Fixes #2043, fixes #1736

_By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice._

### CODE REVIEW

File: internal/pkg/manifest/job.go [hunk 1]
```diff
@@ -93,13 +93,24 @@ func newDefaultScheduledJob() *ScheduledJob {
...
+	}
+	if props.Schedule != "" {
+		job.On.Schedule = aws.String(props.Schedule)
+	}
+	if props.Retries != 0 {
+		job.Retries = aws.Int(props.Retries)
+	}
+	if props.Timeout != "" {
+		job.Timeout = aws.String(props.Timeout)
+	}
```
Comment (bvtujo) [inline internal/pkg/manifest/job.go:113]: o_O thank you so much for cleaning up this craziness

**Review by bvtujo — APPROVED** [review]

**Review by huanjani — APPROVED** [review]
