### PR TITLE
fix: remove newline from spinner.Stop() definition

### LINKED ISSUE #1591: env init execute shows duplicated log
Screen Shot 2020-10-29 at 12 44 44 PM

There are two `- Virtual private cloud on 2 availability zones to hold your services and jobs     [Complete]`

### PR DESCRIPTION
**Pull request by huanjani**
Previously, when the progress spinner stopped, a newline was appended. In `env init`, this was causing the event progress entries below the spinner to replace themselves one line down from where they had been, thereby duplicating the first line.

```
✔ Created the infrastructure for the env-two environment.
- Virtual private cloud on 2 availability zones to hold your services and jobs     [Complete]
- Virtual private cloud on 2 availability zones to hold your services and jobs     [Complete]
  - Internet gateway to connect the network to the internet                        [Complete]
  - Public subnets for internet facing services and jobs                           [Complete]
  - Private subnets for services and jobs that can't be reached from the internet  [Complete]
  - Routing tables for services and jobs to talk with each other                   [Complete]
- ECS Cluster to hold your services and jobs 
✔ Linked account 240594714208 and region us-west-2 to application video-store.

✔ Created environment env-two in region us-west-2 under application video-store.
```
Now, the expected behavior happens:
```
✔ Created the infrastructure for the env-two environment.
- Virtual private cloud on 2 availability zones to hold your services and jobs     [Complete]
  - Internet gateway to connect the network to the internet                        [Complete]
  - Public subnets for internet facing services and jobs                           [Complete]
  - Private subnets for services and jobs that can't be reached from the internet  [Complete]
  - Routing tables for services and jobs to talk with each other                   [Complete]
- ECS Cluster to hold your services and jobs                                       [Complete]
✔ Linked account 240594714208 and region us-west-2 to application video-store.
✔ Created environment env-two in region us-west-2 under application video-store.
```
In order to maintain the desired newlines in other commands' output, I added newlines to each of those instances.

Fixes https://github.com/aws/copilot-cli/issues/1591

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

File: internal/pkg/cli/env_delete_test.go [hunk 1]
```diff
@@ -264,7 +264,7 @@ func TestDeleteEnvOpts_Execute(t *testing.T) {
     DeletionPolicy: Retain`, nil)
 				deployer.EXPECT().DeleteEnvironment(gomock.Any(), gomock.Any(), gomock.Any()).Return(errors.New("some error"))
 
-				prog.EXPECT().Stop(log.Serror("Failed to delete environment test from application phonetool."))
+				prog.EXPECT().Stop(log.Serror("Failed to delete environment test from application phonetool.\n"))
```
Comment (iamhopaul123) [inline internal/pkg/cli/env_delete_test.go:267]: can we make it consistent for using `Serror` and `Serrorln`?

**Review by iamhopaul123 — APPROVED** [review]
LGTM thank you for making this change!

File: internal/pkg/cli/env_delete_test.go (hunk 1 above)
Comment (huanjani) [reply internal/pkg/cli/env_delete_test.go:267]: For `env_delete`, I used `\n` in the string consts because I can't do `ln` with `f` and those use `Serrorf` and `Ssuccessf`. So for this one, it's `fmtDeleteEnvFailed   = "Failed to delete environment %s from application %s.\n"`

File: internal/pkg/cli/svc_delete.go [hunk 2]
```diff
@@ -36,10 +36,10 @@ const (
 
 const (
 	fmtSvcDeleteStart             = "Deleting service %s from environment %s."
-	fmtSvcDeleteFailed            = "Failed to delete service %s from environment %s: %v."
-	fmtSvcDeleteComplete          = "Deleted service %s from environment %s."
-	fmtSvcDeleteResourcesStart    = "Deleting resources of service %s from application %s."
-	fmtSvcDeleteResourcesComplete = "Deleted resources of service %s from application %s."
+	fmtSvcDeleteFailed            = "Failed to delete service %s from environment %s: %v.\n"
+	fmtSvcDeleteComplete          = "Deleted service %s from environment %s.\n"
+	fmtSvcDeleteResourcesStart    = "Deleting resources of service %s from application %s.\n"
```
Comment (efekarakus) [inline internal/pkg/cli/svc_delete.go:41]: Should we remove the new line from this start?

Comment (huanjani) [reply internal/pkg/cli/svc_delete.go:41]: That's the one that's currently being used with a Stop. I am going to make a SvcDeleteResourcesFailed (and the equivalent for `job_delete`) in a separate PR and will adjust newlines accordingly.

**Review by efekarakus — APPROVED** [review]
