### PR TITLE
fix: support amazon-ecr-credential-helper & check for bucket existence before emptying the bucket

### LINKED ISSUE #2323: copilot deploy throws error if ECR credential helper is enabled in Docker config
If Docker is configured to use the ECR Credential Helper, any attempt to deploy will result in the following error being thrown:

```
Error saving credentials: error storing credentials - err: exit status 1, out: `not implemented`
```

Helper version: 0.5.0
Copilot version: 1.6.0

This is a little inconvenient because it means I have to edit my Docker `config.json` file merely to disable the helper when I'm using Copilot.

### PR DESCRIPTION
**Pull request by hariohmprasath**
### Summary

#2323 - Depending on the value of `credsStore` attribute (inside docker config file), the code either performs the `docker login` or skips it.
#2070 - Added code to check for the existence of the bucket using `s3.HeadBucket` API before proceed to empty the contents

### Issue number
Fixes  #2323 & #2070

----
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

File: internal/pkg/exec/docker.go [hunk 1]
```diff
@@ -159,3 +161,38 @@ func imageName(uri, tag string) string {
 	}
 	return fmt.Sprintf("%s:%s", uri, tag)
 }
+
+// GetHelperProviderFromDockerCfg will fetch credential store used by docker from config file
+func (c DockerCommand) GetHelperProviderFromDockerCfg() (string) {
```
Comment (iamhopaul123) [inline internal/pkg/exec/docker.go]: Quick question: does this function work for windows? Since we support windows maybe we don't want this function to break Windows users.

File: internal/pkg/exec/docker.go [hunk 2]
```diff
@@ -159,3 +161,38 @@ func imageName(uri, tag string) string {
 	}
 	return fmt.Sprintf("%s:%s", uri, tag)
 }
+
+// GetHelperProviderFromDockerCfg will fetch credential store used by docker from config file
```
Comment (iamhopaul123) [inline internal/pkg/exec/docker.go]:
```suggestion
// GetHelperProviderFromDockerCfg tries to fetch credential store used by docker from config file.
```

File: internal/pkg/exec/docker.go [hunk 3]
```diff
@@ -159,3 +161,38 @@ func imageName(uri, tag string) string {
...
+			continue
+		}
+		if provider != "" {
+			return provider
+		}
+	}
+	return ""
+}
+
+// parseCredFromDockerConfig will unmarshal string to struct
```
Comment (iamhopaul123) [inline internal/pkg/exec/docker.go]: Maybe we don't need this comment for private function since it doesn't add a lot of value.

File: internal/pkg/repository/repository.go [hunk 4]
```diff
@@ -54,13 +55,19 @@ func (r *Repository) BuildAndPush(docker ContainerLoginBuildPusher, args *exec.B
...
 	}
 
-	username, password, err := r.registry.Auth()
-	if err != nil {
-		return "", fmt.Errorf("get auth: %w", err)
-	}
+	// Check for usage of amazon-ecr-credential-helper before performing docker login
+	credStore := docker.GetHelperProviderFromDockerCfg()
+
+	// Perform docker login only if credStore not
```
Comment (iamhopaul123) [inline internal/pkg/repository/repository.go]: Is this comment incomplete?

**Review by iamhopaul123 — COMMENTED** [review]
Thank you so much for making this change! This is awesome! Just had some nits and a quick question.

File: internal/pkg/exec/docker.go (hunk 1 above)
Comment (efekarakus) [reply internal/pkg/exec/docker.go]: nit: 
```suggestion
func (c DockerCommand) GetHelperProviderFromDockerCfg() string {
```

File: internal/pkg/exec/docker.go [hunk 5]
```diff
@@ -159,3 +161,38 @@ func imageName(uri, tag string) string {
 	}
 	return fmt.Sprintf("%s:%s", uri, tag)
 }
+
+// GetHelperProviderFromDockerCfg will fetch credential store used by docker from config file
+func (c DockerCommand) GetHelperProviderFromDockerCfg() (string) {
+	// Look into the default locations
+	pathsToTry := []string{"/.docker/config.json", ".dockercfg"}
+	for _, path := range pathsToTry {
+		content, err := ioutil.ReadFile(fmt.Sprintf("%s/%s",os.Getenv("HOME"), path))
```
Comment (efekarakus) [inline internal/pkg/exec/docker.go]: Will this result in a double "//" such as "<homepath>//.docker/config.json"?
```suggestion
	pathsToTry := []string{filepath.Join(".docker, config.json"), ".dockercfg"}
	for _, path := range pathsToTry {
		content, err := ioutil.ReadFile(filepath.Join(os.Getenv("HOME"), path))
```

Comment (efekarakus) [inline internal/pkg/exec/docker.go]: What do you think of storing the environment variable in the `DockerCommand` type to allow writing unit tests for this new method:
```go
// DockerCommand represents docker commands that can be run.
type DockerCommand struct {
	runner
	// Override in unit tests.
	homePath string // new field that can be substituted in tests
	buf *bytes.Buffer
}

// NewDockerCommand returns a DockerCommand.
func NewDockerCommand() DockerCommand {
	return DockerCommand{
		runner: NewCmd(),
		homePath: os.Getenv("HOME"),
	}
}
```

(for an example of unit tests with fake file systems, we use `afero.NewMemMapFs()`: https://github.com/aws/copilot-cli/blob/c2d143dfe781a865ed823984c88065a92836b4c6/internal/pkg/workspace/workspace_test.go#L123-L126)

File: internal/pkg/repository/repository.go [hunk 6]
```diff
@@ -54,13 +55,19 @@ func (r *Repository) BuildAndPush(docker ContainerLoginBuildPusher, args *exec.B
...
+	if credStore != "ecr-login"{
```
Comment (efekarakus) [inline internal/pkg/repository/repository.go]: can we move "ecr-login" to a const?
```go
const (
   credStoreECRLogin = "ecr-login"
)
```

**Review by efekarakus — COMMENTED** [review]
Awesome, this is so good thank you so much for fixing this issue 😍 !   
Some suggestions for enabling writing unit tests for the new functionality 🙏

File: internal/pkg/exec/docker.go (hunk 3 above)
Comment (hariohmprasath) [reply internal/pkg/exec/docker.go]: Removed

File: internal/pkg/repository/repository.go (hunk 4 above)
Comment (hariohmprasath) [reply internal/pkg/repository/repository.go]: Updated comments

File: internal/pkg/exec/docker.go (hunk 5 above)
Comment (hariohmprasath) [reply internal/pkg/exec/docker.go]: Makes sense and thanks for the suggestion. I have added additional test cases to unit test this method

File: internal/pkg/repository/repository.go (hunk 6 above)
Comment (hariohmprasath) [reply internal/pkg/repository/repository.go]: Done

File: internal/pkg/exec/docker.go [hunk 7]
```diff
@@ -159,3 +172,51 @@ func imageName(uri, tag string) string {
...
+		return nil, err
+	}
+
+	return &cred, nil
+}
+
+func userHomeDirectory() string {
+	home, err := os.UserHomeDir()
+	if err!= nil{
+		println("authenticate to ECR: %w", err)
```
Comment (iamhopaul123) [inline internal/pkg/exec/docker.go]: Can we remove this line? We don't log outside of the `cli` pkg. Or you might want to define a new error and catch that in the `cli` pkg.

File: internal/pkg/exec/docker.go [hunk 8]
```diff
@@ -159,3 +172,51 @@ func imageName(uri, tag string) string {
 	}
 	return fmt.Sprintf("%s:%s", uri, tag)
 }
+
+// IsEcrCredentialHelperEnabled return true if ecr-login is enabled either globally or registry level
+func (c DockerCommand) IsEcrCredentialHelperEnabled(uri string) bool {
+	// Make sure the program is able to obtain the home directory
+	splits := strings.Split(uri, "/")
+	if c.homePath != "" && len(splits) > 0 {
```
Comment (iamhopaul123) [inline internal/pkg/exec/docker.go]: Hmm why not just 
```suggestion
	homePath := userHomeDirectory()
	if homePath != "" && len(splits) > 0 {
```
I don't see `homePath` being used in the other places.

File: internal/pkg/exec/docker.go [hunk 9]
```diff
@@ -159,3 +172,51 @@ func imageName(uri, tag string) string {
...
+			if config.CredsStore == CredStoreECRLogin || config.CredHelpers[splits[0]] == CredStoreECRLogin {
+				return true
+			}
+		}
+	}
+
+	return false
+}
+
+func parseCredFromDockerConfig(config []byte) (*dockerConfig, error) {
```
Comment (iamhopaul123) [inline internal/pkg/exec/docker.go:206]: Would you mind to give an example of the config file that we are able to parse in the comment of this function?

File: internal/pkg/exec/docker.go (hunk 7 above)
Comment (hariohmprasath) [reply internal/pkg/exec/docker.go]: Removed

File: internal/pkg/exec/docker.go (hunk 8 above)
Comment (hariohmprasath) [reply internal/pkg/exec/docker.go]: Its done to enable unit testing, so part of unit test code we can control this path, like below:

```go
s := DockerCommand{
  runner: mockRunner,
  buf:    tc.inBuffer,
  homePath: "test/copilot",
}
```

File: internal/pkg/exec/docker.go (hunk 9 above)
Comment (hariohmprasath) [reply internal/pkg/exec/docker.go:206]: Added a sample json

File: internal/pkg/exec/docker.go [hunk 10]
```diff
@@ -39,6 +43,15 @@ type BuildArguments struct {
 	Args       map[string]string // Optional. Build args to pass via `--build-arg` flags. Equivalent to ARG directives in dockerfile.
 }
 
+type dockerConfig struct {
+	CredsStore  string            `json:"credsStore,omitempty"`
+	CredHelpers map[string]string `json:"credHelpers,omitempty"`
+}
+
+const(
+	CredStoreECRLogin = "ecr-login" // set on `credStore` attribute in docker configuration file
```
Comment (iamhopaul123) [inline internal/pkg/exec/docker.go]:
```suggestion
	credStoreECRLogin = "ecr-login" // set on `credStore` attribute in docker configuration file
```
Maybe we don't need to make it public

File: internal/pkg/exec/docker.go [hunk 11]
```diff
@@ -159,3 +172,57 @@ func imageName(uri, tag string) string {
...
+	return false
+}
+
+func parseCredFromDockerConfig(config []byte) (*dockerConfig, error) {
+	/*
+	Sample docker config file
+	"credsStore" : "ecr-login",
+	  "credHelpers": {
+	        "dummyaccountId.dkr.ecr.region.amazonaws.com": "ecr-login"
+	  },
```
Comment (iamhopaul123) [inline internal/pkg/exec/docker.go]:
```suggestion
    {
        "credsStore" : "ecr-login",
        "credHelpers": {
            "dummyaccountId.dkr.ecr.region.amazonaws.com": "ecr-login"
        }
    }
```
Could you make this json file aligned?

**Review by iamhopaul123 — APPROVED** [review]
Just some nits. Other than that lgtm!

**Comment by hariohmprasath** [comment]
> Just some nits. Other than that lgtm!

Thanks I have accepted the suggestions, appreciate the support on this.

File: internal/pkg/exec/docker.go [hunk 12]
```diff
@@ -159,3 +172,59 @@ func imageName(uri, tag string) string {
...
+				// if we can't read the file keep going
+				continue
+			}
+
+			config, err := parseCredFromDockerConfig(content)
+			if err != nil {
+				continue
+			}
+
+			if config.CredsStore == CredStoreECRLogin || config.CredHelpers[splits[0]] == CredStoreECRLogin {
```
Comment (iamhopaul123) [inline internal/pkg/exec/docker.go]: could you update the variable here?

Comment (hariohmprasath) [reply internal/pkg/exec/docker.go]: I just noticed the same const is used in unit test case as well. So I have updated it back to Capitol letter so it can be get used in both the places

Comment (iamhopaul123) [reply internal/pkg/exec/docker.go]: Yeah but still they are in the same package right?

Comment (hariohmprasath) [reply internal/pkg/exec/docker.go]: You are right, been a long day I guess :) Sorry about the back and forth, its fixed now.

File: internal/pkg/aws/s3/s3.go [hunk 13]
```diff
@@ -105,48 +108,59 @@ func (s *S3) ZipAndUpload(bucket, key string, files ...NamedBinary) (string, err
...
-				Key:       deleteMarker.Key,
-				VersionId: deleteMarker.VersionId,
-			})
-		}
-		if len(objectsToDelete) == 0 {
-			return nil
-		}
-		_, err = s.s3Client.DeleteObjects(&s3.DeleteObjectsInput{
+
+	if isExists {
```
Comment (efekarakus) [inline internal/pkg/aws/s3/s3.go]: Can we flip the if-condition here so that the main logic is not nested?

```go
if !isExists {
    return nil
}
...
```

File: internal/pkg/aws/s3/s3.go [hunk 14]
```diff
@@ -161,3 +175,24 @@ func ParseURL(url string) (bucket string, key string, err error) {
...
+	if err != nil {
+		if aerr, ok := err.(awserr.Error); ok {
+			switch aerr.Code() {
+				case notFound:
+					return false, nil
+				default:
+					return false, aerr
+			}
+		}
+		return false, err
```
Comment (efekarakus) [inline internal/pkg/aws/s3/s3.go]: nit: I believe these two statements return the same error, maybe we can simplify it like this:
```go
if aerr, ok := err.(awserr.Error); ok && aerr.Code() == notFound {
     return false, nil
}
return false, err
```

File: internal/pkg/exec/docker.go [hunk 15]
```diff
@@ -159,3 +172,59 @@ func imageName(uri, tag string) string {
 	}
 	return fmt.Sprintf("%s:%s", uri, tag)
 }
+
+// IsEcrCredentialHelperEnabled return true if ecr-login is enabled either globally or registry level
+func (c DockerCommand) IsEcrCredentialHelperEnabled(uri string) bool {
+	// Make sure the program is able to obtain the home directory
+	splits := strings.Split(uri, "/")
+	if c.homePath != "" && len(splits) > 0 {
```
Comment (efekarakus) [inline internal/pkg/exec/docker.go]: nit: can we flip this if statement to reduce nesting
```go
if c.homePath == "" || len(splits) == 0 {
     return false
}
```

**Review by efekarakus — APPROVED** [review]
Looks great thank you so much! And I'm sorry for the delay on the review 🙇 

Just small requests to flip the if-statement to reduce nesting and then the PR should auto-merge once we remove the label.

File: internal/pkg/aws/s3/s3.go (hunk 13 above)
Comment (hariohmprasath) [reply internal/pkg/aws/s3/s3.go]: Done

File: internal/pkg/aws/s3/s3.go (hunk 14 above)
Comment (hariohmprasath) [reply internal/pkg/aws/s3/s3.go]: Done

File: internal/pkg/exec/docker.go (hunk 15 above)
Comment (hariohmprasath) [reply internal/pkg/exec/docker.go]: Done
