### PR TITLE
fix(windows): improve ux for env init execute workflow

### LINKED ISSUE #1464: Windows user experience for env init
Running init in Windows leads to 2 usability issues

First is the guided prompts fail for user input and forces a user to use paramaters
image

Using init with parameters create the application but updates are in every newline
image

### PR DESCRIPTION
**Pull request by iamhopaul123**
fixes #1464

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by iamhopaul123** [comment]
new windows execute experience for windows terminal:

image

File: internal/pkg/cli/env_init.go [hunk 1]
```diff
@@ -626,6 +628,8 @@ func buildEnvInitCmd() *cobra.Command {
 				return err
 			}
 			return opts.Execute()
+			// test()
+			// return nil
```
Comment (efekarakus) [inline internal/pkg/cli/env_init.go]: :D can we delete these

File: internal/pkg/cli/env_init.go [hunk 2]
```diff
@@ -56,6 +56,7 @@ https://aws.github.io/copilot-cli/docs/credentials/#environment-credentials`
 	envInitDefaultRegionOption = "us-west-2"
 
 	fmtDeployEnvStart        = "Proposing infrastructure changes for the %s environment."
+	fmtDeployEnvSuccess      = "Proposed infrastructure changes for the %s environment."
```
Comment (efekarakus) [inline internal/pkg/cli/env_init.go]: Why did we add this? I think it was intentional so that the line:
`"Proposing infrastructure changes for the %s environment."`  gets overriden and becomes:
`"Creating the infrastructure for the %s environment."`

File: internal/pkg/term/progress/spinner_windows.go [hunk 3]
```diff
@@ -0,0 +1,142 @@
...
+	s.spin.Stop()
+	// Reset event entries once the spinner stops.
+	s.pastEvents = nil
+}
+
+// Events writes additional information below the spinner while the spinner is still in progress.
+// If there are already existing events under the spinner, it replaces them with the new information.
+//
+// An event is displayed in a table, where columns are separated with the '\t' character.
+func (s *Spinner) Events(events []TabRow) {
```
Comment (efekarakus) [inline internal/pkg/term/progress/spinner_windows.go:88]: Instead of duplicating the entire spinner files, what do you think of having two files:
`events.go` and `events_windows.go` where only the `(s *Spinner) Events(events []TabRow)` method is in these files, since that's the only method that's overriden for windows.

This way it'd be easier to compare the differences.

File: internal/pkg/term/progress/spinner_windows.go [hunk 4]
```diff
@@ -0,0 +1,142 @@
...
+	done := make(chan struct{})
+	go func() {
+		s.lock()
+		defer s.unlock()
+		// Erase previous entries, and move the cursor back to the spinner.
```
Comment (efekarakus) [inline internal/pkg/term/progress/spinner_windows.go:93]: nit: can we update the comments to match for what windows does

**Review by efekarakus — COMMENTED** [review]
😍 awesome, I can't believe this is fixed!

File: internal/pkg/cli/env_init.go (hunk 2 above)
Comment (iamhopaul123) [reply internal/pkg/cli/env_init.go]: Because on Windows the workflow is not like this: `"Creating the infrastructure for the %s environment."` is at the bottom instead of above those progress info. And `"Proposing infrastructure changes for the %s environment."` will just disappear and leave it to be an empty line. But I'm ok if we want to remove it.

File: internal/pkg/term/progress/spinner_windows.go (hunk 3 above)
Comment (iamhopaul123) [reply internal/pkg/term/progress/spinner_windows.go:88]: sounds good!

File: internal/pkg/term/progress/spinner_windows.go (hunk 4 above)
Comment (iamhopaul123) [reply internal/pkg/term/progress/spinner_windows.go:93]: this is the same :P

File: internal/pkg/term/progress/spinner_windows.go (hunk 3 above)
Comment (iamhopaul123) [reply internal/pkg/term/progress/spinner_windows.go:88]: oh i also modified `Stop` method.

File: internal/pkg/term/progress/spinner_windows.go [hunk 5]
```diff
@@ -0,0 +1,142 @@
...
+	spin startStopper
+	cur  mover
+
+	pastEvents   []TabRow     // Already written entries.
+	eventsWriter writeFlusher // Writer to pretty format events in a table.
+}
+
+// NewSpinner returns a spinner that outputs to stderr.
+func NewSpinner() *Spinner {
+	s := spinner.New(charset, 500*time.Millisecond, spinner.WithHiddenCursor(true))
```
Comment (iamhopaul123) [inline internal/pkg/term/progress/spinner_windows.go:61]: modified the refresh rate.

File: internal/pkg/term/progress/spinner_windows.go [hunk 6]
```diff
@@ -0,0 +1,142 @@
...
+func (s *Spinner) Start(label string) {
+	s.suffix(fmt.Sprintf(" %s", label))
+	s.spin.Start()
+}
+
+// Stop stops the spinner and replaces it with a label.
+func (s *Spinner) Stop(label string) {
+	s.finalMSG(fmt.Sprintln(label))
+	s.spin.Stop()
+	// Reset event entries once the spinner stops.
```
Comment (iamhopaul123) [inline internal/pkg/term/progress/spinner_windows.go:80]: get rid of the print previous events

File: internal/pkg/term/progress/spinner_windows.go [hunk 7]
```diff
@@ -0,0 +1,142 @@
...
+		defer s.unlock()
+		// Erase previous entries, and move the cursor back to the spinner.
+		for i := 0; i < len(s.pastEvents); i++ {
+			s.cur.Down(1)
+			s.cur.EraseLine()
+		}
+
+		// Add new status updates, and move cursor back to the spinner.
+		for _, event := range events {
+			fmt.Fprintf(s.eventsWriter, "\r%s\n", event)
```
Comment (iamhopaul123) [inline internal/pkg/term/progress/spinner_windows.go:101]: modified here

File: internal/pkg/term/progress/spinner_windows.go [hunk 8]
```diff
@@ -0,0 +1,142 @@
...
+	done := make(chan struct{})
+	go func() {
+		s.lock()
+		defer s.unlock()
+		// Erase previous entries, and move the cursor back to the spinner.
+		for i := 0; i < len(s.pastEvents); i++ {
+			s.cur.Down(1)
+			s.cur.EraseLine()
+		}
+
```
Comment (iamhopaul123) [inline internal/pkg/term/progress/spinner_windows.go:98]: modified here

**Review by efekarakus — APPROVED** [review]

**Review by huanjani — APPROVED** [review]
Woohoo!
