### PR TITLE
fix(cli): command with env/svc flag should work without app flag

### LINKED ISSUE #2776: Error when running copilot env show when app name contains a hyphen
Tested with copilot v1.9.0.

I created an app named `migration-demo` and an environment named `test`. When I run `copilot env show --name test`, I see the following error:

```
✘ get environment test in application : ValidationException: Parameter name: can't be prefixed with "ssm" (case-insensitive). If formed as a path, it can consist of sub-paths divided by slash symbol; each sub-path can be formed as a mix of letters, numbers and the following 3 symbols .-_
        status code: 400, request id: d6454b99-8806-40fb-a9cb-d61be1aa2fb0
```

When I run `copilot env show`, it works and returns the details of the environment.

```
(.env) adam:~ $ copilot env show
Only found one application, defaulting to: migration-demo
Only found one environment, defaulting to: test
About

  Name              test
  Production        false
  Region            us-west-2
  Account ID        123456789

Services

  Name              Type
  ----              ----

Tags

  Key                  Value
  ---                  -----
  copilot-application  migration-demo
  copilot-environment  test
```

### PR DESCRIPTION
**Pull request by iamhopaul123**
fixes #2776 

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

File: internal/pkg/cli/job_logs.go [hunk 1]
```diff
@@ -78,8 +78,10 @@ func newJobLogOpts(vars jobLogsVars) (*jobLogsOpts, error) {
...
 func (o *jobLogsOpts) Validate() error {
 	if o.appName != "" {
-		_, err := o.configStore.GetApplication(o.appName)
-		if err != nil {
+		if _, err := o.configStore.GetApplication(o.appName); err != nil {
+			return err
+		}
+		if _, err := o.configStore.GetJob(o.appName, o.name); err != nil {
 			return err
 		}
```
Comment (efekarakus) [inline internal/pkg/cli/job_logs.go]: Is `o.name` always set here?

File: internal/pkg/cli/svc_resume.go [hunk 2]
```diff
@@ -53,15 +53,15 @@ func (o *resumeSvcOpts) Validate() error {
 		if err := o.validateAppName(); err != nil {
 			return err
 		}
-	}
-	if o.envName != "" {
-		if err := o.validateEnvName(); err != nil {
-			return err
+		if o.envName != "" {
```
Comment (efekarakus) [inline internal/pkg/cli/svc_resume.go]: I just wanted to make sure that all this changes will indeed result in an error right in case the user does something like this `copilot svc resume -e invalid-env`.

As long as the `Execute` or `Ask` logic ends up returning errors after these changes then I'm fine with it!

File: internal/pkg/cli/svc_status.go [hunk 3]
```diff
@@ -92,15 +92,15 @@ func (o *svcStatusOpts) Validate() error {
 		if _, err := o.store.GetApplication(o.appName); err != nil {
 			return err
 		}
-	}
-	if o.svcName != "" {
-		if _, err := o.store.GetService(o.appName, o.svcName); err != nil {
-			return err
+		if o.envName != "" {
```
Comment (efekarakus) [inline internal/pkg/cli/svc_status.go]: nit: we should consider flipping the if-statement in most of these methods to:
```go
if o.appName == "" { return nil }
```

**Review by efekarakus — COMMENTED** [review]
Looks good! just some questions

File: internal/pkg/cli/job_logs.go (hunk 1 above)
Comment (iamhopaul123) [reply internal/pkg/cli/job_logs.go]: darn good call

File: internal/pkg/cli/svc_resume.go (hunk 2 above)
Comment (iamhopaul123) [reply internal/pkg/cli/svc_resume.go]: Yeah they will error out in selector I think.
```
✘ select deployed services for application demo: list deployed service for environment ts: get environment config ts: couldn't find environment ts in the application demo
```

File: internal/pkg/cli/svc_status.go (hunk 3 above)
Comment (iamhopaul123) [reply internal/pkg/cli/svc_status.go]: ok done!

**Review by efekarakus — APPROVED** [review]

**Comment by huanjani** [comment]
This fixes #2776, not #2777, right?

File: internal/pkg/cli/svc_resume.go (hunk 2 above)
Comment (huanjani) [reply internal/pkg/cli/svc_resume.go]: Hm. Doesn't `AskEnvName()` return nil if the `o.name` is set? 
Can we add the validation to `AskEnvName()` for each command?  It seems a little odd to prompt with the selector if `-n` was set at the beginning....

File: internal/pkg/cli/job_logs.go [hunk 4]
```diff
@@ -78,10 +78,14 @@ func newJobLogOpts(vars jobLogsVars) (*jobLogsOpts, error) {
 // Validate returns an error if the values provided by flags are invalid.
 func (o *jobLogsOpts) Validate() error {
 	if o.appName != "" {
-		_, err := o.configStore.GetApplication(o.appName)
-		if err != nil {
+		if _, err := o.configStore.GetApplication(o.appName); err != nil {
```
Comment (Lou1415926) [inline internal/pkg/cli/job_logs.go:81]: Do we also need to validate `envName` flag then? `appName` and `envName` are used in `initLogsSvc` which are called by `svc logs` from within `Execute()`

File: internal/pkg/cli/secret_init.go [hunk 5]
```diff
@@ -148,6 +148,13 @@ func (o *secretInitOpts) Validate() error {
 		if err != nil {
 			return fmt.Errorf("get application %s: %w", o.appName, err)
 		}
+		if o.values != nil {
```
Comment (Lou1415926) [inline internal/pkg/cli/secret_init.go:151]: :woman-facepalming:

Comment (Lou1415926) [reply internal/pkg/cli/secret_init.go:151]: What do you think we leave this chunk at its original place and modify `o.targetEnv` instead?
```go
func (o *secretInitOpts) targetEnv(envName string) (*config.Environment, error) {
        if o.appName == "" {
                return nil, nil
        }
 	env, err := o.store.GetEnvironment(o.appName, envName)
	if err != nil {
		return nil, fmt.Errorf("get environment %s in application %s: %w", envName, o.appName, err)
	}
	return env, nil
}
```

**Review by Lou1415926 — COMMENTED** [review]
LGTM! One small suggestion / question ⬇️

**Comment by iamhopaul123** [comment]
> This fixes #2776, not #2777, right?

true true. Thank you!

File: internal/pkg/cli/secret_init.go (hunk 5 above)
Comment (iamhopaul123) [reply internal/pkg/cli/secret_init.go:151]: Umm I think it still prefer handling it in the validate, since it would make more sense when reading `validate`

**Review by Lou1415926 — APPROVED** [review]
