### PR TITLE
fix(cli)!: use default creds when deploying "test" env with "copilot init"

### LINKED ISSUE #1068: Copilot env command doesn't inspect environment variables
For AWS Control Tower accounts where access is governed by temporary credentials:

``` bash
export AWS_ACCESS_KEY_ID="<redacted>"
export AWS_SECRET_ACCESS_KEY="<redacted>"
export AWS_SESSION_TOKEN="<redacted>"
```

The command copilot init works fine

```bash
copilot init
```

But once you try to provision infrastructure with `copilot env init`, the CLI wants credentials from .aws/ and not the environment variables mentioned above, causing the command to fail.

This can be easily fixed on the user end by manually writing temp creds to ~/.aws/credentials.

### PR DESCRIPTION
**Pull request by efekarakus**
Removes the --profile flag from the "init" command as
it's most likely not used + this change is the expected behavior from
customers.

Fixes #1068 #1104

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

File: internal/pkg/cli/init.go [hunk 1]
```diff
@@ -126,8 +130,13 @@ func newInitOpts(vars initVars) (*initOpts, error) {
 		initEnvVars: initEnvVars{
 			GlobalOpts:   NewGlobalOpts(),
 			Name:         defaultEnvironmentName,
-			Profile:      vars.profile,
 			IsProduction: false,
+
+			TempCreds: tempCredsVars{
```
Comment (iamhopaul123) [inline internal/pkg/cli/init.go:135]: Are this temp cred only configurable via `copilot init`? (Can users specify them using flags when doing `env init`?)

Comment (efekarakus) [reply internal/pkg/cli/init.go:135]: Jes, next PR will add the flags so that users can configure them via flags in `env init`.
