### PR TITLE
fix: redirect AppRunner services on ARM architectures to AMD

### LINKED ISSUE #2640: bug: Creating app runner services from ARM machines
Hi, 

I'm following through the basic first app https://aws.github.io/copilot-cli/docs/getting-started/first-app-tutorial/. Everything goes along smoothly, but the ECS Service won't deploy. I receive this message: 

 Resource handler returned message: "Error occurred during operation `ECS Deployment Circuit Breaker was triggered'." (RequestToken: XXXXXXXXXXX, HandlerErrorCode: GeneralServiceException)`        

Would anyone know where I can review deployment logs? I checked on both `copilot svc logs` and on AWS CloudWatch.

Here's a full log output
```Proposing infrastructure changes for the example-app-test environment. 
- Creating the infrastructure for the example-app-test environment.      [create complete]  [81.7s]
  - An IAM Role for AWS CloudFormation to manage resources               [create complete]  [24.6s]
  - An ECS cluster to group your services                                [create complete]  [6.4s]
  - Enable long ARN formats for the authenticated AWS principal          [create complete]  [0.0s]
  - An IAM Role to describe resources in your environment                [create complete]  [24.4s]
  - A security group to allow your containers to talk to each other      [create complete]  [5.7s]
  - An Internet Gateway to connect to the public internet                [create complete]  [13.9s]
  - Private subnet 1 for resources with no internet access               [create complete]  [16.8s]
  - Private subnet 2 for resources with no internet access               [create complete]  [16.8s]
  - Public subnet 1 for resources that can access the internet           [create complete]  [16.8s]
  - Public subnet 2 for resources that can access the internet           [create complete]  [16.8s]
  - A Virtual Private Cloud to control networking of your AWS resources  [create complete]  [13.9s]
✔ Created environment test in region ap-southeast-2 under application example-app.
Environment test is already on the latest version v1.4.1, skip upgrade.
✔ Proposing infrastructure changes for stack example-app-test-front-end 
- Creating the infrastructure for stack example-app-test-front-end                   [rollback complete]  [866.2s]
  The following resource(s) failed to create: [Service]. Rollback reques                                  
  ted by user.                                                                                            
  - Service discovery for your services to communicate within the VPC                [delete complete]    [0.0s]
  - Update your environment's shared resources                                       [update complete]    [114.2s]
    - A security group for your load balancer allowing HTTP and HTTPS traffic        [create complete]    [5.0s]
    - An Application Load Balancer to distribute public traffic to your services     [create complete]    [92.5s]
  - An IAM Role for the Fargate agent to make AWS API calls on your behalf           [delete complete]    [2.4s]
  - A CloudWatch log group to hold your service logs                                 [delete complete]    [2.4s]
  - An ECS service to run and maintain your tasks in the environment cluster         [delete complete]    [57.8s]
    Resource handler returned message: "Error occurred during operation 'E                                
    CS Deployment Circuit Breaker was triggered'." (RequestToken: XXXXXXXXXXX, HandlerErrorCode: GeneralServiceExceptio                                
    n)                                                                                                    
    Deployments                                                                                            
               Revision  Rollout   Desired  Running  Failed  Pending                                               
      PRIMARY  4         [failed]  1        0        9       1                                                     
  - A target group to connect the load balancer to your service                      [delete complete]    [2.4s]
  - An ECS task definition to group your containers and run them on ECS              [delete complete]    [0.0s]
  - An IAM role to control permissions for the containers in your tasks              [delete complete]    [2.4s]
```

### PR DESCRIPTION
**Pull request by huanjani**
Previously, ARM -> AMD redirection was failing because we don't surface the `platform` field in RDWS manifests.
Now we hard code `linux/amd64` for empty `platform` fields.

Fixes https://github.com/aws/copilot-cli/issues/2640.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the Apache 2.0 License.

### CODE REVIEW

File: internal/pkg/manifest/workload.go [hunk 1]
```diff
@@ -503,12 +503,14 @@ type TaskConfig struct {
...
 // TaskPlatform returns the platform for the service.
-func (t *TaskConfig) TaskPlatform() (*string, error) {
-	if t.Platform.PlatformString == nil {
-		return nil, nil
+func (t *TaskConfig) TaskPlatform() *string {
+	if t.Platform.IsEmpty() {
+		return nil
+	}
+	if t.IsWindows() {
+		return aws.String(platformString(OSWindows, t.Platform.Arch()))
```
Comment (efekarakus) [inline internal/pkg/manifest/workload.go]: what if `Arch` is empty? should we instead just return `OSWindows`?

File: internal/pkg/cli/svc_deploy.go [hunk 2]
```diff
@@ -396,7 +396,7 @@ func (o *deploySvcOpts) dfBuildArgs(svc interface{}) (*dockerengine.BuildArgumen
 func buildArgs(name, imageTag, copilotDir string, unmarshaledManifest interface{}) (*dockerengine.BuildArguments, error) {
 	type dfArgs interface {
 		BuildArgs(rootDirectory string) *manifest.DockerBuildArgs
-		TaskPlatform() (*string, error)
+		TaskPlatform() *string
```
Comment (efekarakus) [inline internal/pkg/cli/svc_deploy.go]: What do you think of 
```suggestion
		TaskPlatform() string
```
instead `""` means use whatever is Docker's default. The clients anyway have to do `aws.StringValue` afterwards

Comment (efekarakus) [reply internal/pkg/cli/svc_deploy.go]: I wonder if we should also rename the method to be `ContainerPlatform` instead to denote that this is related to building the container image and not the ECS platform. (For example, this method name is odd for a RDWS)

**Review by efekarakus — COMMENTED** [review]
yay thank you!!

File: internal/pkg/manifest/workload.go (hunk 1 above)
Comment (huanjani) [reply internal/pkg/manifest/workload.go]: `Arch` is not allowed to be empty; spruced up the `validate` file so we check for both platform parts before we call either `Platform.Arch()` or `Platform.OS()`.

File: internal/pkg/manifest/validate.go [hunk 3]
```diff
@@ -235,6 +254,14 @@ func (w WorkerServiceConfig) Validate() error {
 			return fmt.Errorf(`validate "taskdef_overrides[%d]": %w`, ind, err)
 		}
 	}
+	if w.TaskConfig.IsWindows() {
+		if err = validateWindows(validateWindowsOpts{
+			execEnabled: w.ExecuteCommand.Enable,
+			efsVolumes: w.Storage.Volumes,
+		}); err != nil {
+			return err
```
Comment (iamhopaul123) [inline internal/pkg/manifest/validate.go]: We can probably wrap this error msg and in our unit test we can just validate the error msg prefix like what we are doing for taskdef override. And put more meat into the unit test function for `validateWindows()`

File: internal/pkg/manifest/validate_test.go [hunk 4]
```diff
@@ -148,8 +148,45 @@ func TestLoadBalancedWebService_Validate(t *testing.T) {
 			},
 			wantedErrorMsgPrefix: `validate container dependencies: `,
 		},
+		"error if both Windows and exec indicated": {
```
Comment (iamhopaul123) [inline internal/pkg/manifest/validate_test.go]: like mentioned before we should move this test case into another new test function `Test ValidateWindows_Validate` for `validateWindows()`.

And include `error if fail to validate windows` this test case for each of our workload.

File: internal/pkg/manifest/validate_test.go [hunk 5]
```diff
@@ -317,6 +354,29 @@ func TestRequestDrivenWebService_Validate(t *testing.T) {
...
+					InstanceConfig: AppRunnerInstanceConfig{
+						CPU:      nil,
+						Memory:   nil,
+						Platform: PlatformArgsOrString{
+							PlatformString: (*PlatformString)(aws.String("mockPlatform")),
+						},
+					},
+				},
+			},
+			wantedError: fmt.Errorf("validate \"platform\": platform 'mockPlatform' must be in the format [OS]/[Arch]"),
```
Comment (iamhopaul123) [inline internal/pkg/manifest/validate_test.go]: same we should just validate the error msg prefix as we wrap this error

File: internal/pkg/cli/svc_deploy.go [hunk 6]
```diff
@@ -396,28 +396,25 @@ func (o *deploySvcOpts) dfBuildArgs(svc interface{}) (*dockerengine.BuildArgumen
...
 	var tags []string
 	if imageTag != "" {
 		tags = append(tags, imageTag)
 	}
 	args := mf.BuildArgs(filepath.Dir(copilotDir))
-	platform, err := mf.TaskPlatform()
-	if err != nil {
-		return nil, fmt.Errorf("get platform for service: %w", err)
-	}
+	platform := mf.ContainerPlatform()
```
Comment (iamhopaul123) [inline internal/pkg/cli/svc_deploy.go]: Maybe we don't need this variable at all now

File: internal/pkg/cli/svc_deploy.go [hunk 7]
```diff
@@ -396,28 +396,25 @@ func (o *deploySvcOpts) dfBuildArgs(svc interface{}) (*dockerengine.BuildArgumen
...
 	return &dockerengine.BuildArguments{
 		Dockerfile: *args.Dockerfile,
 		Context:    *args.Context,
 		Args:       args.Args,
 		CacheFrom:  args.CacheFrom,
 		Target:     aws.StringValue(args.Target),
-		Platform:   aws.StringValue(platform),
+		Platform:   platform,
```
Comment (efekarakus) [inline internal/pkg/cli/svc_deploy.go]: mega nit: can we remove the extra variable:
```suggestion
		Platform:   mf.ContainerPlatform(),
```

(https://refactoring.com/catalog/inlineVariable.html)

File: internal/pkg/manifest/rd_web_svc_test.go [hunk 8]
```diff
@@ -316,6 +316,43 @@ func TestRequestDrivenWebService_Port(t *testing.T) {
...
+					PlatformString: nil,
+					},
+				},
+			},
+	}
+	// WHEN
+	actual = mft.ContainerPlatform()
+
+	// THEN
+	require.Equal(t, "linux/amd64", actual)
```
Comment (efekarakus) [inline internal/pkg/manifest/rd_web_svc_test.go]: Instead of having multiple test scenarios in one testcase Go's testing library allows us to nest tests cases like this:
```go
t.Run("should return specified platform number when provided", func(t *testing.T) {

})

t.Run("should default to linux/amd64 when no platform is specified", func(t *testing.T) {
})
```

example: https://github.com/aws/copilot-cli/blob/9e80236e136a86ef592dc598222e4797c9b5e972/internal/pkg/aws/cloudformation/cloudformation_test.go#L787-L788

This has the nice benefit of adding a nice name to the test cases to help us figure out what's the issue when a test fails

File: internal/pkg/manifest/validate.go [hunk 9]
```diff
@@ -520,10 +555,14 @@ func (p PlatformArgsOrString) Validate() error {
 		return nil
 	}
 	if !p.PlatformArgs.isEmpty() {
-		return p.PlatformArgs.Validate()
+		if err := p.PlatformArgs.Validate(); err != nil {
+			return err
+		}
```
Comment (efekarakus) [inline internal/pkg/manifest/validate.go]: what's the difference in this change? the previous version seems to be shorter 🤔

File: internal/pkg/manifest/validate.go [hunk 10]
```diff
@@ -1031,6 +1085,11 @@ type containerDependency struct {
 	isEssential bool
 }
 
+type validateWindowsOpts struct {
+	execEnabled *bool
```
Comment (efekarakus) [inline internal/pkg/manifest/validate.go]: nit:
```suggestion
	execEnabled bool
```

File: internal/pkg/manifest/validate.go [hunk 11]
```diff
@@ -1178,3 +1237,17 @@ func isValidSubSvcName(name string) bool {
 	return len(trailingMatch) == 0
 }
 
+func validateWindows(opts validateWindowsOpts) error {
+	// Exec is not supported for Windows architectures.
```
Comment (efekarakus) [inline internal/pkg/manifest/validate.go]: No need for the comments the error message is pretty clear

**Review by efekarakus — COMMENTED** [review]
Yay looks great! Just minor feedback :shipit:

File: internal/pkg/manifest/validate.go (hunk 9 above)
Comment (huanjani) [reply internal/pkg/manifest/validate.go]: Haha, yes, I've already changed it back, just haven't pushed. I had added more validations below those two so made that change, but forgot to revert when I moved the validations elsewhere. 🤦🏼

**Review by efekarakus — APPROVED** [review]

**Review by iamhopaul123 — APPROVED** [review]
Awesome!
