### PR TITLE
fix(manifest): render http health check path correctly

### LINKED ISSUE #1685: Healthcheck path not present
On Copilot 0.7.0.

My target group healthcheck path is empty (just '/') when deploying the following manifest:
```
http:
  healthcheck: 
    path: '/custom-path-to/healthcheck'
    healthy_threshold: 3
    unhealthy_threshold: 4
    interval: 30s
    timeout: 10s
```
The following works:
```
healthcheck: '/custom-path-to/healthcheck'
```
But I need to adjust healthcheck thresholds in order to allow my app to come online.

Have I misinterpreted the syntax or make a mistake?

Thanks!

### PR DESCRIPTION
**Pull request by iamhopaul123**
fixes #1685

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

File: internal/pkg/manifest/lb_web_svc_test.go [hunk 1]
```diff
@@ -154,6 +154,7 @@ func TestNewLoadBalancedWebService_UnmarshalYaml(t *testing.T) {
 					Interval:           durationp(78 * time.Second),
 					Timeout:            durationp(9 * time.Second),
 				},
+				HealthCheckPath: nil,
```
Comment (efekarakus) [inline internal/pkg/manifest/lb_web_svc_test.go:157]: can we update the name of this test case to reflect this change? for example:
"should use custom healthcheck configuration when provided and set default path to nil"

File: internal/pkg/manifest/workload.go [hunk 2]
```diff
@@ -149,7 +149,8 @@ func (b *BuildArgsOrString) UnmarshalYAML(unmarshal func(interface{}) error) err
 	}
 
 	if !b.BuildArgs.isEmpty() {
-		// Unmarshaled successfully to b.BuildArgs, return.
+		// Unmarshaled successfully to b.BuildArgs, unset b.BuildString, and return.
+		b.BuildString = nil
```
Comment (efekarakus) [inline internal/pkg/manifest/workload.go:153]: does this UnmarshalYAML have unit tests? can we do something similar to above to make sure that the buildstring gets reset to nil if a custom build field is provided

**Review by huanjani — APPROVED** [review]
LGTM!

File: internal/pkg/manifest/workload.go (hunk 2 above)
Comment (iamhopaul123) [reply internal/pkg/manifest/workload.go:153]: it is tested here https://github.com/aws/copilot-cli/pull/1686/files#diff-c4a6f6a13adfd37f7bd3fbc2d6d56fe5d1f2a6e752f6d795628adca336bf97e3R157. since `newDefaultLoadBalancedWebService` has default to be "/" and it is set back to nil

File: internal/pkg/manifest/lb_web_svc_test.go (hunk 1 above)
Comment (iamhopaul123) [reply internal/pkg/manifest/lb_web_svc_test.go:157]: done!

File: internal/pkg/manifest/workload.go (hunk 2 above)
Comment (efekarakus) [reply internal/pkg/manifest/workload.go:153]: wut am I misunderstanding something? that one is for UnmarshalYAML for healthchecks whereas this change is for the `image.build` field

Comment (iamhopaul123) [reply internal/pkg/manifest/workload.go:153]: oooh sorry i misread it.

**Review by efekarakus — APPROVED** [review]
