### PR TITLE
fix: use env accountID for SNS topic ARNs instead of app

### LINKED ISSUE #2949: COPILOT_SNS_TOPIC_ARNS in Cloudformation Template Uses Incorrect AccountID
When creating an application that has a `publish` section in the manifest file, an SNS Topic will be created when you deploy your application and [according to the documentation](https://aws.github.io/copilot-cli/docs/developing/publish-subscribe/) the ARN of the newly created SNS Topic(s) will be injected into your task environment in the `COPILOT_SNS_TOPIC_ARNS` variable.

So, in my application, I am using two separate accounts. I ran my initial `copilot init` for my app using what I'll call the *prod* account, but have a separate environment in another account that we'll call *nonprod*.

Right now, when deploying my application to my *nonprod* environment/account, while building the ARN for the SNS Topic it is hardcoding the Account ID from the *prod* account. In my cloudformation template you see (using fake account IDs):

```yml
- Name: COPILOT_SNS_TOPIC_ARNS
  Value: '{"readyForProcessing":"arn:aws:sns:us-east-1:111111111prod:pf-athena-nonprod-ingest-readyForProcessing"}'
```

However, I would expect to see:

```yml
- Name: COPILOT_SNS_TOPIC_ARNS
  Value: '{"readyForProcessing":"arn:aws:sns:us-east-1:22222222nonprod:pf-athena-nonprod-ingest-readyForProcessing"}'
```

Or maybe even (I think this is the better way to do it):

```yml
- Name: COPILOT_SNS_TOPIC_ARNS
  Value: !Sub '{"readyForProcessing":"arn:aws:sns:us-east-1:${AWS::AccountId}:pf-athena-nonprod-ingest-readyForProcessing"}'
```

I'm using the latest release (`v1.11.0`)

### PR DESCRIPTION
**Pull request by efekarakus**
Fixes #2949 

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the Apache 2.0 License.

### CODE REVIEW

File: internal/pkg/deploy/cloudformation/stack/workload.go [hunk 1]
```diff
@@ -61,12 +61,14 @@ const (
...
-	AddonsTemplateURL        string            // Optional. S3 object URL for the addons template.
-	AdditionalTags           map[string]string // AdditionalTags are labels applied to resources in the workload stack.
-	ServiceDiscoveryEndpoint string            // Endpoint for the service discovery namespace in the environment.
-	AccountID                string            // Account ID for constructing ARNs
-	Region                   string            // Region for constructing ARNs
+	Image             *ECRImage         // Optional. Image location in an ECR repository.
+	AddonsTemplateURL string            // Optional. S3 object URL for the addons template.
+	AdditionalTags    map[string]string // AdditionalTags are labels applied to resources in the workload stack.
+
+	// The target environment metadata.
```
Comment (huanjani) [inline internal/pkg/deploy/cloudformation/stack/workload.go:68]: Ah, this makes sense to separate them!

**Review by huanjani — APPROVED** [review]
Thanks for finding this and fixing it!

**Review by Lou1415926 — APPROVED** [review]
