### PR TITLE
fix(alias): should not delete record for alias in new cert

### LINKED ISSUE #2504: Could not deploy multiple services those set custom domain with `http.alias`
Hi, there. I update copilot to 1.8.0 to set custom domain to multiple services.

```sh
$ copilot --version
copilot version: v1.8.0
```

I have 2 Load Balanced Web Services `frontend` and `rails` those set custom domain as `http.alias` field. 

```yml
name: frontend
type: Load Balanced Web Service

...

environments:
  dev:
    http:
      alias: dev-frontend.example.com
  staging:
    http:
      alias: staging-frontend.example.com
```

```yml
name: rails
type: Load Balanced Web Service

...

environments:
  dev:
    http:
      alias: dev-rails.example.com
  staging:
    http:
      alias: staging-rails.example.com
```

First, I deploy `frontend` service to `dev` environment (`copilot svc deploy --name frontend --env dev`), that enable access `dev-frontend.example.com`. Next, I deploy `rails` service to `dev` environment (`copilot svc deploy --name rails --env dev`), that occur error below.

```
- Creating the infrastructure for stack chronos-dev-rails                       [rollback complete]   [67.3s]
  The following resource(s) failed to create: [EnvControllerAction]. Rol                              
  lback requested by user.                                                                            
  - An EFS access point to handle POSIX permissions                             [not started]         
  - An Addons CloudFormation Stack for your additional AWS resources            [review in progress]  [630.3s]
    - A security group for your workload to access the DB cluster railscluster  [not started]         
  - Service discovery for your services to communicate within the VPC           [delete complete]     [0.0s]
  - Update your environment's shared resources                                  [update complete]     [72.1s]
    - Add an A-record to the hosted zone for the domain alias                   [update complete]     [0.0s]
    - Request and validate an ACM certificate for your domain                   [delete complete]     [67.8s]
  - An IAM Role for the Fargate agent to make AWS API calls on your behalf      [delete complete]     [1.4s]
  - A CloudWatch log group to hold your service logs                            [delete complete]     [0.0s]
  - An ECS service to run and maintain your tasks in the environment cluster    [not started]         
  - A target group to connect the load balancer to your service                 [delete complete]     [0.0s]
  - An ECS task definition to group your containers and run them on ECS         [not started]         
  - An IAM role to control permissions for the containers in your tasks         [not started]     
```

I confirm management console in CloudFormation, output this error below.

スクリーンショット 2021-06-23 20 03 46

### PR DESCRIPTION
**Pull request by iamhopaul123**
fixes #2504 also added e2e test for multi services in one env case.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by iamhopaul123** [comment]
Ginkgo ran 1 suite in 1h4m51.561899092s
Test Suite Passed

File: cf-custom-resources/lib/dns-cert-validator.js [hunk 1]
```diff
@@ -238,104 +238,74 @@ const updateHostedZoneRecords = async function (
...
+      .promise();
+    for (const certSummary of listCertResp.CertificateSummaryList || []) {
+      if (
+        certSummary.DomainName !== defaultDomain ||
+        certSummary.CertificateArn === certArn
+      ) {
+        // Skip if it is not the new certificate.
+        continue;
       }
+      const { Certificate } = await acm
```
Comment (efekarakus) [inline cf-custom-resources/lib/dns-cert-validator.js:269]: nit:
```suggestion
      // There exist another certificate created by Copilot later which has the updated alias fields as SANS.
      // We don't want to delete any validation records associated with the new certificate.
      const { Certificate } = await acm
```

File: cf-custom-resources/lib/dns-cert-validator.js [hunk 2]
```diff
@@ -238,104 +238,74 @@ const updateHostedZoneRecords = async function (
...
       break;
+    }
+    if (!listCertResp.NextToken) {
+      break;
+    }
+    listCertificatesInput.NextToken = listCertResp.NextToken;
+  }
+  const newCertOptionSet = new Set(
+    newCertOptions.map((item) => item.DomainName)
+  );
```
Comment (efekarakus) [inline cf-custom-resources/lib/dns-cert-validator.js]: Can we rename these variables like this? 
nit: personally I find it harder to read once we break it up into these new lines
```suggestion
  const newCertSANS = new Set(newCertOptions.map((item) => item.DomainName));
```

File: cf-custom-resources/lib/dns-cert-validator.js [hunk 3]
```diff
@@ -238,104 +238,74 @@ const updateHostedZoneRecords = async function (
 // deleteHostedZoneRecords deletes the validation records associated with the certificate.
 // We don't want to delete a validation record if it's used by another certificate because
 // the validation records are used to renew the certificate.
-// The legacy certificate (only `${envName}.${appName}.${domainName}`) and the new
-// certificate generated with the "alias" field share the same validation record.
-// Therefore, we check if there is more than one certificate using the record and only delete
-// if there is no other certificate using the record.
 const deleteHostedZoneRecords = async function (
   options,
```
Comment (efekarakus) [inline cf-custom-resources/lib/dns-cert-validator.js]: can we rename this to `oldCertOptions` so that we contrast it against `newCertOptions`

File: cf-custom-resources/lib/dns-cert-validator.js [hunk 4]
```diff
@@ -238,104 +238,74 @@ const updateHostedZoneRecords = async function (
...
+    if (!listCertResp.NextToken) {
+      break;
+    }
+    listCertificatesInput.NextToken = listCertResp.NextToken;
+  }
+  const newCertOptionSet = new Set(
+    newCertOptions.map((item) => item.DomainName)
+  );
+  const recordOptionToDelete = [];
+  for (const option of options) {
```
Comment (efekarakus) [inline cf-custom-resources/lib/dns-cert-validator.js]: nit:
```suggestion
  for (const oldCertOption of oldCertOptions) {
```

File: cf-custom-resources/lib/dns-cert-validator.js [hunk 5]
```diff
@@ -238,104 +238,74 @@ const updateHostedZoneRecords = async function (
...
+    if (!newCertOptionSet.has(option.DomainName)) {
+      recordOptionToDelete.push(option);
```
Comment (efekarakus) [inline cf-custom-resources/lib/dns-cert-validator.js]:
```suggestion
      // This alias field is no longer in use, we can safely delete its validation.
      recordOptionToDelete.push(option);
```

File: e2e/app-with-domain/app_with_domain_test.go [hunk 6]
```diff
@@ -70,47 +70,64 @@ var _ = Describe("App With Domain", func() {
...
+				Name:     "hello",
 				EnvName:  "test",
 				ImageTag: "hello",
 			})
 			Expect(deployErr).NotTo(HaveOccurred())
 		})
 
-		It("svc deploy to prod should succeed", func() {
+		It("deploy frontend to test should succeed", func() {
+			_, deployErr = cli.SvcDeploy(&client.SvcDeployInput{
```
Comment (efekarakus) [inline e2e/app-with-domain/app_with_domain_test.go:110]: oh boy this test is gonna take forever to run :D

**Review by efekarakus — COMMENTED** [review]
Looks good just some renaming and comments to make it clearer!

File: cf-custom-resources/lib/dns-cert-validator.js (hunk 2 above)
Comment (iamhopaul123) [reply cf-custom-resources/lib/dns-cert-validator.js]: It's formatted by vscode 🤔 I'll rename the variables.

Comment (efekarakus) [reply cf-custom-resources/lib/dns-cert-validator.js]: 💩

Comment (iamhopaul123) [reply cf-custom-resources/lib/dns-cert-validator.js]: ok after renaming it collapses to one line

File: e2e/app-with-domain/app_with_domain_test.go (hunk 6 above)
Comment (iamhopaul123) [reply e2e/app-with-domain/app_with_domain_test.go:110]: about 1h in total

**Review by efekarakus — APPROVED** [review]

File: cf-custom-resources/lib/dns-cert-validator.js [hunk 7]
```diff
@@ -238,104 +238,75 @@ const updateHostedZoneRecords = async function (
...
 // the validation records are used to renew the certificate.
-// The legacy certificate (only `${envName}.${appName}.${domainName}`) and the new
-// certificate generated with the "alias" field share the same validation record.
-// Therefore, we check if there is more than one certificate using the record and only delete
-// if there is no other certificate using the record.
 const deleteHostedZoneRecords = async function (
-  options,
-  certDomain,
+  oldCertOptions,
+  certArn,
```
Comment (Lou1415926) [inline cf-custom-resources/lib/dns-cert-validator.js]:
```suggestion
  oldCertArn,
```
I think this may help understanding the rest of the code!

File: cf-custom-resources/lib/dns-cert-validator.js [hunk 8]
```diff
@@ -238,104 +238,75 @@ const updateHostedZoneRecords = async function (
...
+        continue;
       }
+      // There exists another certificate created by Copilot which has the updated alias fields as SANs.
+      // We don't want to delete any validation records associated with the new certificate.
+      const { Certificate } = await acm
+        .describeCertificate({
+          CertificateArn: certSummary.CertificateArn,
+        })
+        .promise();
+      newCertOptions = Certificate.DomainValidationOptions || [];
```
Comment (Lou1415926) [inline cf-custom-resources/lib/dns-cert-validator.js:274]: We intend to break out of the larger `while` loop right?

File: cf-custom-resources/lib/dns-cert-validator.js [hunk 9]
```diff
@@ -238,104 +238,75 @@ const updateHostedZoneRecords = async function (
...
-      // since the legacy cert still needs the validation record in the env hosted zone.
-      for (const option of options) {
-        if (option.DomainName === certDomain || option.DomainName === `*.${certDomain}`) {
-          continue;
-        }
-        newOptions.push(option);
+  let listCertificatesInput = {};
+  let newCertOptions = [];
+  // Make sure if there is a new certificate, we don't delete any DNS validation records
+  // that are used by the new certificate.
```
Comment (Lou1415926) [inline cf-custom-resources/lib/dns-cert-validator.js]:
```suggestion
  // Look for the new certificate, and note down its validation records. 
  //This is to make sure if there is a new certificate, we don't delete any DNS validation records that are used by the new certificate.
```

File: cf-custom-resources/lib/dns-cert-validator.js [hunk 10]
```diff
@@ -238,104 +238,75 @@ const updateHostedZoneRecords = async function (
...
+  while (true) {
+    const listCertResp = await acm
+      .listCertificates(listCertificatesInput)
+      .promise();
+    for (const certSummary of listCertResp.CertificateSummaryList || []) {
+      if (
+        certSummary.DomainName !== defaultDomain ||
+        certSummary.CertificateArn === certArn
+      ) {
+        // Skip if it is not the new certificate.
```
Comment (Lou1415926) [inline cf-custom-resources/lib/dns-cert-validator.js]:
```suggestion
        // Skip if it is not the new certificate for the domain.
```

File: cf-custom-resources/lib/dns-cert-validator.js [hunk 11]
```diff
@@ -238,104 +238,75 @@ const updateHostedZoneRecords = async function (
...
+      newCertOptions = Certificate.DomainValidationOptions || [];
+      break;
+    }
+    if (!listCertResp.NextToken) {
       break;
+    }
+    listCertificatesInput.NextToken = listCertResp.NextToken;
+  }
+  const newCertSANs = new Set(newCertOptions.map((item) => item.DomainName));
+  const recordOptionToDelete = [];
```
Comment (Lou1415926) [inline cf-custom-resources/lib/dns-cert-validator.js]: nit:
```suggestion
  const recordOptionsToDelete = [];
```

**Review by Lou1415926 — COMMENTED** [review]
LGTM! Just a few nits on comment clarify and one question ⬇️

File: cf-custom-resources/lib/dns-cert-validator.js (hunk 8 above)
Comment (iamhopaul123) [reply cf-custom-resources/lib/dns-cert-validator.js:274]: yeah cause that means we found it

Comment (Lou1415926) [reply cf-custom-resources/lib/dns-cert-validator.js:274]: This probably doesn't matter since there should be only one such cert. But it seems like we are only breaking out of the for-loop, not the while loop 🤔

Comment (iamhopaul123) [reply cf-custom-resources/lib/dns-cert-validator.js:274]: yeah that's true. OK done fixing it.

**Review by Lou1415926 — APPROVED** [review]
:shipit: 🚢
