### PR TITLE
fix(cli): best-effort create service linked role for ECS on env init

### LINKED ISSUE #1324: Failed to create a new environment if it's the first time to create an ECS cluster in an AWS account
Reproduce:
- Create a new AWS account
- Use that account for `copilot init`
- 'Yes' for deploying test env (or `copilot env init` after 'No' for it)

Then the CFn stack for new env is going to fail due to an error something like:
```
Invalid request provided: CreateCluster Invalid Request: Unable to assume the service linked role. Please verify that the ECS service linked role exists. (Service: Ecs, Status Code: 400, Request ID: a973c2ca-204c-4715-9e2e-6097da7eb8c1, Extended Request ID: null)
```

Here is the CLI output:
```
~ snip ~
All right, you're all set for local development.
Deploy: Yes

✘ Failed to create the infrastructure for the test environment.
- Virtual private cloud on 2 availability zones to hold your services                       [Failed]
- Virtual private cloud on 2 availability zones to hold your services                       [Failed]
  Resource creation cancelled
  - Internet gateway to connect the network to the internet                                 [Failed]
  Resource creation cancelled                                                                        ess]
  - Public subnets for internet facing services                                             [In Progress]
  - Private subnets for services that can't be reached from the internet                    [In Progress]
  - Routing tables for services to talk with each other                                     [In Progress]
- ECS Cluster to hold your services                                                         [Failed]
  Invalid request provided: CreateCluster Invalid Request: Unable to assume the service linked role  ess]
- Application load balancer to distribute traffic                                           [In Progress]
✘ wait until stack prod-ready-copilot-test create is complete: ResourceNotReady: failed waiting for successful resource state

$ copilot --version
copilot version: v0.3.0
```

I think we need some documentation and/or nice CLI output to let users solve - removing the existing failed stack and `copilot env init` again - this problem.

### PR DESCRIPTION
**Pull request by efekarakus**
For accounts that never used ECS before, the [service linked role](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/using-service-linked-roles.html) does not exist which results in ECS not being able to create the cluster during `env init`.

This change attempts a best-effort creation of the role before creating the environment stack.

Resolves #1324

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

File: internal/pkg/cli/env_init.go [hunk 1]
```diff
@@ -228,25 +233,30 @@ func (o *initEnvOpts) Execute() error {
 			return fmt.Errorf("granting DNS permissions: %w", err)
 		}
 	}
-	// 1. Start creating the CloudFormation stack for the environment.
+	// 1. Attempt to create the service linked role if it doesn't exist.
+	// If the call fails because the role already exists, nothing to do.
+	// If the call fails because the user doesn't have permissions, then the role must be created outside of Copilot.
+	_ = o.iam.CreateECSServiceLinkedRole()
```
Comment (bvtujo) [inline internal/pkg/cli/env_init.go:239]: Are those the only two failure cases? Is it okay not to fail here due to permissions issues without surfacing any error?

File: internal/pkg/aws/iam/iam.go [hunk 2]
```diff
@@ -57,6 +62,18 @@ func (c *IAM) DeleteRole(roleARN string) error {
...
 }
 
+// CreateECSServiceLinkedRole creates a Service-Linked Role for Amazon ECS.
+// This role is necessary so that Amazon ECS can call AWS APIs.
+// https://docs.aws.amazon.com/AmazonECS/latest/developerguide/using-service-linked-roles.html
+func (c *IAM) CreateECSServiceLinkedRole() error {
+	if _, err := c.client.CreateServiceLinkedRole(&iam.CreateServiceLinkedRoleInput{
+		AWSServiceName: aws.String(ecsServiceName),
+	}); err != nil {
+		return fmt.Errorf("create service linked role for Amazon ECS: %w", err)
```
Comment (bvtujo) [inline internal/pkg/aws/iam/iam.go]: Do we need to wrap this error, since it a) doesn't ever get reported and b) will always be wrapped by other methods?

**Review by bvtujo — COMMENTED** [review]
Looks good, just a couple of questions

File: internal/pkg/cli/env_init.go (hunk 1 above)
Comment (efekarakus) [reply internal/pkg/cli/env_init.go:239]: I feel like it's fine because I don't' know what more we can do here for the user:
If the user doesn't have permission and the role was already created -> we don't want to fail.
If there was an internal error -> we don't want to fail.
For all other situations -> same behavior as today, it will print that the role is missing.

File: internal/pkg/aws/iam/iam.go (hunk 2 above)
Comment (efekarakus) [reply internal/pkg/aws/iam/iam.go]: Hmm good question 🤔, I think:
a) That should be up to the client to decide whether they want to ignore the error or handle it, so we should still return the error.
b) It's definitely odd reading: `"create ECS service linked role: create ECS service linked role: AWS err"`
I think we should still wrap but I'll change the data of this error message so that it's more specific to the input of the call:
`"create service linked role for ecs.amazonaws.com: %w"`

**Review by bvtujo — APPROVED** [review]
🚀

**Review by iamhopaul123 — APPROVED** [review]
