### PR TITLE
fix(describe): use new deploy store API to improve Describe

### LINKED ISSUE #1003: svc show fails when the service is deploying
When a service is deploying and `svc show` fails because of "ClientException".

```
$ archer svc show
Which application's service would you like to show? e2e-multisvc-1591649836
Which service of e2e-multisvc-1591649836 would you like to show? front-end
Error: describe service front-end: retrieve environment variables: describe task definition e2e-multisvc-1591649836-test-front-end: ClientException: Unable to describe task definition.
```

### PR DESCRIPTION
**Pull request by iamhopaul123**
Part of #1069. Fixes #1003.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by iamhopaul123** [comment]
## Manual Test

1. When a new service is not deployed in any env
```
$ copilot svc show
About

  Application       my-project
  Name              my-app
  Type              Load Balanced Web Service

Configurations

  Environment       Tasks               CPU (vCPU)          Memory (MiB)        Port

Routes

  Environment       URL

Service Discovery

  Environment       Namespace

Variables

  Name              Environment         Value
```

2. When it is deployed
```
$ copilot svc show
About

  Application       my-project
  Name              my-app
  Type              Load Balanced Web Service

Configurations

  Environment       Tasks               CPU (vCPU)          Memory (MiB)        Port
  test              1                   0.25                512                 5000

Routes

  Environment       URL
  test              http://my-pr-Publi-1BVP1UJT0GI0K-1645102785.us-west-2.elb.amazonaws.com/my-app

Service Discovery

  Environment       Namespace
  test              my-app.my-project.local:5000

Variables

  Name                                Environment         Value
  COPILOT_APPLICATION_NAME            test                my-project
  COPILOT_ENVIRONMENT_NAME            test                test
  COPILOT_LB_DNS                      test                my-pr-Publi-1BVP1UJT0GI0K-1645102785.us-west-2.elb.amazonaws.com
  COPILOT_SERVICE_DISCOVERY_ENDPOINT  test                my-project.local
  COPILOT_SERVICE_NAME                test                my-app
```

File: internal/pkg/describe/backend_service.go [hunk 1]
```diff
@@ -20,7 +21,7 @@ type BackendServiceDescriber struct {
 	service         *config.Service
 	enableResources bool
 
-	store                storeSvc
+	store                deployStoreSvc
```
Comment (iamhopaul123) [inline internal/pkg/describe/backend_service.go:24]: i'll rename this back to be "storeSvc" once i fix env show in my next pr. Then we'll remove dependency to config pkg.

**Comment by kohidave** [comment]
I’m not sure if you plan to tackle the UX for this yet but maybe instead of an empty svc show - we say “this service is not deployed yet. Run copilot svc deploy” or something like that.

**Comment by iamhopaul123** [comment]
> I’m not sure if you plan to tackle the UX for this yet but maybe instead of an empty svc show - we say “this service is not deployed yet. Run copilot svc deploy” or something like that.

hmm i think it kind of makes sense to me to show empty svc show for svcs that are not deployed yet. i'll fix it for svc status, which should return error if the ECS service is not initiated yet.

File: internal/pkg/deploy/deploy.go [hunk 2]
```diff
@@ -59,11 +59,7 @@ type Store struct {
 }
 
 // NewStore returns a new store.
-func NewStore() (*Store, error) {
-	store, err := config.NewStore()
-	if err != nil {
-		return nil, fmt.Errorf("connect to config store: %w", err)
-	}
+func NewStore(store configStoreClient) (*Store, error) {
```
Comment (efekarakus) [inline internal/pkg/deploy/deploy.go:62]: out-of-curiosity what does it look like for a client that wants to use the constructor if the interface is private?
What does the error message look like if they pass an obj that doesnt implement the interface :O or what do the docs look like

File: internal/pkg/describe/backend_service.go [hunk 3]
```diff
@@ -20,25 +21,29 @@ type BackendServiceDescriber struct {
...
 	svcDescriber         svcDescriber
 	initServiceDescriber func(string) error
 }
 
 // NewBackendServiceDescriber instantiates a backend service describer.
 func NewBackendServiceDescriber(app, svc string) (*BackendServiceDescriber, error) {
```
Comment (efekarakus) [inline internal/pkg/describe/backend_service.go:30]: This is def. for a separate PR but it would be cool if the constructor just had parameters for the dependencies instead of initializing them.

We can see why it's useful to do that in l.39 where previously `deploy.NewStore()` would just re-create the same `config` client so we'd have multiple location where the client initialization could fail.

File: internal/pkg/deploy/deploy.go (hunk 2 above)
Comment (iamhopaul123) [reply internal/pkg/deploy/deploy.go:62]: > out-of-curiosity what does it look like for a client that wants to use the constructor if the interface is private?

https://github.com/aws/copilot-cli/pull/1090/files#diff-88fdaab0450f79a9400f9ba9c6d7c280R39

> What does the error message look like if they pass an obj that doesnt implement the interface :O or what do the docs look like

it will not be compilable i think...

**Comment by iamhopaul123** [comment]
> I’m not sure if you plan to tackle the UX for this yet but maybe instead of an empty svc show - we say “this service is not deployed yet. Run copilot svc deploy” or something like that.

issue noted here: https://github.com/aws/copilot-cli/issues/1093
