### PR TITLE
fix(manifest): add more validation on manifest.AdvancedCount

### LINKED ISSUE #2229: bug: specifying autoscaling options in svc manifest with no range results in segfault
Under the `count` field, if autoscaling options are specified without a Range, e.g.:
```
count:
  cpu_percentage: 20
```

This will result in a panic on `svc deploy`:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x197db38]

goroutine 1 [running]:
github.com/aws/copilot-cli/internal/pkg/deploy/cloudformation/stack.convertAutoscaling(0xc0003c2c70, 0xcc1, 0xc0001e0d80, 0xcc1)
	/Users/hsinghui/workspace/copilot-cli/internal/pkg/deploy/cloudformation/stack/transformers.go:184 +0x78
github.com/aws/copilot-cli/internal/pkg/deploy/cloudformation/stack.convertAdvancedCount(0xc0003c2c70, 0x0, 0x0, 0x0)
	/Users/hsinghui/workspace/copilot-cli/internal/pkg/deploy/cloudformation/stack/transformers.go:105 +0x45
github.com/aws/copilot-cli/internal/pkg/deploy/cloudformation/stack.(*LoadBalancedWebService).Template(0xc00039fb00, 0x0, 0x0, 0x0, 0x0)
	/Users/hsinghui/workspace/copilot-cli/internal/pkg/deploy/cloudformation/stack/lb_web_svc.go:112 +0x490
github.com/aws/copilot-cli/internal/pkg/deploy/cloudformation.toStack(0x2a33320, 0xc00039fb00, 0xbdfadb0, 0x10, 0x18)
	/Users/hsinghui/workspace/copilot-cli/internal/pkg/deploy/cloudformation/cloudformation.go:383 +0x35
github.com/aws/copilot-cli/internal/pkg/deploy/cloudformation.CloudFormation.DeployService(0x2a422a8, 0xc000352bb0, 0x2a0a820, 0xc000352c20, 0x2a0a7a0, 0xc000566ce0, 0x2a0a8c0, 0xc0004ceb70, 0xc000353000, 0x2a3baf8, ...)
	/Users/hsinghui/workspace/copilot-cli/internal/pkg/deploy/cloudformation/workload.go:18 +0x4d
github.com/aws/copilot-cli/internal/pkg/cli.(*deploySvcOpts).deploySvc(0xc000356e00, 0x0, 0x0, 0x0, 0x0)
	/Users/hsinghui/workspace/copilot-cli/internal/pkg/cli/svc_deploy.go:440 +0x1b4
github.com/aws/copilot-cli/internal/pkg/cli.(*deploySvcOpts).Execute(0xc000356e00, 0x0, 0x0)
	/Users/hsinghui/workspace/copilot-cli/internal/pkg/cli/svc_deploy.go:167 +0x417
github.com/aws/copilot-cli/internal/pkg/cli.buildSvcDeployCmd.func1(0xc000414a00, 0x3628f30, 0x0, 0x0, 0xc00029fd58, 0x0)
	/Users/hsinghui/workspace/copilot-cli/internal/pkg/cli/svc_deploy.go:517 +0x118
github.com/aws/copilot-cli/internal/pkg/cli.runCmdE.func1(0xc000414a00, 0x3628f30, 0x0, 0x0, 0x0, 0x0)
	/Users/hsinghui/workspace/copilot-cli/internal/pkg/cli/cli.go:66 +0x6e
github.com/spf13/cobra.(*Command).execute(0xc000414a00, 0x3628f30, 0x0, 0x0, 0xc000414a00, 0x3628f30)
	/Users/hsinghui/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:852 +0x472
github.com/spf13/cobra.(*Command).ExecuteC(0xc0003cd680, 0x10014b0, 0x0, 0x0)
	/Users/hsinghui/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:960 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/hsinghui/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:897
main.main()
	/Users/hsinghui/workspace/copilot-cli/cmd/copilot/main.go:25 +0x2b
```

### PR DESCRIPTION
**Pull request by SoManyHs**
Previously, invalid count specifications in the service manifest would
result in a segfault. This catches those errors during unmarshalling.

Fixes: #2229

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by SoManyHs** [comment]
Now, if manifest has bad count specification, e.g.:

```
count:
  cpu_percentage: 20
```

Copilot gives you the following error:

```
$ copilot svc deploy
Only found one service, defaulting to: api
Only found one environment, defaulting to: test
Environment test is already on the latest version v1.3.0, skip upgrade.
✘ unmarshal service api manifest: unmarshal to load balanced web service: must specify "range" if using autoscaling
```

File: internal/pkg/manifest/svc.go [hunk 1]
```diff
@@ -134,8 +134,9 @@ func (c *Count) UnmarshalYAML(unmarshal func(interface{}) error) error {
 		}
 	}
 
-	if !c.AdvancedCount.IsValid() {
-		return errUnmarshalSpot
+	err := c.AdvancedCount.IsValid()
+	if err != nil {
+		return err
 	}
```
Comment (huanjani) [inline internal/pkg/manifest/svc.go]: nit: save a line?
```suggestion
	if err := c.AdvancedCount.IsValid(); err != nil {
		return err
	}
```

**Review by huanjani — APPROVED** [review]
Looks great!

**Review by efekarakus — APPROVED** [review]
