### PR TITLE
fix: clean up IAM roles on env stack failures

### LINKED ISSUE #2100: Stack Cleanup for Environments fails
Good morning COPILOTS!

I've noticed, that while working with customers, that the environment cloudformation stack cleanup currently has a couple of pernicious issues that can cause quite a bit of customer confusion. 

## Steps to repro

1. Run `copilot init`
2. Environment creation CloudFormation fails (for permissions, limits, whatever) 
3. Customer fixes issue
4. Run `copilot init` again
5. The stack creation will fail with an error: 
    > ... check if changeset is empty: create change set copilot-842c4f30-ada3-40ac-984c-0f18b7d5241b for stack app-env: ValidationError: Stack [app-env] already exists and cannot be created again with the changeSet [copilot-842c4f30-ada3-40ac-984c-0f18b7d5241b].
6. Ok, this looks like a race condition - so wait a few seconds, and then try running `copilot init` again
7. In this case, you'll get an error that the CFN Execution role already exists: `app-env-CFNExecutionRole already exists`

Looks like the env manager role is not being deleted 🤔 

## What I expect

1. Run `copilot init`
2. Environment creation CloudFormation fails (for permissions, limits, whatever) 
3. Customer fixes issue
4. Run `copilot init`
5. The previous stack is deleted - and we wait until it's created, and then the new stack is created successfully 

## Summary

Two issues - the environment stack cleanup seems to have a race condition that doesn't properly wait for the stack to be deleted. The CFNExecution role isn't cleaned up. I didn't try with workloads. 

Thank you friends!

### PR DESCRIPTION
**Pull request by efekarakus**
Fixes #2100 

1. We now wait for a failed stack to be deleted first before attempting to re-create it.
2. Best-effort attempt to delete IAM roles on `env delete` this removes intermittent role deletion errors in the CLI.
3. If a user deletes an environment, and then re-creates it, `env init` now ensures the previous dangling IAM roles are deleted.
4. Similarly, if the env stack creation fails, we delete any retained IAM roles created part of the stack.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by kohidave** [comment]
Heroic.

File: internal/pkg/cli/interfaces.go [hunk 1]
```diff
@@ -531,6 +531,20 @@ type serviceLinkedRoleCreator interface {
...
+	ListRoleTags(string) (map[string]string, error)
+}
+
+type roleManager interface {
+	roleTagsLister
+	roleDeleter
+	serviceLinkedRoleCreator
+}
+
+type stackExister interface {
```
Comment (bvtujo) [inline internal/pkg/cli/interfaces.go]: nit: Is there a way we can reframe this? The name is a little confusing, and while it's clear that it's not a `stackCreator` it's not immediately clear what the interface does from the `exister` verb.
```suggestion
type stackExistChecker interface 
```

**Review by bvtujo — APPROVED** [review]
What David said. This is amazing, and should help with a lot of our frustrating error cases. I combed through and couldn't find anything confusing; so I just have a naming nit.

File: internal/pkg/aws/cloudformation/cloudformation.go [hunk 2]
```diff
@@ -187,6 +187,30 @@ func (c *CloudFormation) Describe(name string) (*StackDescription, error) {
 	return &descr, nil
 }
 
+// Exists returns true if the environment stack exists, false otherwise.
+// If an error occurs for another reason than ErrStackNotFound, then returns the error.
```
Comment (iamhopaul123) [inline internal/pkg/aws/cloudformation/cloudformation.go]: Maybe
```suggestion
// Exists returns true if the CloudFormation stack exists, false otherwise.
// If an error occurs for another reason than ErrStackNotFound, then returns the error.
```
as `aws.cloudformation` pkg should be agnostic about Copilot terminology?

File: internal/pkg/aws/cloudformation/cloudformation.go [hunk 3]
```diff
@@ -58,7 +58,7 @@ func (c *CloudFormation) Create(stack *Stack) (changeSetID string, err error) {
 	status := StackStatus(aws.StringValue(descr.StackStatus))
 	if status.requiresCleanup() {
 		// If the stack exists, but failed to create, we'll clean it up and then re-create it.
-		if err := c.Delete(stack.Name); err != nil {
+		if err := c.DeleteAndWait(stack.Name); err != nil {
```
Comment (iamhopaul123) [inline internal/pkg/aws/cloudformation/cloudformation.go:61]: :tada:

File: internal/pkg/cli/env_init.go [hunk 4]
```diff
@@ -548,12 +555,18 @@ func (o *initEnvOpts) deployEnv(app *config.Application, customResourcesURLs map
...
+	}
 	if err := o.envDeployer.DeployAndRenderEnvironment(os.Stderr, deployEnvInput); err != nil {
 		var existsErr *cloudformation.ErrStackAlreadyExists
 		if errors.As(err, &existsErr) {
 			// Do nothing if the stack already exists.
 			return nil
 		}
+		// The stack failed to create due to an unexpect reason.
+		// Delete the retained roles created part of the stack.
+		o.tryDeletingEnvRoles(o.appName, o.name)
```
Comment (iamhopaul123) [inline internal/pkg/cli/env_init.go:569]: If we delete the role before deleting the stack (since it failed to be deleted), will this make users not authorized to manage the env stack unless they manually create the env manager role again (if env upgrade happened before)?

File: internal/pkg/aws/cloudformation/cloudformation.go [hunk 5]
```diff
@@ -236,6 +260,25 @@ func (c *CloudFormation) Events(stackName string) ([]StackEvent, error) {
 	return c.events(stackName, func(in *cloudformation.StackEvent) bool { return true })
 }
 
+// StackResources returns the list of resources created part of a CloudFormation stack.
```
Comment (Lou1415926) [inline internal/pkg/aws/cloudformation/cloudformation.go]:
```suggestion
// StackResources returns the list of resources created as parts of a CloudFormation stack.
```

File: internal/pkg/cli/env_init.go (hunk 4 above)
Comment (Lou1415926) [reply internal/pkg/cli/env_init.go:569]: PH's comment makes me wonder whether it is guaranteed that if `deployAndRenderEnvironment` fails, then the env stack will be rolled back and delete 🤔

**Review by Lou1415926 — COMMENTED** [review]
Awesome! Nothing much to add except for a tiny nit on comment and a quesiton.

File: internal/pkg/cli/env_init.go (hunk 4 above)
Comment (iamhopaul123) [reply internal/pkg/cli/env_init.go:569]: Very good point! I think most of the time it will just be deleted but sometimes the rollback could fail (see `ROLLBACK_FAILED` in [here](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-describing-stacks.html)). It is just since we always try deleting the roles for a clean state when we create the environment so maybe it is ok to skip deleting the roles if the creation fails?

Comment (efekarakus) [reply internal/pkg/cli/env_init.go:569]: I don't think I am fully following, so I'll try my best to clarify but please let me know if I'm not answering properly:

1. > If we delete the role before deleting the stack (since it failed to be deleted), will this make users not authorized to manage the env stack unless they manually create the env manager role again 

We don't pass a RoleARN for CloudFormation to assume when we initially create the stack. So on failure, it is safe to delete the roles that were retained since they were not used yet to mutate the cloudformation stack.

2. > `whether it is guaranteed that if deployAndRenderEnvironment fails, then the env stack will be rolled back and delete`

On failure, `deployAndRenderEnvironment` will indeed rollback back the stack but won't delete it. Instead, the second time that the customer runs `copilot env init` then on `Create` we will check if the stack requires deletion and if so first delete it and then re-create it: https://github.com/aws/copilot-cli/blob/1284849126a6a09b5ac25fe883501793d28f8a7f/internal/pkg/aws/cloudformation/cloudformation.go#L48-L65

3. > it is ok to skip deleting the roles if the creation fails

This would be true, if only the stack got deleted if the creation fails. Instead it goes into a `ROLLBACK_COMPLETE`  state I believe. So if the user just re-runs `copilot env init` and we don't clean up the IAM roles on failed create, then we will:
  1.  first check if the stack exists ✅, so skip 
  2. The stack tries to re-create the IAM but fails because the CFNExecRole already exists ❌
  
Does this help?

Comment (iamhopaul123) [reply internal/pkg/cli/env_init.go:569]: Ah yes. Sorry I was stupid I wasn't aware it is creating an environment so env upgrade can't happen before.

Im totally ok with the current implementation but 
> The stack tries to re-create the IAM but fails because the CFNExecRole already exists ❌

`env init` will try to delete the existing IAM roles before deploying the stack right?

Comment (Lou1415926) [reply internal/pkg/cli/env_init.go:569]: Yesss thanks for the explanation! It makes sense. I have no problem with the current implementation either but same question as Penghao's just to make sure my understanding aligns with the implementation.

File: internal/pkg/cli/interfaces.go (hunk 1 above)
Comment (efekarakus) [reply internal/pkg/cli/interfaces.go]: Done!

File: internal/pkg/aws/cloudformation/cloudformation.go (hunk 2 above)
Comment (efekarakus) [reply internal/pkg/aws/cloudformation/cloudformation.go]: Yup sorry, I had this method originally in the `describe` pkg and while moving it here forgot to update the comment :D fixed!

File: internal/pkg/cli/env_init.go (hunk 4 above)
Comment (efekarakus) [reply internal/pkg/cli/env_init.go:569]: > env init will try to delete the existing IAM roles before deploying the stack right?

Yes that's right! We delete the roles iff:
1. There is no environment cloudformation stack
2. But there are IAM roles

This scenario means that `env delete` previously failed to delete the EnvManagerRole and it should be cleaned up before trying to re-create it. I updated the comment in the `cleanUpDanglingRoles` method, hopefully that explains a bit better this scenario.

**Review by Lou1415926 — APPROVED** [review]
