### PR TITLE
fix(task): use only env security group for task run

### LINKED ISSUE #1882: svc delete hangs at `UPDATE_COMPLETE_CLEANUP_IN_PROGRESS`
I ran a copilot one-off task in an environment and the env stack hung at `UPDATE_COMPLETE_CLEANUP_IN_PROGRESS` status when i ran `copilot svc delete` to delete the last ALB service in that environment. The CFN events said it was because it failed to delete the ALB security group because `it has a dependent object`.

Under the hood it is because when you run a task in an app env cluster, copilot will find all the security groups tagged with app env tags, and pass those security groups to `ecs:TaskRun`. However, since it adds both environment security group and ALB security group, it creates an ENI and attaches both env security group and ALB security group to the ENI. As a result, when doing `svc delete` and the env controller is trying to delete the ALB security group, it fails because the security group is still attaching to the ENI. In this situation you have to stop the running one-off task in order to remove the ENI before deleting the service.

Given the reason above, since for now we don't allow importing security groups, we should only use the environment security group when we run a task in an environment.

### PR DESCRIPTION
**Pull request by iamhopaul123**
fixes #1882.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

File: internal/pkg/task/env_runner_test.go [hunk 1]
```diff
@@ -30,6 +30,10 @@ func TestEnvRunner_Run(t *testing.T) {
 			Values: []string{inApp},
 		},
 	}
+	filtersForSecurityGroup := append(filtersForSubnetID, ec2.Filter{
+		Name:   fmt.Sprintf(ec2.TagFilterName, envSecurityGroupCFNLogicalIDTagKey),
```
Comment (efekarakus) [inline internal/pkg/task/env_runner_test.go]: nit: Can we use the strings directly? like "tag:aws:cloudformation:logical-id" to make sure that the function under test does the translation properly

**Review by efekarakus — APPROVED** [review]
Great investigation on this! 🕵️‍♀️

**Review by huanjani — APPROVED** [review]
