### PR TITLE
fix: honor env-specific `image` override 

### LINKED ISSUE #1702: Copilot should honor env-specific overrides in image.build
Now that we support an increasing number of Docker build flags in the manifest, customers want to be able to customize these flags per environment the same way they customize environment variables, secrets, and CPU values for different environments. 

The `image.build` section of the manifest is slightly different than the rest of the fields because it's the only field which doesn't correlate directly to some aspect of the underlying cloudformation and is instead handled by `docker build`. We should add functionality to build a service or job's image for a particular environment, employing a merge strategy the same way we handle the rest of the env overrides.

### PR DESCRIPTION
**Pull request by Lou1415926**
This PR:
1. implements custom`merge.Merge` logic for `image` field of workload manifest.
2. `ApplyEnv` override immediately after reading manifest, so that the image is built based on env-specific image override.

Fixes: #1702 and #2382.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

File: internal/pkg/manifest/workload.go [hunk 1]
```diff
@@ -66,6 +74,40 @@ type Image struct {
...
+		dstImage := dst.Interface().(Image)
+		srcImage := src.Interface().(Image)
+
+		err := mergo.Merge(&dstImage, srcImage, mergo.WithOverride, mergo.WithOverwriteWithEmptyValue)
+		if err != nil {
+			return err
+		}
+
+		// Perform customized merge
+		dstBuild := dst.Field(0)
```
Comment (iamhopaul123) [inline internal/pkg/manifest/workload.go]: Shall we use `FieldByName` instead to make this more reliable?

File: internal/pkg/manifest/backend_svc.go [hunk 2]
```diff
@@ -122,7 +122,8 @@ func (s BackendService) ApplyEnv(envName string) (*BackendService, error) {
 	// Apply overrides to the original service s.
 	err := mergo.Merge(&s, BackendService{
 		BackendServiceConfig: *overrideConfig,
-	}, mergo.WithOverride, mergo.WithOverwriteWithEmptyValue)
+	}, mergo.WithOverride, mergo.WithOverwriteWithEmptyValue, mergo.WithTransformers(imageTransformer{}))
```
Comment (iamhopaul123) [inline internal/pkg/manifest/backend_svc.go]: We might want to give `imageTransformer` another name since it's not actually a transformer for image, it's just for now we only customize the merging of image type. Maybe `workloadTransformer`?

**Review by iamhopaul123 — APPROVED** [review]
This is fantastic! Only a few nits 🙇🏻‍♂️

File: internal/pkg/manifest/workload.go [hunk 3]
```diff
@@ -45,6 +48,11 @@ var (
 	errInvalidAutoscaling   = errors.New(`must specify "range" if using autoscaling`)
 )
 
+// WorkloadManifest represents a workload manifest.
+type WorkloadManifest interface {
+	ApplyEnv(envName string) (WorkloadManifest, error)
+}
```
Comment (efekarakus) [inline internal/pkg/manifest/workload.go:54]: nice! This is a v neat idea!

File: internal/pkg/manifest/workload.go [hunk 4]
```diff
@@ -66,6 +74,40 @@ type Image struct {
 	DependsOn    map[string]string `yaml:"depends_on,flow"` // Add any sidecar dependencies.
 }
 
+type imageTransformer struct{}
+
+// Transformer implements customized merge logic for Image field of manifest.
+// It merges `DockerLabels` and `DependsOn` in the default manager (i.e. with configurations mergo.WithOverride, mergo.WithOverwriteWithEmptyValue)
+// And then overrides both `Build` and `Location` fields at the same time with the src values, given that they are non-empty themselves.
+func (t imageTransformer) Transformer(typ reflect.Type) func(dst, src reflect.Value) error {
```
Comment (efekarakus) [inline internal/pkg/manifest/workload.go]: What's the reason why the `image` field override doesn't work today and we need a transformer?

File: internal/pkg/manifest/workload.go [hunk 5]
```diff
@@ -66,6 +74,40 @@ type Image struct {
...
+	if typ != reflect.TypeOf(Image{}) {
+		return nil
+	}
+	return func(dst, src reflect.Value) error {
+		// Perform default merge
+		dstImage := dst.Interface().(Image)
+		srcImage := src.Interface().(Image)
```
Comment (efekarakus) [inline internal/pkg/manifest/workload.go:93]: Do we need to worry about panicking here? Should we be using `CanInterface` first?

File: internal/pkg/manifest/workload.go [hunk 6]
```diff
@@ -66,6 +74,40 @@ type Image struct {
...
+		// Perform customized merge
+		dstBuild := dst.Field(0)
+		dstLocation := dst.Field(1)
+
+		srcBuild := src.Field(0)
+		srcLocation := src.Field(1)
+
+		if !srcBuild.IsZero() || !srcLocation.IsZero() {
+			dstBuild.Set(srcBuild)
+			dstLocation.Set(srcLocation)
```
Comment (efekarakus) [inline internal/pkg/manifest/workload.go:109]: Do we need to do any sort of validation here? where users can not set both build and location?

File: internal/pkg/manifest/workload.go (hunk 4 above)
Comment (Lou1415926) [reply internal/pkg/manifest/workload.go]: Currently, if the dst has only Build, and src has Location, the merged result will have both Build and Location non-empty, while Build and Location should be mutually exclusive.

File: internal/pkg/manifest/backend_svc.go (hunk 2 above)
Comment (Lou1415926) [reply internal/pkg/manifest/backend_svc.go]: addressed!

File: internal/pkg/manifest/workload.go (hunk 6 above)
Comment (Lou1415926) [reply internal/pkg/manifest/workload.go:109]: The validation will happen afterwards. Specifically, `svc deploy` will read in the manifest, `ApplyEnv` (during which the custom transform happens), and then check if `DockerBuild` is required. During the call to check if a build is required, it will error out if `build` and `location` are set at the same time.

I guess that'd be a better place for that validation than in the transformer. The transformer should probably solely focus on custom merging strategy.

File: internal/pkg/manifest/workload.go (hunk 5 above)
Comment (Lou1415926) [reply internal/pkg/manifest/workload.go:93]: It will panic if `if the Value was obtained by accessing unexported struct fields`([doc](https://golang.org/pkg/reflect/#Value.Interface)), while `mergo` only merges exported fields, so I think we don't need to worry about panic here.

I also did some experiment where I added an unexported field to `LoadBalancedWebService` (the receiver of `ApplyEnv`). The unexported field won't get merged, hence `Transformer` won't get called.

**Review by efekarakus — APPROVED** [review]
