### PR TITLE
fix: validation of sidecar image fields in the manifest

### LINKED ISSUE #5108: service & sidecar image/image.location is confusing
According to the documentation, to point a main service to a docker registry we use `image.location` whilst sidecars expect just `image`. 

This difference in syntax is slightly confusing, but it's made worse because if you incorrectly use `image.location` in the sidecar config, it then tries to build a Dockerfile in the root of the project.

I questioned my sanity for awhile until I went back to look at the docs. 

It would be helpful if the configuration keys are consistent, and/or if sidecars fail with a loud error if missing both `image` and `image.build` instead of defaulting to looking for a Dockerfile in the root of the repo.

### PR DESCRIPTION
**Pull request by KollaAdithya**
resolves #5108
I would like to apologize 🙇 for missing this validation when I am working on the sidecar build. The below specification leads to building a container image from the root of the repository.
i.e

```
sidecars:
 nginx:
   port:8080
```
**Fix**

We have three scenarios, First two scenarios requires validation where as third scenario does not require validation.

1. If none of `image` and `image.build` and `image.location` are specified. We need a validation on the manifest because we need atleast one of the fields to be specified in the manifest.
2. If both `image.build` and `image.location` with out `image` are specified then we validate the manifest.
3. If both `image` and `image.build` is specified this will not require a validation, this will lead to unmarshal error for the manifest.[no need of validation]
```
sidecars:
 ngnix:
  image: 535307839156.dkr.ecr.us-west-2.amazonaws.com/jerry
    build: ../../demo/web/Dockerfile
```

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the Apache 2.0 License.

### CODE REVIEW

File: internal/pkg/manifest/validate.go [hunk 1]
```diff
@@ -1498,6 +1498,21 @@ func (s SidecarConfig) validate() error {
 	}
 	return s.ImageOverride.validate()
 }
+func (s SidecarConfig) validateSideCarImageFields() error {
```
Comment (iamhopaul123) [inline internal/pkg/manifest/validate.go]: Can we simplify the logic by

1. first check if `image` is set. If not error out saying it is a required field;
2. if `image` is a struct, check if either `location` or `build` is set.

This way we'll have clearer error msg for customers and from impl perspective we don't need to define a new error type specifically for this.

**Review by iamhopaul123 — COMMENTED** [review]
Also it's not your fault. We own the codebase collectively :homer-disappearing:

File: internal/pkg/manifest/validate.go [hunk 2]
```diff
@@ -1498,6 +1498,15 @@ func (s SidecarConfig) validate() error {
...
```
Comment (dannyrandall) [inline internal/pkg/manifest/validate.go]: nit, for consistency with struct
```suggestion
func (s SidecarConfig) validateSidecarImageFields() error {
```

File: internal/pkg/manifest/validate.go [hunk 3]
```diff
@@ -1498,6 +1498,15 @@ func (s SidecarConfig) validate() error {
...
+	if s.Image.Basic == nil && s.Image.Advanced.Location == nil && s.Image.Advanced.Build.isEmpty() {
+		return fmt.Errorf(`must specify one of image or image.build or image.location`)
```
Comment (dannyrandall) [inline internal/pkg/manifest/validate.go]:
```suggestion
		return fmt.Errorf(`must specify one of "image", "image.build", or "image.location"`)
```

File: internal/pkg/manifest/validate.go [hunk 4]
```diff
@@ -1498,6 +1498,15 @@ func (s SidecarConfig) validate() error {
...
+	}
+	if err := s.Image.Advanced.validate(); err != nil {
+		return fmt.Errorf(`validate "build": %w`, err)
```
Comment (dannyrandall) [inline internal/pkg/manifest/validate.go]:
```suggestion
		return fmt.Errorf(`validate "image.build": %w`, err)
```

File: internal/pkg/manifest/validate_test.go [hunk 5]
```diff
@@ -332,10 +332,16 @@ func TestLoadBalancedWebService_validate(t *testing.T) {
 					ImageConfig: testImageConfig,
 					Sidecars: map[string]*SidecarConfig{
 						"foo": {
+							Image: Union[*string, ImageLocationOrBuild]{
+								Basic: aws.String("mockImage"),
+							},
```
Comment (dannyrandall) [inline internal/pkg/manifest/validate_test.go]: these should use `BasicToUnion()` instead of directly creating the struct so that `isBasic` gets set on the Union struct

File: internal/pkg/manifest/validate.go [hunk 6]
```diff
@@ -1498,6 +1498,15 @@ func (s SidecarConfig) validate() error {
 	}
 	return s.ImageOverride.validate()
 }
+func (s SidecarConfig) validateSideCarImageFields() error {
+	if s.Image.Basic == nil && s.Image.Advanced.Location == nil && s.Image.Advanced.Build.isEmpty() {
```
Comment (dannyrandall) [inline internal/pkg/manifest/validate.go]: this can be simplified:
```suggestion
	if s.IsZero() {
```

File: internal/pkg/manifest/validate.go [hunk 7]
```diff
@@ -1498,6 +1498,15 @@ func (s SidecarConfig) validate() error {
...
+		return fmt.Errorf(`must specify one of image or image.build or image.location`)
+	}
+	if err := s.Image.Advanced.validate(); err != nil {
```
Comment (dannyrandall) [inline internal/pkg/manifest/validate.go]: this will call validate on the correct underlying type (Advanced, in this case, if it's set)
```suggestion
	if err := s.Image.validate(); err != nil {
```

**Review by dannyrandall — COMMENTED** [review]
just some nits about the `Union` type!

File: internal/pkg/manifest/validate.go [hunk 8]
```diff
@@ -2236,7 +2245,6 @@ func (i ImageLocationOrBuild) validate() error {
 		return &errFieldMutualExclusive{
 			firstField:  "build",
 			secondField: "location",
-			mustExist:   true,
```
Comment (dannyrandall) [inline internal/pkg/manifest/validate.go]: wait aren't the mutually exclusive?

Comment (KollaAdithya) [reply internal/pkg/manifest/validate.go]: I think we set `mustExist: true` if both `image.build` and `image.location` are empty. we are doing that validation over here. https://github.com/aws/copilot-cli/blob/mainline/internal/pkg/manifest/validate.go#L714:L719 

In `errors.go` we have error message based on `mustExist` field. https://github.com/aws/copilot-cli/blob/mainline/internal/pkg/manifest/errors.go#L94:L99

File: internal/pkg/manifest/validate.go [hunk 9]
```diff
@@ -1498,6 +1498,15 @@ func (s SidecarConfig) validate() error {
 	}
 	return s.ImageOverride.validate()
 }
+func (s SidecarConfig) validateSidecarImageFields() error {
```
Comment (Lou1415926) [inline internal/pkg/manifest/validate.go]: nit: the "sidecar" keyword in the function name is redundant with the struct name
```suggestion
func (s SidecarConfig) validateImages() error {
```

File: internal/pkg/manifest/validate.go (hunk 8 above)
Comment (dannyrandall) [reply internal/pkg/manifest/validate.go]: interesting - should we just remove the check here then? is it just a duplicate validation?

File: internal/pkg/manifest/validate.go [hunk 10]
```diff
@@ -1498,6 +1498,15 @@ func (s SidecarConfig) validate() error {
...
+	if s.Image.IsZero() {
+		return fmt.Errorf(`must specify one of "image", "image.build, or "image.location"`)
+	}
+	if err := s.Image.validate(); err != nil {
+		return fmt.Errorf(`validate "image.build": %w`, err)
```
Comment (Lou1415926) [inline internal/pkg/manifest/validate.go]: I thought `s.Image.validate()` would validate both `image.location` and `image.build` right?
```suggestion
		return fmt.Errorf(`validate "image": %w`, err)
```

Comment (KollaAdithya) [reply internal/pkg/manifest/validate.go]: That's true 👍

File: internal/pkg/manifest/validate.go (hunk 8 above)
Comment (KollaAdithya) [reply internal/pkg/manifest/validate.go]: It is not a redundant validation. we are checking two cases.
1. if both `image.build` and `image.location` are empty
2. If both `image.build` and `image.location` are not empty.
I just moved both validation to one place in this commit [9fd2a4e](https://github.com/aws/copilot-cli/pull/5122/commits/9fd2a4e431c3ee2242411aeb97677f6b4012e3c4)

File: internal/pkg/manifest/validate.go [hunk 11]
```diff
@@ -1498,6 +1491,15 @@ func (s SidecarConfig) validate() error {
 	}
 	return s.ImageOverride.validate()
 }
+func (s SidecarConfig) validateImages() error {
```
Comment (Lou1415926) [inline internal/pkg/manifest/validate.go]:
```suggestion
func (s SidecarConfig) validateImage() error {
```

File: internal/pkg/manifest/validate.go [hunk 12]
```diff
@@ -1459,6 +1452,9 @@ func (l Logging) validate() error {
 
 // validate returns nil if SidecarConfig is configured correctly.
 func (s SidecarConfig) validate() error {
+	if err := s.validateImages(); err != nil {
```
Comment (Lou1415926) [inline internal/pkg/manifest/validate.go]:
```suggestion
	if err := s.validateImage(); err != nil {
```

File: internal/pkg/manifest/validate.go [hunk 13]
```diff
@@ -2232,7 +2234,7 @@ func (i ImageLocationOrBuild) validate() error {
 	if err := i.Build.validate(); err != nil {
 		return fmt.Errorf(`validate "build": %w`, err)
 	}
-	if !i.Build.isEmpty() && i.Location != nil {
+	if i.Build.isEmpty() == (i.Location == nil) {
```
Comment (Lou1415926) [inline internal/pkg/manifest/validate.go:2237]: Won't this error out if we have ⬇️  ?
```yaml
sidecars:
  nginx:
     image: <mylocation>
```

Do you know what happens if we had ⬇️ 
```yaml
name: mysvc

image:
   port: 80
```
That is, neither `location` or `build` is set for the _main container_. Do we error out on validation, or do we error out when we try to build the image?

Comment (KollaAdithya) [reply internal/pkg/manifest/validate.go:2237]: In case of main container with the below config we error out on validation.

```
image:
  port: 80
```

`✘ validate manifest against environment "test": validate "image": must specify one of "build" and "location"`

In case of below  config ⬇️ for sidecars
```
sidecars:
  nginx:
     image: <mylocation>
```  
we do not error out in this case because we are doing validation on `image.build` and `image.location` only

The cases we error out  are ⬇️ 
```
sidecars:
  nginx:
   image:
    build: ../../demo/web/Dockerfile
    location: "location"
   port: 81
   ```
   `validate manifest against environment "test": validate "sidecars[nginx]": validate "image": must specify one of "build" and "location"`
  ``` 
   sidecars:
  nginx:
   port: 81
   ```
   `validate manifest against environment "test": validate "sidecars[nginx]": must specify one of "image", "image.build, or "image.location"`

Comment (Lou1415926) [reply internal/pkg/manifest/validate.go:2237]: > In case of below config ⬇️ for sidecars
> ```
> sidecars:
>  nginx:
>     image: <mylocation>
> ```
> we do not error out in this case.

I agree that we shouldn't! 


Correct me if I'm wrong though, with current logic (the revision that i'm looking at rn), we will:
1. Go to `if s.Image.IsZero() {` (L1495); because Image is not zero (it has the string) we don't error out
2. Go to `if err := s.Image.validate(); err != nil {`, where `s.image` is an `ImageLocationOrBuild`), this goes to the code that this comment is placed under. It will error out with `errFieldMutualExclusive` because both `i.Build.isEmpty`  and `i.Location == nil` are true.

Comment (KollaAdithya) [reply internal/pkg/manifest/validate.go:2237]: exactly this is true!

> 1. Go to if s.Image.IsZero() { (L1495); because Image is not zero (it has the string) we don't error out

`IsZero()` will return true both `Basic` and `Advanced` are zero. 
In this case 
```
sidecars:
 nginx:
    image: <mylocation>
```
In this case `Basic` value is set so we do not error out.

`if err := s.Image.validate(); err != nil ` will call the validation of `Union` type over here which will validate both Basic and Advanced Type.
https://github.com/aws/copilot-cli/blob/mainline/internal/pkg/manifest/union.go#L145

In this case we have `Image  Union[*string, ImageLocationOrBuild]`
as there is no validation on the `Basic `type which is just a string, but we have validation on `ImageLocationOrBuild`

Comment (dannyrandall) [reply internal/pkg/manifest/validate.go:2237]: @Lou1415926 I _think_ that `SidecarConfig.Image` has a couple layers of nesting that is making this confusing:
- `SidecarConfig.Image` is the union type between `*string` and `ImageLocationOrBuild`  
- `SidecarConfig.Image.Advanced` is how to access the `ImageLocationOrBuild` field
- `SidecarConfig.Image.validate()` calls `ImageLocationOrBuild.validate()` only if the config set `build` or `location`

Therefore, in the situation you proposed:
```
sidecars:
  nginx:
    image: <mylocation>
```

My understanding is that `s.Image.IsZero()` returns false, as you said. Then, `s.Image.Validate()` will _**not call any validation function**_, because the underlying value of the union is `*string`, which doesn't have a `validate()` function on it!

Comment (Lou1415926) [reply internal/pkg/manifest/validate.go:2237]: makes sense!!

**Review by Lou1415926 — APPROVED** [review]

File: internal/pkg/manifest/validate.go (hunk 13 above)
Comment (dannyrandall) [reply internal/pkg/manifest/validate.go:2237]: ah @KollaAdithya you beat me too it! I agree with your synopsis 👍

**Review by dannyrandall — APPROVED** [review]
