### PR TITLE
test: add integ tests for advanced count fields

### LINKED ISSUE #2218: bug: environment override on AdvancedCount not applied
Given a manifest with a count field:
```
count:
  range: 2-10
```
with the following environment override:
```
environments:
  test:
    count:
      spot: 5
```

This will return the following error:
```
convert the advanced count configuration for service fe: "count.spot" and "count.range" cannot be specified together
```

Likely caused by an issue with `manifest.ApplyEn` https://github.com/aws/copilot-cli/blob/mainline/internal/pkg/manifest/lb_web_svc.go#L204

### PR DESCRIPTION
**Pull request by SoManyHs**
Fixes https://github.com/aws/copilot-cli/issues/2218

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

File: internal/pkg/manifest/lb_web_svc.go [hunk 1]
```diff
@@ -206,6 +206,11 @@ func (s LoadBalancedWebService) ApplyEnv(envName string) (*LoadBalancedWebServic
 	if !ok {
 		return &s, nil
 	}
+	envCount := overrideConfig.TaskConfig.Count
+
+	if !envCount.IsEmpty() {
+		s.TaskConfig.Count = envCount // will this mess up the other envs?
```
Comment (efekarakus) [inline internal/pkg/manifest/lb_web_svc.go]: 😂 this made me laugh lol 

Can we add this as a unit test where we apply an `envName` to the override and see if the original count remains intact although the returned object changed?

I think this will be safe because the receiver is a concrete type `(s LoadBalancedWebService)` and not `(s *LoadBalancedWebService)` so the original object shouldn't be touched. But we should definitely validate this

**Review by efekarakus — COMMENTED** [review]
The code looks good!

File: internal/pkg/manifest/lb_web_svc.go (hunk 1 above)
Comment (efekarakus) [reply internal/pkg/manifest/lb_web_svc.go]: Do we need to make the same changes for Backend Service as well?

Comment (SoManyHs) [reply internal/pkg/manifest/lb_web_svc.go]: gah, yes. keep forgetting that -- would be nice if we could dedupe some of that logic!

Comment (SoManyHs) [reply internal/pkg/manifest/lb_web_svc.go]: Anyway, I was just pushing up https://github.com/aws/copilot-cli/pull/2223/commits/577c9b7030ad1c5abe44759c7844f0bee23f90df which should address your first comment!

**Review by efekarakus — APPROVED** [review]

**Review by Lou1415926 — APPROVED** [review]
The code 👀 GTM! Nothing much to add. Thank you for the unit tests on count!
