### PR TITLE
fix(cloudformation): should not throw ErrChangeSetEmpty when CFN tmp has bad reference

### LINKED ISSUE #2089: Updating manifest fails when addons stack present - empty addons stack changeset results in failure
If an application has an addons stack defined, after initial successful deployment, making a change to the manifest.yml and redeploying fails - Cloudformation gives an error that there are no changes to make to the addons stack and the deployment fails - which is technically true in that there are no changes to the addons stack yml, but to the main manifest yml.   Any subsequent changes which require redeployment with the addons stack in place fails due to the changeset status failing.

Screen Shot 2021-03-22 at 3 06 46 PM
Screen Shot 2021-03-22 at 3 06 34 PM

### LINKED ISSUE #2257: How to deploy service with Aurora Serverless to custom environment?
Hi! I think AWS Copilot is a great tool that makes containers easy to use.
Thank you for developing such a useful and wonderful tool.

When I create a service with Aurora Serverless, I get an error message and cannot deploy the service.
```sh
# create application with name `chronos`
$ copilot app init
Application name: chronos
✔ Created the infrastructure to manage services and jobs under application chronos.

✔ The directory copilot will hold service manifests for application chronos.

Recommended follow-up actions:
- Run `copilot init` to add a new service or job to your application.

# create environment with name `dev`
$ copilot env init
What is your environment's name? dev
Which credentials would you like to use to create dev? [profile default]
Would you like to use the default configuration for a new environment?
    - A new VPC with 2 AZs, 2 public subnets and 2 private subnets
    - A new ECS Cluster
    - New IAM Roles to manage services and jobs in your environment
 Yes, use default.
✔ Linked account 123456789101 and region ap-northeast-1 to application chronos.

✔ Proposing infrastructure changes for the chronos-dev environment.
...

# create Rails service with Load Balanced Web Service
$ copilot svc init
Note: It's best to run this command in the root of your workspace.
Service type: Load Balanced Web Service
Service name: rails
Dockerfile: ./Dockerfile.prod
no EXPOSE statements in Dockerfile ./Dockerfile.prod
Port: 3000
✔ Manifest file for service rails already exists at copilot/rails/manifest.yml, skipping writing it.
Your manifest contains configurations like your container size and port (:3000).

✔ Created ECR repositories for service rails.

Recommended follow-up actions:
- Update your manifest copilot/rails/manifest.yml to change the defaults.
- Run `copilot svc deploy --name rails --env test` to deploy your service to a test environment.

# create storage with Aurora Serverless
$ copilot storage init
Only found one workload, defaulting to: rails
Storage type: Aurora Serverless
Storage resource name: rails-cluster
Database engine: MySQL
Initial database name: app_production

# Deploy service
$ copilot svc deploy
Only found one service, defaulting to: rails
Only found one environment, defaulting to: dev
Environment dev is already on the latest version v1.3.1, skip upgrade.
...
# build docker image
# push docker image to ECR
...
✘ Proposing infrastructure changes for stack chronos-dev-rails
✘ deploy service: change set with name copilot-6012e83b-fa5a-4c90-a93d-b9f1e616b9ab for stack chronos-dev-rails has no changes
```

After deleting the `addons` directory, I can deploy Rails service.
```sh
rm -rf copilot/rails/addons

# successfully deploy
copilot svc deploy
```
But, i can deploy `test` environment that created by `copilot init` instruction even if not delete `addons` directory.
How can i deploy service to custom environment (ex. dev, staging) with Aurora Serverless.

### PR DESCRIPTION
**Pull request by iamhopaul123**
fixes #2089, fixes #2257

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by iamhopaul123** [comment]
Before the fix:
```
✘ execute svc deploy: deploy service: change set with name copilot-197f5bc9-0499-40c4-8ed0-bb5c69b66b6a for stack demo-test-hello has no changes
```
After the fix:
```
✘ Proposing infrastructure changes for stack demo-test-hello
✘ deploy service: wait for creation of change set copilot-e6e40e0a-7b2e-45bc-94df-50e75c027930 for stack demo-test-hello: ResourceNotReady: failed waiting for successful resource state: Template format error: Unresolved resource dependencies [mys3s] in the Resources block of the template
```

**Comment by bvtujo** [comment]
omg if this is what I think it is... ❤️ ❤️ ❤️ ❤️ ❤️ ❤️

**Review by efekarakus — APPROVED** [review]

File: internal/pkg/aws/cloudformation/changeset_test.go [hunk 1]
```diff
@@ -0,0 +1,353 @@
...
+	"testing"
+
+	"github.com/aws/aws-sdk-go/aws"
+	"github.com/aws/aws-sdk-go/service/cloudformation"
+	"github.com/aws/copilot-cli/internal/pkg/aws/cloudformation/mocks"
+	"github.com/golang/mock/gomock"
+	"github.com/stretchr/testify/require"
+)
+
+func TestChangeSet_createAndExecute(t *testing.T) {
```
Comment (efekarakus) [inline internal/pkg/aws/cloudformation/changeset_test.go]: Can we instead capture this part of our exposed APIs like the `UpdateStack` test instead of creating a separate one here

Comment (iamhopaul123) [reply internal/pkg/aws/cloudformation/changeset_test.go]: addressed~

**Review by bvtujo — APPROVED** [review]
This is so good, PH. The new tests look amazing
