### PR TITLE
fix: add UntagResource permission for KMS key

### LINKED ISSUE #1199: Can't create env in a different account (not authorized to perform: kms:UntagResource)
I tried creating a new environment in a different AWS account but ran into an issue with `KMSKey`.

```
Exception=[class software.amazon.awssdk.services.kms.model.KmsException] ErrorCode=[AccessDeniedException], ErrorMessage=[User: arn:aws:sts::123:assumed-role/foo-executionrole/abc-123 is not authorized to perform: kms:UntagResource on resource: arn:aws:kms:eu-central-1:123:key/def-456]
```

I can see that the key policy on `arn:aws:kms:eu-central-1:123:key/def-456` does not allow `kms:UntagResource`.

```
{
    "Version": "2012-10-17",
    "Id": "StackSet-sample-java-infrastructure-db3e2f97-ea6a-4a49-9e62-3533e652841a",
    "Statement": [
        {
            "Effect": "Allow",
            "Principal": {
                "AWS": "arn:aws:iam::123:root"
            },
            "Action": [
                "kms:Create*",
                "kms:Describe*",
                "kms:Enable*",
                "kms:List*",
                "kms:Put*",
                "kms:Update*",
                "kms:Revoke*",
                "kms:Disable*",
                "kms:Get*",
                "kms:Delete*",
                "kms:ScheduleKeyDeletion",
                "kms:CancelKeyDeletion",
                "kms:Tag*"
            ],
            "Resource": "*"
        },
        {
            "Effect": "Allow",
            "Principal": {
                "AWS": "arn:aws:iam::123:root"
            },
            "Action": [
                "kms:Encrypt",
                "kms:Decrypt",
                "kms:ReEncrypt*",
                "kms:GenerateDataKey*",
                "kms:DescribeKey"
            ],
            "Resource": "*"
        }
    ]
}
```

CLI version: 0.2.0

### PR DESCRIPTION
**Pull request by kohidave**
There seems to be an issue with the current KMS CF resource
that is causing superfluous tag/untag calls. This new permission
fixes that issue.

A customer encountered this issue (#1199) when using resource tags,
so I've also updated the e2e tests to include setting resource tags.

In the future, this permission will be useful if we want to support
updating tags at the app level (removing a tag, for example) so it's
not entierly a hack :)

Fixes #1199 

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

File: e2e/internal/client/cli.go [hunk 1]
```diff
@@ -312,12 +313,23 @@ func (cli *CLI) EnvList(appName string) (*EnvListOutput, error) {
...
 */
 func (cli *CLI) AppInit(opts *AppInitRequest) (string, error) {
 	commands := []string{"app", "init", opts.AppName}
 	if opts.Domain != "" {
 		commands = append(commands, "--domain", opts.Domain)
 	}
+
+	if len(opts.Tags) > 0 {
+		commands = append(commands, "--resource-tags")
+		tags := []string{}
```
Comment (efekarakus) [inline e2e/internal/client/cli.go:326]: you're killing me david
