### PR TITLE
fix: clean the elb access bucket at `env deploy` when it is disabled in the env mft

### LINKED ISSUE #5428: Unable to deploy environment changes
Hi, I'm unable to deploy changes to my environment using `copilot env deploy`. For some context/background, I've been using copilot very successfully since version 1.8.1. At that time, there were no environment manifests so my project did not have one until recently.

While on v1.31.0, I ran `copilot env init` to create the manifest for my staging environment. I set the manifest to this:
```
name: staging
type: Environment
http:
  public:
    access_logs: true
```
And then deployed it using `copilot env deploy`. This worked fine. I did all of this to try to troubleshoot a different issue I'm having. I posted on gitter about that one.

Since the logs were mostly noisy, I attempted to change the env manifest to disable access logs and enable observability insights instead:
```
name: staging
type: Environment
observability:
  container_insights: true
http:
  public:
    access_logs: false
```

After attempting to deploy, I received this error:
```
copilot env deploy
Name: staging
✔ Proposing infrastructure changes for the stronghaven-staging environment.
- Creating the infrastructure for the stronghaven-staging environment.               [update rollback complete]  [24.9s]
  The following resource(s) failed to update: [Cluster, PublicLoadBalanc
  er, EnvironmentManagerRole].
  - An ECS cluster to group your services                                            [update complete]           [4.3s]
    Resource update cancelled
  - Add an A-record to the hosted zone for the domain alias                          [not started]
  - An IAM Role to describe resources in your environment                            [update complete]           [4.3s]
    Resource update cancelled
  - An Application Load Balancer to distribute public traffic to your services       [update complete]           [0.0s]
    Resource handler returned message: "Attributes cannot be empty (Servic
    e: ElasticLoadBalancingV2, Status Code: 400, Request ID: 838a06dc-02a9
    -40b8-a5ab-2d924a53cd3c)" (RequestToken: ca63222c-0a11-7ca2-8715-364b9
    3ef5540, HandlerErrorCode: InvalidRequest)

✘ deploy environment staging: stack stronghaven-staging did not complete successfully and exited with status UPDATE_ROLLBACK_COMPLETE
```

I'm really confused about what is happening inside the environment. I appreciate any help in identifying and resolving the issue.

### PR DESCRIPTION
**Pull request by iamhopaul123**
Fixes https://github.com/aws/copilot-cli/issues/5428

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the Apache 2.0 License.

### CODE REVIEW

File: cf-custom-resources/lib/bucket-cleaner.js [hunk 1]
```diff
@@ -0,0 +1,200 @@
...
+      })
+    }
+    // After deleting other versions, remove delete markers version.
+    // For info on "delete marker": https://docs.aws.amazon.com/AmazonS3/latest/dev/DeleteMarker.html
+    for (const deleteMarker of listResp.DeleteMarkers) {
+      objectsToDelete.push({
+        Key: deleteMarker.Key,
+        VersionId: deleteMarker.VersionId
+      })
+    }
```
Comment (KollaAdithya) [inline cf-custom-resources/lib/bucket-cleaner.js]: I learnt this very new when learning typescript 😄 
may be can combine these two for loops
```
let objectsToDelete = [
    ...listResp.Versions.map(version => ({ Key: version.Key, VersionId: version.VersionId })),
    ...listResp.DeleteMarkers.map(marker => ({ Key: marker.Key, VersionId: marker.VersionId }))
  ];
 ```

File: cf-custom-resources/lib/bucket-cleaner.js [hunk 2]
```diff
@@ -0,0 +1,200 @@
...
+    const delResp = await s3.deleteObjects({
+      Bucket: bucketName,
+      Delete: {
+        Objects: objectsToDelete,
+        Quiet: true
+      }
+    }).promise()
+    if (delResp.Errors.length > 0) {
+      throw new AggregateError([new Error(`${delResp.Errors.length}/${objectsToDelete.length} objects failed to delete`),
```
Comment (KollaAdithya) [inline cf-custom-resources/lib/bucket-cleaner.js:110]: I have a question on AggregateError. Isn't this already an inbuilt Error in js 16 🤔 

And also do we need to log all the error messages instead of only first error or is the first error good.

```
  const errorMessages = delResp.Errors.map(
    error => new Error(`Failed on key "${error.Key}": ${error.Message}`)
  );
```

File: cf-custom-resources/lib/bucket-cleaner.js [hunk 3]
```diff
@@ -0,0 +1,200 @@
...
+  });
+};
+
+/**
+ * Delete all objects in a bucket.
+ *
+ * @param {string} bucketName Name of the bucket to be cleaned.
+ */
+const cleanBucket = async function (bucketName) {
+  let s3 = new aws.S3();
```
Comment (KollaAdithya) [inline cf-custom-resources/lib/bucket-cleaner.js]: can `s3` be a const as this is never reassigned.

File: cf-custom-resources/lib/bucket-cleaner.js (hunk 2 above)
Comment (iamhopaul123) [reply cf-custom-resources/lib/bucket-cleaner.js:110]: > I have a question on AggregateError. Isn't this already an inbuilt Error in js 16 🤔

That's what I thought too but it doesn't seem to be the case.

> And also do we need to log all the error messages instead of only first error or is the first error good.

I just migrate what we do currently and I think the first error msg can be a good start for triaging.

File: cf-custom-resources/lib/bucket-cleaner.js [hunk 4]
```diff
@@ -0,0 +1,191 @@
...
+        break;
+      case "Delete":
+        await cleanBucket(props.BucketName);
+        break;
+      default:
+        throw new Error(`Unsupported request type ${event.RequestType}`);
+    }
+    await report(event, context, "SUCCESS", physicalResourceId, responseData);
+  } catch (err) {
+    console.log(`Caught error ${err}.`);
```
Comment (Lou1415926) [inline cf-custom-resources/lib/bucket-cleaner.js:142]: should this be a best-effort clean up? i.e. if there is an error, we log it, but don't fail the operation.

Comment (iamhopaul123) [reply cf-custom-resources/lib/bucket-cleaner.js:142]: We might want to surface the error to users if the custom resource fails, because it's less likely for this custom resource to fail for random reasons 💭 This is what we are doing to our stackset bucket and static site bucket too.

**Review by KollaAdithya — APPROVED** [review]
LGTM!

File: internal/pkg/template/templates/environment/partials/elb-access-logs.yml [hunk 5]
```diff
@@ -41,4 +41,60 @@ ELBAccessLogsBucket:
...
+    PermissionsBoundary: !Sub 'arn:${AWS::Partition}:iam::${AWS::AccountId}:policy/{{.PermissionsBoundary}}'
+    {{- end}}
+    Path: /
+    Policies:
+      - PolicyName: "CleanELBAccessLogs"
+        PolicyDocument:
+          Version: '2012-10-17'
+          Statement:
+            - Effect: Allow
+              Action: "s3:*"
```
Comment (Lou1415926) [inline internal/pkg/template/templates/environment/partials/elb-access-logs.yml]: maybe scope down to just the actions we need 👀 ?

**Review by Lou1415926 — APPROVED** [review]

File: internal/pkg/template/templates/environment/partials/elb-access-logs.yml (hunk 5 above)
Comment (iamhopaul123) [reply internal/pkg/template/templates/environment/partials/elb-access-logs.yml]: i've tried but it seems like the action that we use in the custom resource is not a valid one for IAM...we'll keep it for now until someone has better idea. Should be good enough for now as at least we limit the resource to only this bucket.

Comment (dannyrandall) [reply internal/pkg/template/templates/environment/partials/elb-access-logs.yml]: i think [`HeadBucket`](https://docs.aws.amazon.com/AmazonS3/latest/API/API_HeadBucket.html) is `s3:ListBucket`, [`ListObjectVersions`](https://docs.aws.amazon.com/AmazonS3/latest/API/API_ListObjectVersions.html) is `s3:ListBucketVersions` (though you could add `s3:ListBucket` to be safe), and [`DeleteObjects`](https://docs.aws.amazon.com/AmazonS3/latest/API/API_DeleteObjects.html) is.... `s3:DeleteObject` and `s3:DeleteObjectVersion`?
