### PR TITLE
fix(lambda): should correctly set PhysicalResourceId

### LINKED ISSUE #2530: Unable to upgrade Copilot environment from v1.2.0 to v1.4.0: HTTPS Listener failed to update
I am managing multiple applications using Copilot and all of them were created using the --domain flag. I've recently upgraded the Copilot version used in my build process, and I'm consistently encountering the same error when Copilot tries to upgrade the environment.
```
✘ Failed to upgrade environment dev's template to version v1.4.0.. 
✘ upgrade environment dev from version v1.2.0 to version v1.4.0: update and wait for stack drone-csup-dev: wait until stack drone-csup-dev update is complete: ResourceNotReady: failed waiting for successful resource state
```

When I look at the CloudFormation stack events, the `HTTPSListener` failed to update with the following message:

```
Resource handler returned message: "Certificate ARN '2021/06/28/[$LATEST]03124a95687c4fd58f341966dbe6d9e2' is not valid (Service: ElasticLoadBalancingV2, Status Code: 400, Request ID: c942874d-8bd3-4faa-b006-d536da4ed9c9, Extended Request ID: null)" (RequestToken: 16666b21-d7a8-b379-77c7-8c3234ff1748, HandlerErrorCode: InvalidRequest)
```

It looks like a CloudWatch path is being substituted for an ACM Certificate ARN for the listener. I briefly looked at the stack and see the HTTPSCert object is a custom Lambda function that presumably outputs this ARN. My guess is there is an issue with that code.

I was able in one instance to rebuild the environment successfully after deleting all the associated services, but I would prefer not to take that route to rebuild three environments each for multiple applications, including prod environments. Any idea with this is happening, or suggestions for a workaround?

---
 EDIT: Furthermore, I looked in the CloudWatch log for what I assume to be the erroneous run of the Lambda function, but there is no useful information there, only:
 ```
2021-06-28T14:45:51.345+02:00 | START RequestId: ec44b656-aaa8-4a7f-b18a-32f63cf7353f Version: $LATEST
-- | --
  | 2021-06-28T14:45:51.515+02:00 | END RequestId: ec44b656-aaa8-4a7f-b18a-32f63cf7353f
  | 2021-06-28T14:45:51.515+02:00 | REPORT RequestId: ec44b656-aaa8-4a7f-b18a-32f63cf7353f Duration: 167.92 ms Billed Duration: 168 ms Memory Size: 512 MB Max Memory Used: 86 MB Init Duration: 457.88 ms
```

### PR DESCRIPTION
**Pull request by iamhopaul123**
#2524 only fixes the env controller lambda while this PR fixes all our lambda for setting `PhysicalResourceId` correctly. Fixes #2530

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

File: cf-custom-resources/lib/custom-domain.js [hunk 1]
```diff
@@ -172,7 +172,7 @@ const writeARecord = async function (
  */
 exports.handler = async function (event, context) {
   var responseData = {};
-  var physicalResourceId;
+  const physicalResourceId = `${event.LogicalResourceId}`;
```
Comment (Lou1415926) [inline cf-custom-resources/lib/custom-domain.js]: Could this be just `event.LogicalResourceId` without wrapped within "`${}`"?

File: cf-custom-resources/lib/dns-cert-validator.js [hunk 2]
```diff
@@ -523,7 +523,7 @@ const clients = function (region, rootDnsRole) {
  */
 exports.certificateRequestHandler = async function (event, context) {
   var responseData = {};
-  var physicalResourceId;
+  var physicalResourceId = event.PhysicalResourceId;
```
Comment (Lou1415926) [inline cf-custom-resources/lib/dns-cert-validator.js:528]: This changes the original behavior a little bit for "Update". Originally, it is possible that `physicalResourceId` is the logstreamName, now it's not because `event.PhysicalResourceId` is always given with `Update` and `Delete`. Would this matter?

File: cf-custom-resources/lib/dns-delegation.js [hunk 3]
```diff
@@ -264,28 +262,27 @@ const waitForRecordSetChange = function (route53, changeId) {
 
 exports.domainDelegationHandler = async function (event, context) {
   var responseData = {};
-  var physicalResourceId;
+  const props = event.ResourceProperties;
+  const physicalResourceId = props.SubdomainName;
```
Comment (Lou1415926) [inline cf-custom-resources/lib/dns-delegation.js:268]: For `Delete`, it was `event.PhysicalResourceId`, do we guarantee somewhere that `props.SubdomainName` is the same as `event.PhysicalResourceId` when the "Delete" action is performed? I feel like in that case we should include one line of explanation here, maybe?

File: cf-custom-resources/lib/enable-long-arns.js [hunk 4]
```diff
@@ -97,18 +97,16 @@ const enableLongArnFormat = async function () {
...
 exports.handler = async function (event, context) {
   var responseData = {};
-  var physicalResourceId;
+  const physicalResourceId = event.PhysicalResourceId || event.LogicalResourceId;
 
   try {
     switch (event.RequestType) {
       case "Create":
         await enableLongArnFormat();
-        physicalResourceId = event.PhysicalResourceId;
```
Comment (Lou1415926) [inline cf-custom-resources/lib/enable-long-arns.js:106]: Interesting isn't `PhysicalResourceId` always `undefined` for "Create" event? Did we find a bug here while fixing another bug 🤔

File: cf-custom-resources/test/alb-rule-priority-generator-test.js [hunk 5]
```diff
@@ -93,12 +93,17 @@ describe("ALB Rule Priority Generator", () => {
     const requestType = "Update";
     const request = nock(ResponseURL)
       .put("/", (body) => {
-        return body.Status === "SUCCESS";
+        return (
```
Comment (Lou1415926) [inline cf-custom-resources/test/alb-rule-priority-generator-test.js:102]: Thanks for updating the tests!!!

**Review by Lou1415926 — COMMENTED** [review]
Thanks for fixing this!

File: cf-custom-resources/lib/custom-domain.js (hunk 1 above)
Comment (iamhopaul123) [reply cf-custom-resources/lib/custom-domain.js]: yes sorry forget to fix this one.

File: cf-custom-resources/lib/dns-cert-validator.js (hunk 2 above)
Comment (iamhopaul123) [reply cf-custom-resources/lib/dns-cert-validator.js:528]: I think this is a bug fix so i would say it's ok.

File: cf-custom-resources/lib/enable-long-arns.js (hunk 4 above)
Comment (efekarakus) [reply cf-custom-resources/lib/enable-long-arns.js:106]: Yea

**Review by efekarakus — APPROVED** [review]
LGTM :shipit: after addressing Wanxian's comment

File: cf-custom-resources/lib/alb-rule-priority-generator.js [hunk 6]
```diff
@@ -150,7 +150,7 @@ exports.nextAvailableRulePriorityHandler = async function (event, context) {
       "FAILED",
       physicalResourceId,
       null,
-      err.message
+      `${err.message} (Log: ${context.logStreamName}/${context.logGroupName})`
```
Comment (Lou1415926) [inline cf-custom-resources/lib/alb-rule-priority-generator.js]: Just throwing this out: what about `Reason: ${reason} (Log: ${context.logStreamName}/${context.logGroupName})` in `report`? This is great too though so no need to change it.

**Review by Lou1415926 — APPROVED** [review]
:shipit:
