### PR TITLE
fix(addon): enable outputing values from parameters in a template

### LINKED ISSUE #1565: Can't use number parameters in addon templates and pass them to integer fields with !Ref
If I specify parameter of type `Number` in addon template and use it with `!Ref` in a field that requires integer, `copilot deploy` will fail:

```
: json: cannot unmarshal string into Go struct field Template.Resources of type int
``` 

It is convenient to use parameters to DRY values in templates and keep them app configuration in sync with infrastructure:

```yaml
Parameters:
  MinPort:
    Type: Number
    Default: 40000
  MaxPort:
    Type: Number
    Default: 49999

Resources:
  EnvironmentSecurityGroupIngressTCPWebRTC:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      Description: Ingress TCP for WebRTC media streams
      GroupId:
        Fn::ImportValue:
          !Sub "${App}-${Env}-EnvironmentSecurityGroup"
      IpProtocol: tcp
      CidrIp: '0.0.0.0/0'
      FromPort: !Ref MinPort # <- Problem is here
      ToPort:   !Ref MaxPort # <- Problem is here

Outputs:
  MediasoupMinPort:
    Value: !Ref MinPort
  MediasoupMaxPort:
    Value: !Ref MaxPort
```

But if I execute this template with `aws cloudformation create-stack` it will be created successfully.

Related issues (as copilot use [goformation](https://github.com/awslabs/goformation/)): https://github.com/awslabs/goformation/issues/252 and https://github.com/awslabs/goformation/issues/304.

<details>
<summary>Full example here</summary>

`copilot/app/addons/ingress-rules.yml`:
```yaml
Parameters:
  App:
    Type: String
    Description: Your application's name.
  Env:
    Type: String
    Description: The environment name your service, job, or workflow is being deployed to.
  MediasoupMinPort:
    Type: Number
    Default: 40000
    Description: "Start of the port range used to receive WebRTC connections with media streams from peers."
    MinValue: 1024
    MaxValue: 65535
  MediasoupMaxPort:
    Type: Number
    Default: 49999
    Description: "End of the port range used to receive WebRTC connections with media streams from peers."
    MinValue: 1024
    MaxValue: 65535

Resources:
  EnvironmentSecurityGroupIngressTCPWebRTC:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      Description: Ingress TCP for WebRTC media streams
      GroupId:
        Fn::ImportValue:
          !Sub "${App}-${Env}-EnvironmentSecurityGroup"
      IpProtocol: tcp
      CidrIp: '0.0.0.0/0'
      FromPort: !Ref MediasoupMinPort
      ToPort:   !Ref MediasoupMaxPort

  EnvironmentSecurityGroupIngressUDPWebRTC:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      Description: Ingress UDP for WebRTC media streams
      GroupId:
        Fn::ImportValue:
          !Sub "${App}-${Env}-EnvironmentSecurityGroup"
      IpProtocol: udp
      CidrIp: '0.0.0.0/0'
      FromPort: !Ref MediasoupMinPort
      ToPort:   !Ref MediasoupMaxPort

Outputs:
  MediasoupMinPort:
    Description: "Start of the port range used to receive WebRTC connections with media streams from peers."
    Value: !Ref MediasoupMinPort
  MediasoupMaxPort:
    Description: "End of the port range used to receive WebRTC connections with media streams from peers."
    Value: !Ref MediasoupMaxPort
```

How to run it via CloudFormation:
```sh
app=panel-discussions
env=test
aws cloudformation create-stack --stack-name $app-$env-vpc-subnets --template-body file://copilot/app/addons/ingress-rules.yml --parameters ParameterKey=App,ParameterValue=$app ParameterKey=Env,ParameterValue=$env --tags Key=copilot-application,Value=$app Key=copilot-environment,Value=$env
```
</details>

### PR DESCRIPTION
**Pull request by efekarakus**
Fixes #1565

Also removes the goformation library in favor of the official YAML library for Go.
By using the yaml library, we get two additional benefits:
- Gets rid of a parsing bug from the goformation lib #1402.
- Reduces our binary size by 9MB.
   Before:
   ```
   ls -lh bin/local
   56M copilot
   ```
   After:
   ```
   ls -lh bin/local
   47M copilot
   ```

_By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice._

### CODE REVIEW

File: internal/pkg/addon/output.go [hunk 1]
```diff
@@ -25,52 +29,127 @@ type Output struct {
...
+	if resourcesNode.Kind != yaml.MappingNode {
+		// "Resources" is a required field in CloudFormation, check if it's defined as a map.
+		return nil, errors.New(`"Resources" field in cloudformation template is not a map`)
+	}
+
+	// The content of a !!map, like the "Resources" field, always come in pairs.
+	// The first element represents the key, ex: {Value: "Cluster", Kind: ScalarNode, Tag: "!!str", Content: nil}
+	// The second element holds the values such as "Type" and "Properties", ex: {Value: "", Kind: MappingNode, Tag:"!!map", Content:[...]}
+	typeFor = make(map[string]string)
+	for i := 0; i < len(resourcesNode.Content); i += 2 {
```
Comment (iamhopaul123) [inline internal/pkg/addon/output.go]: this logic looks very similar as https://github.com/aws/copilot-cli/blob/1b33c83e488047d5a7a42918bef4775464807519/internal/pkg/addon/cloudformation.go#L221-L226 and https://github.com/aws/copilot-cli/blob/e9e3994b0ad535be0627f2ce22b3f065e13d4e7e/internal/pkg/aws/cloudformation/parse.go#L31-L37. Can we possibly modularize and reuse this?

File: internal/pkg/addon/output.go [hunk 2]
```diff
@@ -25,52 +29,127 @@ type Output struct {
...
+		}{}
+		if err := fieldsNode.Decode(&fields); err != nil {
+			return nil, fmt.Errorf(`decode the "Type" field of resource "%s": %w`, logicalIDNode.Value, err)
+		}
+		typeFor[logicalIDNode.Value] = fields.Type
+	}
+	return typeFor, nil
+}
+
+func parseOutputNodes(outputsNode *yaml.Node) ([]*outputNode, error) {
```
Comment (iamhopaul123) [inline internal/pkg/addon/output.go:91]: same for this function

**Review by iamhopaul123 — COMMENTED** [review]
So glad we'll be able to make our binary relatively smaller and fix those parsing bugs! Thank you!

**Review by bvtujo — APPROVED** [review]
This looks good to me, thank you so much for diving into the YAML internals on this.

File: internal/pkg/addon/output.go (hunk 1 above)
Comment (efekarakus) [reply internal/pkg/addon/output.go]: 💭 I think it's mostly looking bulky because of the redundant comments. Maybe I can do this:

```go
package yamlutil

func KeyValueMap(mappingNode *yaml.Node) map[*yaml.Node]*yaml.Node
```
But I don't want util packages 😭 especially with only one function.

I can create this function at least in this pkg since the same text is repeated three times. Let me know if you have any other ideas.

File: internal/pkg/addon/output.go (hunk 2 above)
Comment (efekarakus) [reply internal/pkg/addon/output.go:91]: OK done for both! https://github.com/aws/copilot-cli/pull/1804/commits/7a864d46fd61c3cba28b73132d400c5ef6fdac53

File: internal/pkg/addon/output.go (hunk 1 above)
Comment (iamhopaul123) [reply internal/pkg/addon/output.go]: A util pkg with full of all sorts of garbage function is all we need :)

**Review by iamhopaul123 — APPROVED** [review]
Ship it :ship:
